### ISSUE TITLE
Tailing log file reprocesses the entire file every Refresh_Interval

### ISSUE THREAD

**Issue by alihushyar** [fluent/fluent-bit#757] opened 2018-09-06 22:14 UTC
## Bug Report

**Describe the bug**
I am tailing a single log file using version 0.14.1.  Very basic tail input with stdout output.  Every Refresh_Interval, the entire file is reprocessed and the same events are reprocessed.  

Even if the file is static with a single event, it will read the file and output the event when FB starts, and then repeat the event every Refresh_Interval.  Is this expected behavior?  

DB_Offset file is being updated but doesn't seem it is being used.  

[SERVICE]
    # Flush
    # =====
    # Set an interval of seconds before to flush records to a destination
    Flush        5

    # Daemon
    # ======
    # Instruct Fluent Bit to run in foreground or background mode.
    Daemon       Off

    # Log_Level
    # =========
    # Set the verbosity level of the service, values can be:
    #
    # - error
    # - warning
    # - info
    # - debug
    # - trace
    #
    # By default 'info' is set, that means it includes 'error' and 'warning'.
    Log_Level    info

    # Parsers_File
    # ============
    # Specify an optional 'Parsers' configuration file
    Parsers_File parsers.conf
    Plugins_File plugins.conf

    # HTTP Server
    # ===========
    # Enable/Disable the built-in HTTP Server for metrics
    HTTP_Server  Off
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020

[INPUT]
    Name    tail
    Tag     osquery
    Path    /var/log/osquery/osqueryd.results.log
    DB      /var/log/osquery/fblogs.db
    Refresh_Interval    10

[OUTPUT]
    Name  stdout
    Match *

**Comment by edsiper** [comment] 2018-09-06 22:19
is the file being rotated ?

**Comment by alihushyar** [comment] 2018-09-06 22:30
No rotation.  To be sure I just created a static file with a single line of data and started tailing that file.  The file contains the following line: 

{"name":"yo_test"}

The stdout output with a refresh interval of 10 looks like the following:

Alis-MBP:fluent-bit alihushyar$ sudo fluent-bit --config=fluent-bit.conf -v

Fluent-Bit v0.14.1
Copyright (C) Treasure Data

[2018/09/06 15:27:40] [Warning] [config] I cannot open /usr/local/Cellar/fluent-bit/0.14.1/etc/fluent-bit/plugins.conf file
[2018/09/06 15:27:40] [ info] [engine] started (pid=63562)

[0] osqueryd_snapshots: [1536272860.000000000, {"name"=>"yo_test"}]
[0] osqueryd_snapshots: [1536272870.000000000, {"name"=>"yo_test"}]
[0] osqueryd_snapshots: [1536272880.000000000, {"name"=>"yo_test"}]
[0] osqueryd_snapshots: [1536272890.000000000, {"name"=>"yo_test"}]
[0] osqueryd_snapshots: [1536272900.000000000, {"name"=>"yo_test"}]
[0] osqueryd_snapshots: [1536272910.000000000, {"name"=>"yo_test"}]
[0] osqueryd_snapshots: [1536272920.000000000, {"name"=>"yo_test"}]

**Comment by edsiper** [comment] 2018-09-07 02:35
I cannot reproduce the problem locally, would you please provide a sosreport ?: 

```
$ fluent-bit -c fluent-bit.conf  --sosreport
```

**Comment by alihushyar** [comment] 2018-09-07 02:39
You know what.  I just noticed that I only get this behavior for any file or directory under /var/log on my Mac.  Otherwise it works as describes.  Thank you for looking into this.

**Comment by JavaCS3** [comment] 2018-09-07 05:20
@edsiper I have the same issue if tailing a static file.

**Comment by edsiper** [comment] 2018-09-07 14:41
@JavaCS3 is this a OSX too ?

**Comment by JavaCS3** [comment] 2018-09-10 10:10
Yes, but it happens even if inside of Docker container on Mac OSX.

**Comment by edsiper** [comment] 2018-09-10 16:33
I was able to reproduce the problem.

The root cause that I've found for this problem is the following:

- Fluent Bit start monitoring /var/log/file.log
- Once it validate if a file is rotated, it finds the file associated to the open file is translated to /private/var/log/file.log
- OSX /var is a symbolic link to /private/var
- Fluent Bit assumes the file was rotated, so every few seconds it start reading the file from position zero.

I am still working on this, despite it can be solved with moving the config path to /private/var/log/... I want to check a better way (work in process).

**Comment by edsiper** [comment] 2018-09-10 16:46
Issue only reproducible when using stat(2) backend (tail_fs_stat), Linux based on inotify works properly.

**Comment by JavaCS3** [comment] 2018-09-11 02:02
Seems you are the only one working on issues. No more people? @edsiper

**Comment by edsiper** [comment] 2018-09-11 04:47
@JavaCS3 as fulltime yes, there are other community members who contribute also (plugins, code fixes, etc)

**Comment by edsiper** [comment] 2018-09-12 17:13
@alihushyar @JavaCS3 

I've pushed a [branch](https://github.com/fluent/fluent-bit/tree/issue_757) with a fix for OSX, would you please build from that one and validate the fix ?

https://github.com/fluent/fluent-bit/archive/issue_757.zip

**Comment by edsiper** [comment] 2018-09-21 21:34
the fix has been merged into GIT master and 0.14 branch (to be released as part of 0.14.3)

thanks

**Closed by edsiper** 2018-09-21 21:34 UTC
Labels: bug, fixed
