### ISSUE TITLE
Fluent-bit fails to send logs to an elasticsearch datastream

### ISSUE THREAD

**Issue by pablomg92z** [fluent/fluent-bit#2664] opened 2020-10-09 12:09 UTC
## Bug Report

**Describe the bug**
Fluentbit fails to send logs to an elasticsearch datastream index using the elasticsearch output plugin. This is caused because in datastreams is not allowed to use the operation "index" when a bulk API call is issued to elasticsearch, which is what fluent-bit does. For more info you can see why this is not allowed here: [Use of datastreams](https://www.elastic.co/guide/en/elasticsearch/reference/current/use-a-data-stream.html). Datastreams were introduced in Elasticsearch version 7.9 and it is the recommended way to store logs from now on. 

**To Reproduce**
- Use the elasticsearch output plugin of fluent-bit to send logs to an index in elasticsearch that is configured as a datastream
- Example error message:
```
"
PS C:\Users\Pablo\fluentbit> C:\"Program Files"\td-agent-bit\bin\fluent-bit.exe -c .\fluent-bit.conf
Fluent Bit v1.5.7                                                                                                       * Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2020/10/08 00:11:51] [ info] Configuration:
[2020/10/08 00:11:51] [ info]  flush time     | 5.000000 seconds
[2020/10/08 00:11:51] [ info]  grace          | 5 seconds
[2020/10/08 00:11:51] [ info]  daemon         | 0
[2020/10/08 00:11:51] [ info] ___________
[2020/10/08 00:11:51] [ info]  inputs:
[2020/10/08 00:11:51] [ info]      winlog
[2020/10/08 00:11:51] [ info] ___________
[2020/10/08 00:11:51] [ info]  filters:
[2020/10/08 00:11:51] [ info] ___________
[2020/10/08 00:11:51] [ info]  outputs:
[2020/10/08 00:11:51] [ info]      es.0
[2020/10/08 00:11:51] [ info] ___________
[2020/10/08 00:11:51] [ info]  collectors:
[2020/10/08 00:11:51] [ info] [engine] started (pid=35696)
[2020/10/08 00:11:51] [debug] [engine] coroutine stack size: 98302 bytes (96.0K)
[2020/10/08 00:11:51] [debug] [storage] [cio stream] new stream registered: winlog.0
[2020/10/08 00:11:51] [ info] [storage] version=1.0.5, initializing...
[2020/10/08 00:11:51] [ info] [storage] in-memory
[2020/10/08 00:11:51] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/10/08 00:11:51] [debug] [input:winlog:winlog.0] load channel<Windows PowerShell record=50737 time=1599082024>
[2020/10/08 00:11:51] [debug] [output:es:es.0] host=127.0.0.1 port=9200 uri=/_bulk index=my_index type=create
[2020/10/08 00:11:51] [debug] [router] match rule winlog.0:es.0
[2020/10/08 00:11:51] [ info] [sp] stream processor started
[2020/10/08 00:12:01] [debug] [input:winlog:winlog.0] read 32432 bytes from 'Windows PowerShell'
[2020/10/08 00:12:01] [debug] [input:winlog:winlog.0] save channel<Windows PowerShell record=50767 time=1599082024>
[2020/10/08 00:12:06] [debug] [task] created task=00000144C03816F0 id=0 OK
[2020/10/08 00:12:06] [debug] [output:es:es.0] HTTP Status=200 URI=/_bulk
[2020/10/08 00:12:06] [error] [output:es:es.0] could not pack/validate JSON response
{"took":0,"errors":true,"items":[{"index":{"_index":"my_index","_type":"create","_id":"ca11aa38-1df5-6400-da10-856a55d17c1c","status":400,"error":{"type":"illegal_argument_exception","reason":"only write ops with an op_type of create are allowed in data streams"}}},
errors":true,"items":[{"index":{"_index":"my_index","_type":"create","_id":"ca11aa38-1df5-6400-da10-856a55d17c1c","status":400,"error":{"type":"illegal_argument_exception","reason":"only write ops with an op_type of create are allowed in data streams"
```

**Expected behavior**
 Logs should be received successfully in Elasticsearch

**Your Environment**

* Version used: 1.5.7 windows version installed with .exe
* Configuration: default fluentbit.conf Windows configuration plus:
[INPUT]
    Name         winlog
    Channels     Windows PowerShell
    Interval_Sec 10
    DB           winlog.sqlite

[OUTPUT]
    Name  es
    Match **
    Host  127.0.0.1
    Port  9200
    Index my_index
    type create

* Operating System and version: Windows
* Filters and plugins: elasticsearch output plugin

**Comment by moleksyuk** [comment] 2021-03-18 14:14
Why is it closed? Is it fixed?

**Comment by agup006** [comment] 2021-03-18 15:12
> Why is it closed? Is it fixed?

Auto closes, re-opened

**Comment by alexanderccc** [comment] 2021-03-24 17:37
Do we have an eta on when this might become available?

**Comment by moleksyuk** [comment] 2021-04-28 13:17
Up

**Comment by agup006** [comment] 2021-05-29 02:18
@nokute78 im wondering if this could be done similar to channel in Splunk output plugin

**Comment by nokute78** [comment] 2021-05-29 04:39
I think it is fixed by #2026.
[Current master](https://github.com/fluent/fluent-bit/blob/99c2f68b92e43d01924bddc1c770542ff9df3f5f/plugins/out_es/es_bulk.h#L28) supports "create" action, not "index".

On the other hand, v1.7.x still use "create" action..
https://github.com/fluent/fluent-bit/blob/v1.7.7/plugins/out_es/es_bulk.h#L28

**Comment by fujimotos** [comment] 2021-06-01 09:07
> I think it is fixed by #2026.
> Current master supports "create" action, not "index".

@agup006 @nokute78 FWIW, I can attest this @nokute78's comment.

It's currently planned to be included in v1.8 (I merged the PR into master a while ago,
but did not orted to `1.7` branch), but porting that feature to v1.7 would be not much difficult
if it's worth backporting.

**Comment by moleksyuk** [comment] 2021-07-02 08:46
up

**Comment by fujimotos** [comment] 2021-07-30 00:56
This issue should be fixed by now, considering v1.8 has been released.

Reopen this issue if you can reproduce the same issue in newer releases.

**Closed by fujimotos** 2021-07-30 00:56 UTC

**Comment by superpraiya** [comment] 2022-08-18 13:01
Hi, 

any update for this issue?  can we use a data stream in es output in the latest release?

**Comment by dko-slapdash** [comment] 2023-02-03 06:45
@PettitWesley @edsiper @ChezBunch I think there is still a bug in the code, here: https://github.com/fluent/fluent-bit/blob/master/plugins/out_opensearch/opensearch.c#L838

<img width="963" alt="CleanShot 2023-02-02 at 22 43 03@2x" src="https://user-images.githubusercontent.com/46383452/216530480-010aaafa-acf4-4822-8379-d5e3716496c7.png">

It only ignores status 409, although it should also ignore status 201 (the case when some docs are actually created, and some produced conflicts).

Here is an example of ES response:

![CleanShot 2023-02-02 at 22 38 45@2x](https://user-images.githubusercontent.com/46383452/216530642-63574651-6690-458b-a944-27e734e9ae4b.png)

The thing is that it's impossible to set write_operation=upsert for datastream usecase - ES complains that only `create` mode is allowed in such a case - "only write ops with an op_type of create are allowed in data streams".

**Comment by PettitWesley** [comment] 2023-02-03 19:32
@dko-slapdash If you want this to get prioritized, please open a new issue with clear description and details and version info and config to reproduce it and tag user `nokute78`, IIRC he is the main maintainer of the elasticsearch plugin

**Comment by alita-moore** [comment] 2025-03-18 06:47
please support data streams

**Comment by alita-moore** [comment] 2025-03-18 06:54
nevermind, mine was not working because I had `Write_Operation upsert` instead of `Write_Operation create`
