### ISSUE TITLE
Stackdriver stops working after one hour: Oauth2

### ISSUE THREAD

**Issue by ThommyH** [fluent/fluent-bit#3267] opened 2021-03-22 14:12 UTC
## Bug Report

**Describe the bug**
We use gke@1.16.15-gke.7800 and fluentbit v1.7.2. The configured google service account has the following roles:
- Service Account Token Creator
- Logs Bucket Writer
- Logs Configuration Writer
- Logs Writer
- Monitoring Metric Writer

The configuration works fine and logs are forwarded to stackdriver. But after exactly one hour of log forwarding, the stackdriver plugin fails to push new logs:

**To Reproduce**
```
[2021/03/22 14:33:08] [debug] [output:stackdriver:stackdriver.0] JWT signature:
ey........
[2021/03/22 14:33:08] [debug] [http_client] not using http_proxy for header
[2021/03/22 14:33:08] [debug] [http_client] header=POST /oauth2/v4/token HTTP/1.1
Host: www.googleapis.com
Content-Length: 169553
Content-Type: application/x-www-form-urlencoded


[2021/03/22 14:33:08] [ info] [oauth2] HTTP Status=400
[2021/03/22 14:33:08] [ info] [oauth2] payload:
{
  "error": "unsupported_grant_type",
  "error_description": "Invalid grant_type: "
}
[2021/03/22 14:33:08] [error] [output:stackdriver:stackdriver.0] error retrieving oauth2 access token
[2021/03/22 14:33:08] [error] [output:stackdriver:stackdriver.0] cannot retrieve oauth2 token
```
- Steps to reproduce the problem:
1. service account created with mentioned roles
2. fluent-bit version 1.7.2
3. Cluster had been created with managed fluentbit logging, however
4. scaled down google managed fluentbit. To not interfere with our fluentbit testing.
5. Create daemonset and check Stackdriver logs
6. after 1 hour we get mentioned OAuth2 errors.
7. restart of the pods helps and logs are getting forwarded for another hour until the error returns.

**Expected behavior**
Fluentbit should refresh oauth token correctly and not fail after one hour.

**Your Environment**

* Version used: 1.7.2
* Configuration: see below
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.16.15-gke.7800
* Operating System and version: https://fluent.github.io/helm-charts 0.12.3 with image fluent/fluent-bit 1.7.2
* Filters and plugins: see config

```
config:
      service: |
        [SERVICE]
            Flush         5
            Grace         120
            Log_Level     trace
            Daemon        off
            Parsers_File  custom_parsers.conf
            HTTP_Server   On
            HTTP_Listen   0.0.0.0
            HTTP_PORT     2020
    
      inputs: |
        [INPUT]
            Name             tail
            Alias            kube_containers_kube-system
            Tag              kube.<namespace_name>.<pod_name>.<container_name>
            Tag_Regex        (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
            Path             /var/log/containers/*_kube-system_*.log
            DB               /var/run/google-fluentbit/pos-files/flb_kube_kube-system.db
            Buffer_Max_Size  1MB
            Mem_Buf_Limit    5MB
            Skip_Long_Lines  On
            Refresh_Interval 5
            Read_from_Head   True


        [INPUT]
            Name             tail
            Alias            kube_containers_gke-system
            Tag              kube.<namespace_name>.<pod_name>.<container_name>
            Tag_Regex        (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
            Path             /var/log/containers/*_gke-system_*.log
            DB               /var/run/google-fluentbit/pos-files/flb_kube_gke-system.db
            Buffer_Max_Size  1MB
            Mem_Buf_Limit    5MB
            Skip_Long_Lines  On
            Refresh_Interval 5
            Read_from_Head   True

        [INPUT]
            Name             tail
            Alias            kube_containers
            Tag              kube.<namespace_name>.<pod_name>.<container_name>
            Tag_Regex        (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
            Path             /var/log/containers/*.log
            Exclude_Path     /var/log/containers/*_kube-system_*.log,/var/log/containers/*_istio-system_*.log,/var/log/containers/*_knative-serving_*.log,/var/log/containers/*_gke-system_*.log,/var/log/containers/*_config-management-system_*.log
            DB               /var/run/google-fluentbit/pos-files/flb_kube.db
            Buffer_Max_Size  1MB
            Mem_Buf_Limit    5MB
            Skip_Long_Lines  On
            Refresh_Interval 5
            Read_from_Head   True

        # Example:
        # Dec 21 23:17:22 gke-foo-1-1-4b5cbd14-node-4eoj startupscript: Finished running startup script /var/run/google.startup.script
        [INPUT]
            Name             tail
            Parser           syslog
            Path             /var/log/startupscript.log
            DB               /var/run/google-fluentbit/pos-files/startupscript.db
            Alias            startupscript
            Tag              startupscript
            Read_from_Head   True

        # Logs from anetd for policy action
        [INPUT]
            Name             tail
            Parser           network-log
            Alias            policy-action
            Tag              policy-action
            Path             /var/log/network/policy_action.log
            DB               /var/run/google-fluentbit/pos-files/policy-action.db
            Skip_Long_Lines  On
            Refresh_Interval 5
            Read_from_Head   True

        # Example:
        # I1118 21:26:53.975789       6 proxier.go:1096] Port "nodePort for kube-system/default-http-backend:http" (:31429/tcp) was open before and is still needed
        [INPUT]
            Name            tail
            Alias           kube-proxy
            Tag             kube-proxy
            Path            /var/log/kube-proxy.log
            DB              /var/run/google-fluentbit/pos-files/kube-proxy.db
            Buffer_Max_Size 1MB
            Mem_Buf_Limit   1MB
            Parser          glog
            Read_from_Head  True

        # Logs from systemd-journal for interesting services.
        [INPUT]
            Name            systemd
            Alias           docker
            Tag             docker
            Systemd_Filter  _SYSTEMD_UNIT=docker.service
            Path            /var/log/journal
            DB              /var/run/google-fluentbit/pos-files/docker.db
            Buffer_Max_Size 1MB
            Mem_Buf_Limit   1MB

        [INPUT]
            Name            systemd
            Alias           container-runtime
            Tag             container-runtime
            Systemd_Filter  _SYSTEMD_UNIT=containerd.service
            Path            /var/log/journal
            DB              /var/run/google-fluentbit/pos-files/container-runtime.db
            Buffer_Max_Size 1MB
            Mem_Buf_Limit   1MB

        [INPUT]
            Name            systemd
            Alias           kubelet
            Tag             kubelet
            Systemd_Filter  _SYSTEMD_UNIT=kubelet.service
            Path            /var/log/journal
            DB              /var/run/google-fluentbit/pos-files/kubelet.db
            Buffer_Max_Size 1MB
            Mem_Buf_Limit   1MB

        # kube-node-installation, kube-node-configuration, and kube-logrotate are
        # oneshots, but it's extremely valuable to have their logs on Stackdriver
        # as they can diagnose critical issues with node startup.
        [INPUT]
            Name            systemd
            Alias           kube-node-installation
            Tag             kube-node-installation
            Systemd_Filter  _SYSTEMD_UNIT=kube-node-installation.service
            Path            /var/log/journal
            DB              /var/run/google-fluentbit/pos-files/kube-node-installation.db
            Buffer_Max_Size 1MB
            Mem_Buf_Limit   1MB

        [INPUT]
            Name            systemd
            Alias           kube-node-configuration
            Tag             kube-node-configuration
            Systemd_Filter  _SYSTEMD_UNIT=kube-node-configuration.service
            Path            /var/log/journal
            DB              /var/run/google-fluentbit/pos-files/kube-node-configuration.db
            Buffer_Max_Size 1MB
            Mem_Buf_Limit   1MB

        [INPUT]
            Name            systemd
            Alias           kube-logrotate
            Tag             kube-logrotate
            Systemd_Filter  _SYSTEMD_UNIT=kube-logrotate.service
            Path            /var/log/journal
            DB              /var/run/google-fluentbit/pos-files/kube-logrotate.db
            Buffer_Max_Size 1MB
            Mem_Buf_Limit   1MB

        [INPUT]
            Name            systemd
            Alias           node-problem-detector
            Tag             node-problem-detector
            Systemd_Filter  _SYSTEMD_UNIT=node-problem-detector.service
            Path            /var/log/journal
            DB              /var/run/google-fluentbit/pos-files/node-problem-detector.db
            Buffer_Max_Size 1MB
            Mem_Buf_Limit   1MB

        [INPUT]
            Name            systemd
            Alias           kube-container-runtime-monitor
            Tag             kube-container-runtime-monitor
            Systemd_Filter  _SYSTEMD_UNIT=kube-container-runtime-monitor.service
            Path            /var/log/journal
            DB              /var/run/google-fluentbit/pos-files/kube-container-runtime-monitor.db
            Buffer_Max_Size 1MB
            Mem_Buf_Limit   1MB

        [INPUT]
            Name            systemd
            Alias           kubelet-monitor
            Tag             kubelet-monitor
            Systemd_Filter  _SYSTEMD_UNIT=kubelet-monitor.service
            Path            /var/log/journal
            DB              /var/run/google-fluentbit/pos-files/kubelet-monitor.db
            Buffer_Max_Size 1MB
            Mem_Buf_Limit   1MB

        [INPUT]
            Name            systemd
            Alias           gcfsd
            Tag             gcfsd
            Systemd_Filter  _SYSTEMD_UNIT=gcfsd.service
            Path            /var/log/journal
            DB              /var/run/google-fluentbit/pos-files/gcfsd.db
            Buffer_Max_Size 1MB
            Mem_Buf_Limit   1MB

        [INPUT]
            Name            systemd
            Alias           gcfs-snapshotter
            Tag             gcfs-snapshotter
            Systemd_Filter  _SYSTEMD_UNIT=gcfs-snapshotter.service
            Path            /var/log/journal
            DB              /var/run/google-fluentbit/pos-files/gcfs-snapshotter.db
            Buffer_Max_Size 1MB
            Mem_Buf_Limit   1MB
    
      filters: |
        [FILTER]
            Name         parser
            Match        kube.*
            Key_Name     log
            Reserve_Data True
            Parser       docker
            Parser       containerd

        [FILTER]
            Name        modify
            Match       *
            Hard_rename log message

        [FILTER]
            Name         parser
            Match        kube.*
            Key_Name     message
            Reserve_Data True
            Parser       glog
            Parser       json
            Parser       logfmt

        [FILTER]
            Name    modify
            Match   *
            Copy    level severity

        [FILTER]
            Name                kubernetes
            Match               kube.*
            Kube_Tag_Prefix     kube.
            Regex_Parser        pod-tag-parser
            Kube_URL            https://kubernetes.default.svc:443
            Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
            Merge_Log           On
            K8S-Logging.Parser  On
            K8S-Logging.Exclude On

      outputs: |
        [OUTPUT]
            Name                  stackdriver
            Match                 kube.*
            Resource              k8s_container
            k8s_cluster_name      sre-playground-cluster
            k8s_cluster_location  europe-west4
            tag_prefix            kube.
            severity_key          severity

        [OUTPUT]
            Name                  stackdriver
            Match_Regex           ^(?!kube).*
            Resource              global
            k8s_cluster_name      sre-playground-cluster
            k8s_cluster_location  europe-west4
            
      customParsers: |
        [PARSER]
            Name        docker
            Format      json
            Time_Key    time
            Time_Format %Y-%m-%dT%H:%M:%S.%L%z

        [PARSER]
            Name        containerd
            Format      regex
            Regex       ^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$
            Time_Key    time
            Time_Format %Y-%m-%dT%H:%M:%S.%L%z

        [PARSER]
            Name        json
            Format      json

        [PARSER]
            Name        logfmt
            Format      logfmt        

        [PARSER]
            Name        syslog
            Format      regex
            Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
            Time_Key    time
            Time_Format %b %d %H:%M:%S

        [PARSER]
            Name        glog
            Format      regex
            Regex       ^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source_file>[^ \]]+)\:(?<source_line>\d+)\]\s(?<message>.*)$
            Time_Key    time
            Time_Format %m%d %H:%M:%S.%L

        [PARSER]
            Name        network-log
            Format      json
            Time_Key    timestamp
            Time_Format %Y-%m-%dT%H:%M:%S.%L%z

        [PARSER]
            Name    pod-tag-parser
            Format  regex
            Regex   (?<namespace_name>[^\.]+)\.(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)\.(?<container_name>.+)(?<docker_id>)
    
```
Of course, service account is mounted to the pods:
```
env:
    - name: GOOGLE_SERVICE_CREDENTIALS
      value: "/secret/fluentbit/stackdriver/service-account.json"
```

**Comment by sharkymcdongles** [comment] 2021-03-23 23:53
I did some more digging on this and found if I curl the endpoint for token generation directly via a pod using the same serviceaccount as fluent-bit this is the result:

```
curl -H "Metadata-Flavor:Google"  http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fmonitoring%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fmonitoring.read%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fmonitoring.write
{"access_token":"CENSORED","expires_in":3315,"token_type":"Bearer"}
```

My guess is the method to refresh the token either omits the scopes which gives same 400 error or something else, but it's not functioning properly as of now sadly, unless I am missing something.

**Comment by agup006** [comment] 2021-03-24 01:30
@hsmatulisgoogle @qingling128 I'm wondering if this is something you might be familiar with

**Comment by qingling128** [comment] 2021-03-24 03:09
Hi, this looks like an `oauth` issue. We are not very familiar with that, but there are a few `oauth` issues similar to this:

```
https://github.com/googleapis/gaxios/issues/267
https://github.com/googleapis/nodejs-storage/issues/1128
https://github.com/googleapis/google-api-nodejs-client/issues/2003
https://github.com/googleapis/google-api-ruby-client/issues/862
```

BTW, does your environment have VPC SC set up?

**Comment by qingling128** [comment] 2021-03-24 03:12
We also have an internal report for this issue. Quoting notes from Igor:

```
The plugin still uses the old OAuth2 URL (https://www.googleapis.com/oauth2/v4/token) instead of the new one (https://oauth2.googleapis.com/token). Don't know if it's related, but probably worth fixing in any case.
```

https://github.com/fluent/fluent-bit/blob/b38ddae8974b8553789c45ba14f9c3fd36a210f6/plugins/out_stackdriver/stackdriver.h#L37

**Comment by sharkymcdongles** [comment] 2021-03-24 06:07
> Hi, this looks like an `oauth` issue. We are not very familiar with that, but there are a few `oauth` issues similar to this:
> 
> ```
> https://github.com/googleapis/gaxios/issues/267
> https://github.com/googleapis/nodejs-storage/issues/1128
> https://github.com/googleapis/google-api-nodejs-client/issues/2003
> https://github.com/googleapis/google-api-ruby-client/issues/862
> ```
> 
> BTW, does your environment have VPC SC set up?

@qingling128 
No we don't use VPC SC. I have workload identity enabled but stackdriver output doesn't support it so we are using the service account via a secret per the documentation. Having workload identity enabled hasn't affected any of our other service account mounter workloads either like external-dns or cert-manager via Google DNS.

Is the URL you linked used for the initial auth or only the refresh? If it is used only for token refresh this makes perfect sense. Thanks for taking a look!

**Comment by sharkymcdongles** [comment] 2021-03-25 10:21
@qingling128 I built a test version using the new URL, but now it never gets a token.

I just changed this as you suggested and built a fresh version:

```
 /* Stackdriver authorization URL */
-#define FLB_STD_AUTH_URL  "https://www.googleapis.com/oauth2/v4/token"
+#define FLB_STD_AUTH_URL  "https://oauth2.googleapis.com/token"
```

Now it never gets a token at all. :(

```
[2021/03/25 10:14:31] [ info] [filter:kubernetes:kubernetes.4] testing connectivity with API server...
[2021/03/25 10:14:31] [ info] [filter:kubernetes:kubernetes.4] connectivity OK
[2021/03/25 10:14:31] [ info] [output:stackdriver:stackdriver.0] metadata_server set to http://metadata.google.internal
[2021/03/25 10:14:31] [error] [oauth2] could not get an upstream connection to oauth2.googleapis.com:443
[2021/03/25 10:14:31] [error] [output:stackdriver:stackdriver.0] error retrieving oauth2 access token
[2021/03/25 10:14:31] [ warn] [output:stackdriver:stackdriver.0] token retrieval failed
[2021/03/25 10:14:31] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
```

I will try to test and see if I can figure out the issue, but so far no luck sadly. :(

**Comment by sharkymcdongles** [comment] 2021-03-25 15:05
```
[2021/03/25 15:02:41] [trace] [upstream] get new connection for www.googleapis.com:443, net setup:
net.connect_timeout        = 10 seconds
net.source_address         = any
net.keepalive              = enabled
net.keepalive_idle_timeout = 30 seconds
[2021/03/25 15:02:41] [trace] [net] connection #311 in process to www.googleapis.com:443
[2021/03/25 15:02:41] [trace] [tls] connection and handshake OK
[2021/03/25 15:02:41] [trace] [io] connection OK
[2021/03/25 15:02:41] [debug] [http_client] not using http_proxy for header
[2021/03/25 15:02:41] [debug] [http_client] header=POST /oauth2/v4/token HTTP/1.1
Host: www.googleapis.com
Content-Length: 65325
Content-Type: application/x-www-form-urlencoded
[2021/03/25 15:02:41] [trace] [io coro=0x7fbf3cf8d2b8] [net_write] trying 132 bytes
[2021/03/25 15:02:41] [trace] [io coro=0x7fbf3cf8d2b8] [net_write] ret=0 total=132/132
[2021/03/25 15:02:41] [trace] [io coro=0x7fbf3cf8d2b8] [net_write] trying 65325 bytes
[2021/03/25 15:02:41] [trace] [io coro=0x7fbf3cf8d2b8] [net_write] ret=0 total=65325/65325
[2021/03/25 15:02:41] [trace] [io coro=0x7fbf3cf8d2b8] [net_read] try up to 4095 bytes
[2021/03/25 15:02:41] [trace] [io coro=0x7fbf3cf8d2b8] [net_read] ret=457
[2021/03/25 15:02:41] [trace] [io coro=0x7fbf3cf8d2b8] [net_read] try up to 3644 bytes
[2021/03/25 15:02:41] [trace] [io coro=0x7fbf3cf8d2b8] [net_read] ret=5
[2021/03/25 15:02:41] [ info] [oauth2] HTTP Status=400
[2021/03/25 15:02:41] [ info] [oauth2] payload:
{
  "error": "unsupported_grant_type",
  "error_description": "Invalid grant_type: "
}
[2021/03/25 15:02:41] [error] [output:stackdriver:stackdriver.0] error retrieving oauth2 access token
[2021/03/25 15:02:41] [error] [output:stackdriver:stackdriver.0] cannot retrieve oauth2 token
[2021/03/25 15:02:41] [trace] [upstream] destroy connection #312 to logging.googleapis.com:443
[2021/03/25 15:02:41] [trace] [engine] resuming coroutine=0x7fbf3cf8d2d0
[2021/03/25 15:02:41] [trace] [tls] connection and handshake OK
[2021/03/25 15:02:41] [trace] [io] connection OK
[2021/03/25 15:02:41] [debug] [output:stackdriver:stackdriver.0] local_resource_id not found, tag [kube.imagepullsecret-patcher.imagepullsecret-patcher-7f676564bf-7hm74.imagepullsecret-patcher] is assigned for local_resource_id
[2021/03/25 15:02:41] [debug] [output:stackdriver:stackdriver.0] [logging.googleapis.com/monitored_resource] not found in the payload
[2021/03/25 15:02:41] [debug] [output:stackdriver:stackdriver.0] JWT signature: CENSORED
```

**Comment by sharkymcdongles** [comment] 2021-03-25 16:05
Did even more digging. When you generate the credentials json the URLs are set thusly:

  "client_email": "fluent-bit@mls-sre-playground.iam.gserviceaccount.com",
  "client_id": "116459872538781414060",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",

I suspect it uses the secret for the initial auth then uses the token uri from the json for the refresh.

**Comment by sharkymcdongles** [comment] 2021-03-26 04:12
Did more digging and it seems the error is here:

```
ret = flb_oauth2_payload_append(ctx->o,
                                    "grant_type", -1,
                                    "urn:ietf:params:oauth:"
                                    "grant-type:jwt-bearer", -1);
```

The grant_type needs to be refresh_token I believe to work.

**Comment by sharkymcdongles** [comment] 2021-03-26 07:10
Okay further testing it seems issue is the content-type header isn't sent on the token refresh, so the grant_type from the client isn't read by the server.

**Comment by sharkymcdongles** [comment] 2021-03-26 08:24
Okay added some logging now to `src/flb_oauth2.c`

I see the initial request is correct and gets the token:
```
[2021/03/26 08:18:23] [ warn] [oauth2] request payload:
grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer&assertion=TOKEN
```

However the refresh request has an empty payload from the look of it:
```
[2021/03/26 08:18:23] [ warn] [oauth2] request payload:

```

Seems an easy fix if I can figure out why the refresh request has an empty payload.

**Comment by sharkymcdongles** [comment] 2021-03-26 09:46
So I am fairly certain this commit is the culprit and why this is no longer working properly:

https://github.com/fluent/fluent-bit/pull/2977/files

I noticed the method to clear the payload was introduced from this commit, so I downgraded to the version before this commit, and it works properly now.

@hsmatulisgoogle can you pretty please review this and see if you can suss out why this is breaking the token refresh? I am not well versed in C, so this is beyond me. I learned a lot debugging this though at least. 👯‍♂️

**Comment by hsmatulisgoogle** [comment] 2021-03-26 13:49
Thanks for the investigation! I think the issue is the following:
https://github.com/fluent/fluent-bit/blob/491889b5601f7b353df31a46e0b867ee5464b376/src/flb_oauth2.c#L245
Since payload is an sds_t string it has a header which didn't get updated containing the string length, meaning after the clearing the first byte strings are appended to the end of the buffer rather than the start. It looks like we can fix this by calling `flb_sds_len_set(ctx->payload, 0)`. I added the draft pr https://github.com/fluent/fluent-bit/pull/3291 to attempt to fix this, but have not tested it yet

**Comment by sharkymcdongles** [comment] 2021-03-26 13:54
> Thanks for the investigation! I think the issue is the following:
> https://github.com/fluent/fluent-bit/blob/491889b5601f7b353df31a46e0b867ee5464b376/src/flb_oauth2.c#L245
> 
> 
> Since payload is an sds_t string it has a header which didn't get updated containing the string length, meaning after the clearing the first byte strings are appended to the end of the buffer rather than the start. It looks like we can fix this by calling `flb_sds_len_set(ctx->payload, 0)`. I added the draft pr #3291 to attempt to fix this, but have not tested it yet

I have a build env from my testing. I will build and report back shortly. Thanks for the quick fix @hsmatulisgoogle

**Comment by sharkymcdongles** [comment] 2021-03-26 14:10
> Thanks for the investigation! I think the issue is the following:
> https://github.com/fluent/fluent-bit/blob/491889b5601f7b353df31a46e0b867ee5464b376/src/flb_oauth2.c#L245
> 
> 
> Since payload is an sds_t string it has a header which didn't get updated containing the string length, meaning after the clearing the first byte strings are appended to the end of the buffer rather than the start. It looks like we can fix this by calling `flb_sds_len_set(ctx->payload, 0)`. I added the draft pr #3291 to attempt to fix this, but have not tested it yet

@hsmatulisgoogle 
So I edited the refresh to run in 30 seconds to speed up the testing, and great news! This 1 line fixed the issue completely! I think this issue can be marked solved and hopefully added to a quick 1.7.3 release.  One enhancement I'd suggest is to add the entire payload request sent to the API server to either trace or debug output for easier debugging of such issues in the future. I hacked it in, but if it has been there earlier I probably would've solved it quicker, but at least it taught me a bit about how to use C. 😄

**Comment by edsiper** [comment] 2021-03-26 15:54
FYI: PR looks good, @hsmatulisgoogle as soon the PR is set as non-draft we are good to go.

**Comment by hsmatulisgoogle** [comment] 2021-03-26 20:24
I set it as non-draft, should be good to go then!

**Comment by edsiper** [comment] 2021-03-26 20:52
merged, thanks!

FYI: the fix will be part of v1.7.3

**Closed by edsiper** 2021-03-26 20:52 UTC

**Comment by sharkymcdongles** [comment] 2021-03-27 00:45
We may need to reopen this or make a new ticket @edsiper @hsmatulisgoogle. In the image I built including only the fix that was created in the PR, it works fine for about an hour then the token starts refreshing, but it just keeps refreshing every second in an endless loop.

```
[2021/03/27 00:42:57] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:57] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/27 00:42:57] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:57] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/27 00:42:57] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:57] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/27 00:42:57] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:57] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/27 00:42:57] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:57] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/27 00:42:57] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:57] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/27 00:42:57] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:57] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/27 00:42:57] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:57] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/27 00:42:57] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:57] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/27 00:42:57] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:57] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/27 00:42:57] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:57] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/27 00:42:57] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:57] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/27 00:42:57] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:57] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/27 00:42:57] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:57] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/27 00:42:57] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:57] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/27 00:42:57] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:57] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/27 00:42:57] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:57] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/27 00:42:57] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:57] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/27 00:42:58] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:58] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/27 00:42:58] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:58] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/27 00:42:58] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:58] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/27 00:42:58] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:58] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/27 00:42:58] [ info] [oauth2] HTTP Status=200
[2021/03/27 00:42:58] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
```

I rebuilt it from scratch and changed only the line above that is in the PR when I tested to ensure none of my testing edits were included. Not sure why this is, and I haven't had time to dive in to see if I can figure it out.

**Comment by sharkymcdongles** [comment] 2021-03-27 09:33
I think problem is this method:

```
int flb_oauth2_token_expired(struct flb_oauth2 *ctx)
{
    time_t now;

    if (!ctx->access_token) {
        return FLB_TRUE;
    }

    now = time(NULL);
    if (ctx->expires <= now) {
        return FLB_TRUE;
    }

    return FLB_FALSE;
}
```

I think when the token is cleared this returns FLB_TRUE. Maybe if we remove this it will solve the issue:

```
    if (!ctx->access_token) {
        return FLB_TRUE;
    }
```

**Comment by igorpeshansky** [comment] 2021-04-16 22:29
[This code](https://github.com/fluent/fluent-bit/blob/master/src/flb_oauth2.c#L332) looks a bit suspect — shouldn't we check that the token is _not_ expired? Sent #3373.

**Comment by igorpeshansky** [comment] 2021-07-16 00:24
#3373 has been merged. @sharkymcdongles, can you please confirm that you're no longer seeing this issue?
