### ISSUE TITLE
The amazonlinux 2023 repository does not contain aarch64 packages

### ISSUE THREAD

**Issue by dschaaff** [fluent/fluent-bit#7324] opened 2023-05-04 23:13 UTC
## Bug Report

**Describe the bug**
The amazonlinux 2023 repository does not contain aarch64 packages, only x86_64 packages. This blocks the ability to install on graviton instances in AWS environments.

**To Reproduce**

Navigate to https://packages.fluentbit.io/amazonlinux/2023/

**Expected behavior**
arm builds should provide for amazon linux 2023 just as they are for other platforms.

**Comment by patrick-stephens** [comment] 2023-05-05 09:58
This is a duplicate of 6978 and 6300, the gist is the ARM 64 builds do not complete on GIthub Runners.
The builds used to work until sometime late last year when a change in the base image seems to have triggered very long running builds then that hit the timeouts. 

We're looking to improve this with some Actuated.dev support to spin up hosted runners: self-hosting runners is not recommended for public repos like this so it is a bit of a pickle I'm afraid.

**Closed** 2023-05-05 09:59 UTC
