### ISSUE TITLE
Centos installing failed - parsing err

### ISSUE THREAD

**Issue by wintrov** [fluent/fluent-bit#5463] opened 2022-05-16 14:11 UTC
## Bug Report

When trying to install the fiuent bit got an err on centos 7

![Screen Shot 2022-05-16 at 17 11 28](https://user-images.githubusercontent.com/96373162/168612339-70e8723c-6a48-409b-a6c1-795fd99363c3.png)

**Comment by patrick-stephens** [comment] 2022-05-16 20:18
Duplicate of #5459 so should be resolved now.

**Closed** 2022-05-16 20:18 UTC
Labels: status: waiting-for-triage
