### ISSUE TITLE
record_modifier plugin doesn't exist

### ISSUE THREAD

**Issue by martinlauer** [fluent/fluent-bit#9072] opened 2024-07-10 16:17 UTC
## Bug Report

**Describe the bug**
When starting fluent-bit 3.1 using the `record_modifier` filter plugin, the application fails with an error.

**To Reproduce**
```
$> /opt/fluent-bit/bin/fluent-bit -F record_modifier

Fluent Bit v3.1.0
* Copyright (C) 2015-2024 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

______ _                  _    ______ _ _           _____  __
|  ___| |                | |   | ___ (_) |         |____ |/  |
| |_  | |_   _  ___ _ __ | |_  | |_/ /_| |_  __   __   / /`| |
|  _| | | | | |/ _ \ '_ \| __| | ___ \ | __| \ \ / /   \ \ | |
| |   | | |_| |  __/ | | | |_  | |_/ / | |_   \ V /.___/ /_| |_
\_|   |_|\__,_|\___|_| |_|\__| \____/|_|\__|   \_/ \____(_)___/

[2024/07/10 16:02:22] [error] [config] section 'record_modifier' tried to instance a plugin name that doesn't exist
[2024/07/10 16:02:22] [error] configuration file contains errors, aborting.
```

The `/lib/fluent-bit/libfluent-bit.so` doesn't contain the `filter_record_modifier_plugin` symbol.
```
$ nm /lib/fluent-bit/libfluent-bit.so|grep filter_.*_plugin$
00000000008bb110 D filter_alter_size_plugin
00000000008bb280 D filter_aws_plugin
00000000008bb810 D filter_checklist_plugin
00000000008bbb00 D filter_ecs_plugin
00000000008be290 D filter_expect_plugin
00000000008bf300 D filter_geoip2_plugin
00000000008be5e0 D filter_grep_plugin
00000000008bc540 D filter_kubernetes_plugin
00000000008bea30 D filter_log_to_metrics_plugin
00000000008bef00 D filter_lua_plugin
00000000008bd3d0 D filter_modify_plugin
00000000008bd900 D filter_multiline_plugin
00000000008bdd10 D filter_nest_plugin
00000000008bf4d0 D filter_nightfall_plugin
00000000008be000 D filter_parser_plugin
00000000008be7b0 D filter_rewrite_tag_plugin
00000000008bf2b0 D filter_stdout_plugin
00000000008bbe50 D filter_sysinfo_plugin
00000000008bc0e0 D filter_throttle_plugin
00000000008bc310 D filter_type_converter_plugin
00000000008bf820 D filter_wasm_plugin
```

**Expected behavior**
Fluent-bit shall be able to load the `record_modifier` plugin.

```
$> /opt/fluent-bit/bin/fluent-bit -F record_modifier

Fluent Bit v2.1.10
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2024/07/10 16:14:11] [ info] [fluent bit] version=2.1.10, commit=, pid=653131
[2024/07/10 16:14:11] [ info] [storage] ver=1.5.1, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2024/07/10 16:14:11] [ info] [cmetrics] version=0.6.3
[2024/07/10 16:14:11] [ info] [ctraces ] version=0.3.1
[2024/07/10 16:14:11] [ warn] [filter] NO match rule for record_modifier.0 filter instance, unloading.
[2024/07/10 16:14:11] [error] [engine] filter initialization failed
[2024/07/10 16:14:11] [error] [lib] backend failed
```

The `filter_record_modifier_plugin` symbol should be present in the lib.
```
$ nm /lib/fluent-bit/libfluent-bit.so|grep filter_.*_plugin$
00000000011aa430 D filter_alter_size_plugin
00000000011aa958 D filter_aws_plugin
00000000011aac40 D filter_checklist_plugin
00000000011aaf88 D filter_ecs_plugin
00000000011ad4f0 D filter_expect_plugin
00000000011ae3b0 D filter_geoip2_plugin
00000000011ad6b8 D filter_grep_plugin
00000000011ac308 D filter_kubernetes_plugin
00000000011addf8 D filter_log_to_metrics_plugin
00000000011ae1a0 D filter_lua_plugin
00000000011ac830 D filter_modify_plugin
00000000011acc38 D filter_multiline_plugin
00000000011acf20 D filter_nest_plugin
00000000011ae6f8 D filter_nightfall_plugin
00000000011ad1a8 D filter_parser_plugin
00000000011ab210 D filter_record_modifier_plugin
00000000011ad8e0 D filter_rewrite_tag_plugin
00000000011ae1e8 D filter_stdout_plugin
00000000011ab438 D filter_throttle_plugin
00000000011ab660 D filter_type_converter_plugin
00000000011ae8c0 D filter_wasm_plugin
```

**Screenshots**

**Your Environment**

* Version used: 3.1.0
* Configuration: default
* Server type and version: Raspberry PI arm64
* Operating System and version: Ubuntu 24.04 LTS
* Filters and plugins: record_modifier

**Comment by patrick-stephens** [comment] 2024-07-10 17:12
Resolved in 3.1.1 which is being released now, duplicate of #9069 and #9063

**Closed by patrick-stephens** 2024-07-10 17:12 UTC
Labels: status: waiting-for-triage
