### ISSUE TITLE
Fluent-Bit 2.0.9 caught signal (SIGSEGV)

### ISSUE THREAD

**Issue by auwaerter** [fluent/fluent-bit#7023] opened 2023-03-15 13:20 UTC
## Bug Report

**Describe the bug**
Started with docker-compose, fluent-bit keeps crashing with not clear message about why.

**To Reproduce**

```
fluent-bit      | Fluent Bit v2.0.9
fluent-bit      | * Copyright (C) 2015-2022 The Fluent Bit Authors
fluent-bit      | * Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
fluent-bit      | * https://fluentbit.io
fluent-bit      |
fluent-bit      | [2023/03/15 13:05:14] [ info] Configuration:
fluent-bit      | [2023/03/15 13:05:14] [ info]  flush time     | 25.000000 seconds
fluent-bit      | [2023/03/15 13:05:14] [ info]  grace          | 120 seconds
fluent-bit      | [2023/03/15 13:05:14] [ info]  daemon         | 0
fluent-bit      | [2023/03/15 13:05:14] [ info] ___________
fluent-bit      | [2023/03/15 13:05:14] [ info]  inputs:
fluent-bit      | [2023/03/15 13:05:14] [ info]      tail
fluent-bit      | [2023/03/15 13:05:14] [ info]      tail
fluent-bit      | [2023/03/15 13:05:14] [ info]      tail
fluent-bit      | [2023/03/15 13:05:14] [ info]      tail
fluent-bit      | [2023/03/15 13:05:14] [ info]      tail
fluent-bit      | [2023/03/15 13:05:14] [ info] ___________
fluent-bit      | [2023/03/15 13:05:14] [ info]  filters:
fluent-bit      | [2023/03/15 13:05:14] [ info]      parser.0
fluent-bit      | [2023/03/15 13:05:14] [ info]      grep.1
fluent-bit      | [2023/03/15 13:05:14] [ info] ___________
fluent-bit      | [2023/03/15 13:05:14] [ info]  outputs:
fluent-bit      | [2023/03/15 13:05:14] [ info]      http.0
fluent-bit      | [2023/03/15 13:05:14] [ info] ___________
fluent-bit      | [2023/03/15 13:05:14] [ info]  collectors:
fluent-bit      | [2023/03/15 13:05:14] [ info] [fluent bit] version=2.0.9, commit=4c0ca4fc5f, pid=1
fluent-bit      | [2023/03/15 13:05:14] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
fluent-bit      | [2023/03/15 13:05:14] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
fluent-bit      | [2023/03/15 13:05:14] [ info] [cmetrics] version=0.5.8
fluent-bit      | [2023/03/15 13:05:14] [ info] [ctraces ] version=0.2.7
fluent-bit      | [2023/03/15 13:05:14] [ info] [input:tail:tail.0] initializing
fluent-bit      | [2023/03/15 13:05:14] [ info] [input:tail:tail.0] storage_strategy='memory' (memory only)
fluent-bit      | [2023/03/15 13:05:14] [debug] [tail:tail.0] created event channels: read=21 write=22
fluent-bit      | [2023/03/15 13:05:14] [ info] [input:tail:tail.0] multiline core started
fluent-bit      | [2023/03/15 13:05:14] [debug] [input:tail:tail.0] flb_tail_fs_inotify_init() initializing inotify tail input
fluent-bit      | [2023/03/15 13:05:14] [debug] [input:tail:tail.0] inotify watch fd=28
fluent-bit      | [2023/03/15 13:05:14] [debug] [input:tail:tail.0] scanning path /logs/xca/app/schedule/schedule.*.log
fluent-bit      | [2023/03/15 12:56:33] [debug] [input:tail:tail.4] 0 new files found on path '/logs/xca/httpserver/error.log'
fluent-bit      | [2023/03/15 12:56:33] [debug] [regex:check_option]: unknown option. use default.
fluent-bit      | [2023/03/15 12:56:33] [debug] [http:http.0] created event channels: read=60 write=61
fluent-bit      | [2023/03/15 12:56:33] [debug] [router] match rule tail.0:http.0
fluent-bit      | [2023/03/15 12:56:33] [debug] [router] match rule tail.1:http.0
fluent-bit      | [2023/03/15 12:56:33] [debug] [router] match rule tail.2:http.0
fluent-bit      | [2023/03/15 12:56:33] [debug] [router] match rule tail.3:http.0
fluent-bit      | [2023/03/15 12:56:33] [debug] [router] match rule tail.4:http.0
fluent-bit      | [2023/03/15 12:56:33] [ info] [output:http:http.0] worker #0 started
fluent-bit      | [2023/03/15 12:56:33] [ info] [output:http:http.0] worker #1 started
fluent-bit      | [2023/03/15 12:56:33] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
fluent-bit      | [2023/03/15 12:56:33] [ info] [sp] stream processor started
fluent-bit      | [2023/03/15 12:56:33] [debug] [input:tail:tail.0] [static files] processed 0b, done
fluent-bit      | [2023/03/15 12:56:33] [debug] [input:tail:tail.1] [static files] processed 0b, done
fluent-bit      | [2023/03/15 12:56:33] [debug] [input:tail:tail.2] inode=297 file=/logs/xca/appserver/access.2023-03-15.log promote to TAIL_EVENT
fluent-bit      | [2023/03/15 12:56:33] [ info] [input:tail:tail.2] inotify_fs_add(): inode=297 watch_fd=1 name=/eswcm/logs/cma/appserver/access.2023-03-15.log
fluent-bit      | [2023/03/15 12:56:33] [debug] [input:tail:tail.2] [static files] processed 0b, done
fluent-bit      | [2023/03/15 12:56:33] [debug] [input:tail:tail.3] [static files] processed 0b, done
fluent-bit      | [2023/03/15 12:56:33] [debug] [input:tail:tail.4] inode=16 file=/logs/xca/httpserver/access.log promote to TAIL_EVENT
fluent-bit      | [2023/03/15 12:56:33] [ info] [input:tail:tail.4] inotify_fs_add(): inode=16 watch_fd=1 name=/logs/cma/httpserver/access.log
fluent-bit      | [2023/03/15 12:56:33] [debug] [input:tail:tail.4] [static files] processed 0b, done
fluent-bit      | [2023/03/15 12:56:34] [engine] caught signal (SIGSEGV)
fluent-bit      | #0  0x7fc023b65ad8      in  ???() at ???:0
fluent-bit      | #1  0x7fc023a5bf75      in  ???() at ???:0
fluent-bit      | #2  0x7fc023a6d9c5      in  ???() at ???:0
fluent-bit      | #3  0x560a790666f2      in  flb_sds_printf() at src/flb_sds.c:429
fluent-bit      | #4  0x560a7920e452      in  debug_event_mask() at plugins/in_tail/tail_fs_inotify.c:69
fluent-bit      | #5  0x560a7920e924      in  tail_fs_event() at plugins/in_tail/tail_fs_inotify.c:199
fluent-bit      | #6  0x560a79075d4a      in  flb_input_collector_fd() at src/flb_input.c:1882
fluent-bit      | #7  0x560a790a87aa      in  flb_engine_handle_event() at src/flb_engine.c:490
fluent-bit      | #8  0x560a790a87aa      in  flb_engine_start() at src/flb_engine.c:853
fluent-bit      | #9  0x560a7904fb24      in  flb_lib_worker() at src/flb_lib.c:629
fluent-bit      | #10 0x7fc02423bea6      in  ???() at ???:0
fluent-bit      | #11 0x7fc023aefa2e      in  ???() at ???:0
fluent-bit      | #12 0xffffffffffffffff  in  ???() at ???:0
fluent-bit exited with code 139
```
- Steps to reproduce the problem:

Started fluent-bit with:

```yaml
deploy:
  resources:
    limits:
      cpus: '0.5'
      memory: 75M
    reservations:
      memory: 30M
```

- docker stats never went over 45% of usage.
- Also, in one of my first attempts before i raised the memory where i got the exit code 139, i've received: 
- `fluent-bit exited with code 137`

**Expected behavior**
Fluent-bit being able to ship logs to data-prepper

**Your Environment**

* Version used: 2.0.9
* Configuration:
* Environment name and version: docker-compose 1.29.2
* Server type and version: Linux 5.3.18-150300.59.106-default
* Operating System and version: SLES 15
* Filters and plugins: parser & grep

**Configuration**

[fluent-bit.txt](https://github.com/fluent/fluent-bit/files/10980189/fluent-bit.txt)

**Comment by agup006** [comment] 2023-03-15 13:36
@auwaerter would you be able to past the configuration, also can you repro on non-SLES? We do not currently support SLES 12 / 15

**Comment by auwaerter** [comment] 2023-03-15 13:45
@agup006 i've put the configuration here inside a textfile -> https://github.com/fluent/fluent-bit/files/10980189/fluent-bit.txt

Weird part: I can not reproduce this issue on a similar machine with the exact same config also running on SLES 15, neither on my local dev with debian 10.

My docker-compose looks like:

```yaml
  fluent-bit:
    image: fluent/fluent-bit:2.0.9
    container_name: fluent-bit
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 150M
        reservations:
          memory: 75M
    depends_on:
      - data-prepper
    volumes:
      - logfiles:/logs/
      - ./config/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:rw
      - ./config/fluent-bit/parsers.conf:/fluent-bit/etc/custom-parsers.conf:rw
    networks:
      - net

volumes:
  logfiles:
    name: logfiles
    driver: local
    driver_opts:
      o: bind
      device: /home/opensearch/test-logfiles
      type: none

networks:
  net:
```

**Comment by agup006** [comment] 2023-03-15 13:48
Hmm I'm wondering if it's a specific parser or tail. If it's consistently repro-ing on the one SLES machine. Could we try removing 1 input at a time + filters + outputs and also add standard output?

**Comment by auwaerter** [comment] 2023-03-15 14:04
I've tried removing the first server.log tail as i expect this one to be the biggest. Afterwards the schedule. Then the access.*.log and then the catalina.*.log and lastly the both httpserver logs. With no success.

Without Inputs it is running ;-)

```
fluent-bit      | Fluent Bit v2.0.9
fluent-bit      | * Copyright (C) 2015-2022 The Fluent Bit Authors
fluent-bit      | * Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
fluent-bit      | * https://fluentbit.io
fluent-bit      |
fluent-bit      | [2023/03/15 13:55:57] [ info] Configuration:
fluent-bit      | [2023/03/15 13:55:57] [ info]  flush time     | 25.000000 seconds
fluent-bit      | [2023/03/15 13:55:57] [ info]  grace          | 120 seconds
fluent-bit      | [2023/03/15 13:55:57] [ info]  daemon         | 0
fluent-bit      | [2023/03/15 13:55:57] [ info] ___________
fluent-bit      | [2023/03/15 13:55:57] [ info]  inputs:
fluent-bit      | [2023/03/15 13:55:57] [ info] ___________
fluent-bit      | [2023/03/15 13:55:57] [ info]  filters:
fluent-bit      | [2023/03/15 13:55:57] [ info]      parser.0
fluent-bit      | [2023/03/15 13:55:57] [ info]      grep.1
fluent-bit      | [2023/03/15 13:55:57] [ info] ___________
fluent-bit      | [2023/03/15 13:55:57] [ info]  outputs:
fluent-bit      | [2023/03/15 13:55:57] [ info]      http.0
fluent-bit      | [2023/03/15 13:55:57] [ info] ___________
fluent-bit      | [2023/03/15 13:55:57] [ info]  collectors:
fluent-bit      | [2023/03/15 13:55:57] [ info] [fluent bit] version=2.0.9, commit=4c0ca4fc5f, pid=1
fluent-bit      | [2023/03/15 13:55:57] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
fluent-bit      | [2023/03/15 13:55:57] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
fluent-bit      | [2023/03/15 13:55:57] [ info] [cmetrics] version=0.5.8
fluent-bit      | [2023/03/15 13:55:57] [ info] [ctraces ] version=0.2.7
fluent-bit      | [2023/03/15 13:55:57] [debug] [regex:check_option]: unknown option. use default.
fluent-bit      | [2023/03/15 13:55:57] [debug] [http:http.0] created event channels: read=21 write=22
fluent-bit      | [2023/03/15 13:55:57] [ info] [output:http:http.0] worker #0 started
fluent-bit      | [2023/03/15 13:55:57] [ info] [output:http:http.0] worker #1 started
fluent-bit      | [2023/03/15 13:55:57] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
fluent-bit      | [2023/03/15 13:55:57] [ info] [sp] stream processor started

```

Afterwards i've deactived both filters, but also no success.

To only change the output to:
```
[OUTPUT]
    Name                  stdout
    Match                 *
    Format                msgpack
    Json_date_key         time
    Json_date_format      iso8601
```

brought no solution.

What worked was the following:

```bash
[SERVICE]
    Flush                 25
    Grace                 120
    Log_Level             debug
    Daemon                Off
    Parsers_File          /fluent-bit/etc/custom-parsers.conf
    HTTP_Server           On
    HTTP_Listen           0.0.0.0
    HTTP_Port             2020

[INPUT]
    Name                  tail
    Refresh_Interval      120
    Path                  /logs/xca/app/schedule/schedule.*.log
    Path_Key              logfile-origin
    Ignore_Older          1m
    multiline.parser      java
    Read_from_Head        false
    Skip_Long_Lines       Off
    Mem_Buf_Limit         25MB
    Tag                  app-server-schedule-log
[OUTPUT]
    Name                  stdout
    Match                 *
    Format                msgpack
    Json_date_key         time
    Json_date_format      iso8601
```

```
[...]
fluent-bit      | [2023/03/15 14:00:36] [debug] [input:tail:tail.0] excluded=/logs/xca/app/schedule/schedule.874.6918.log (ignore_older)
fluent-bit      | [2023/03/15 14:00:36] [debug] [input:tail:tail.0] 0 new files found on path '/logs/xca/app/schedule/schedule.*.log'
fluent-bit      | [2023/03/15 14:00:36] [debug] [stdout:stdout.0] created event channels: read=29 write=30
fluent-bit      | [2023/03/15 14:00:36] [ info] [output:stdout:stdout.0] worker #0 started
fluent-bit      | [2023/03/15 14:00:36] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
fluent-bit      | [2023/03/15 14:00:36] [ info] [sp] stream processor started
fluent-bit      | [2023/03/15 14:00:36] [debug] [input:tail:tail.0] [static files] processed 0b, done
```

**Comment by patrick-stephens** [comment] 2023-03-15 14:47
I think this might be another duplicate of your fixed issue @leonardo-albertovich ?

**Comment by patrick-stephens** [comment] 2023-03-15 14:48
See https://github.com/fluent/fluent-bit/issues/6958

**Comment by leonardo-albertovich** [comment] 2023-03-15 14:48
Yes, that's patched, all you have to do is raise the log level above debug for the moment in order to work around it.

**Comment by auwaerter** [comment] 2023-03-15 19:14
Great! Going back to _info_ fixed the exit code 139 and i'm getting a clearer message now:

```
fluent-bit      | [2023/03/15 19:03:39] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
fluent-bit      | [2023/03/15 19:03:39] [ info] [sp] stream processor started
fluent-bit      | [2023/03/15 19:03:43] [ warn] [input] tail.1 paused (mem buf overlimit)
fluent-bit      | [2023/03/15 19:03:43] [ info] [input] pausing tail.1
fluent-bit exited with code 137
````

So i've raised the memory and now it seems to be stable.

Thanks a lot for your support!

**Comment by patrick-stephens** [comment] 2023-03-22 14:03
2.0.10 is released now so should work with `debug` too.

**Closed by patrick-stephens** 2023-03-22 14:03 UTC
Labels: duplicate, waiting-for-release
