### ISSUE TITLE
Allow Elasticsearch Output Plugin to be able to dynamically add Kubernetes container_name to Logstash_Prefix

### ISSUE THREAD

**Issue by samirspatel** [fluent/fluent-bit#1775] opened 2019-11-26 01:50 UTC
**Is your feature request related to a problem? Please describe.**

Elasticsearch is throwing errors because different apps are reporting the same field name with a different datatype. All apps are sending data to the same Elasticsearch index as indicated by the `Logstash_Prefix` configuration option for the `es` output plugin

The `es` output stanza is as follows
```
  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Logstash_Prefix kubeapps
        Time_Key        @timestamp
        Generate_ID     On
        Include_Tag_Key On
        Replace_Dots    On
        Retry_Limit     False
        Buffer_Size     False
        HTTP_User       ${FLUENT_ELASTICSEARCH_USER}
        HTTP_Passwd     ${FLUENT_ELASTICSEARCH_PASS}
        tls             On
        tls.verify      Off
```

**Describe the solution you'd like**

I would like to be able to  change this `Logstash_Prefix kubeapps` to this `Logstash_Prefix kube-<container_name>` so each application in kubernetes has it's own `Logstash_Prefix` and hence it's own index in Elasticsearch

**Describe alternatives you've considered**

The alternative would be to hand configure inputs and create one output per app, which is simply not tenable as the number of services we are adding continues to increase. 

**Additional context**

We are getting errors in Elasticsearch indicating field datatype collisions. ILM is also harder to do because we cannot have a lifecycle policy per app but have to have it on the entire index

**Comment by kurosakisora** [comment] 2019-12-05 09:40
Very waiting for this answer, it looks like there isn't have a solution. And I'm also using NSQ queue with Http output Plugin, and I really hope to create topic dynamically, like this : /pub?topic=< container_name >, oh, also in Kafka too

**Comment by mr-karan** [comment] 2019-12-05 11:13
+1 This would be really nice to have!

**Comment by mtparet** [comment] 2019-12-11 06:57
We have exactly the same issue and so we have to use fluentbit and fluentd to be able to split logs into different indexes...

**Comment by ljfuyuan** [comment] 2019-12-20 03:50
+1 , create index dynamically is needed, now , we have to use fluentd instead

**Comment by novegit** [comment] 2020-01-23 20:48
You can use option _Logstash_Prefix_Key_ to define a message field, which is used to lookup the elasticsearch index for the message. Additional modifications to the index-name field can be made via lua-filter script (before the output plugin)

**Comment by test-account-0** [comment] 2020-02-05 14:59
@novegit could You give an example?

**Comment by test-account-0** [comment] 2020-02-05 19:35
I have added something like this to the filter section:
```
    [FILTER]
        Name    lua
        Match   kube.*
        script  /fluent-bit/etc/fluentbit.lua
        call    set_index
```
where set_index function looks like this:
```
function set_index(tag, timestamp, record)
    cluster = "cluster-sandbox-"
    if record["kubernetes"] ~= nil then
        if record["kubernetes"]["namespace_name"] ~= nil then
            if record["kubernetes"]["labels"]["app"] ~= nil then
                record["es_index"] = cluster
                    .. record["kubernetes"]["namespace_name"]
                    .. "-"
                    .. record["kubernetes"]["labels"]["app"]
                return 1, timestamp, record
            end
            record["es_index"] = cluster
                .. record["kubernetes"]["namespace_name"]
            return 1, timestamp, record
        end
    end
    return 1, timestamp, record
end
```
and it adds `es_index` field in elastic.

I have added also this thing to to the es output section:
```
    [OUTPUT]
        Name  es
        Match *
        Host  <somehost>
        Port  <someport>
        Logstash_Format On
        Retry_Limit 0
        Type  flb_type
        Time_Key @timestamp
        Replace_Dots On
        Logstash_Prefix cluster-sandbox
        Logstash_Prefix_Key: es_index
```

But it uses `Logstash_Prefix` all the time and doesn't resolve `Logstash_Prefix_Key`.
I'm using version 1.3.6.
Should I be trying to use 1.4-dev for it to work?

**Comment by novegit** [comment] 2020-02-06 08:54
@samirspatel
1.3.6 should be ok. Your lua-scipt looks good. Try to debug the record fields, especially your kubernetes fields, by adding an out_stdout output.

**Comment by test-account-0** [comment] 2020-02-06 11:04
@novegit 
Hmm, but es_index is added, so lua part is working fine.
The `Logstash_Prefix_Key` part is not working.

**Comment by Vfialkin** [comment] 2020-02-23 23:44
Trying to do the same. I think the problem is - `"kubernetes.[fieldName]"` is not a part of the original log but part of k8s metadata.

**Comment by Hichem-BenJeddi** [comment] 2020-09-16 20:11
> Because `Logstash_Prefix_Key` [does not support nested fields](https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch#configuration-parameters) I am using a `nest` Filter to extract Kubernetes Metadata using the following Pipeline (no Script required):
> 
> ```
> [INPUT]
>     Name              tail
>     Path              /var/log/containers/*.log
>     Parser            docker
>     Tag               kube.*
>     ....
> 
> [FILTER]
>     Name                kubernetes
>     Match               *
>     Kube_Tag_Prefix     kube.var.log.containers.
>     ...
> 
> [FILTER]
>     Name            nest
>     Match           *
>     Operation       lift
>     Wildcard        kubernetes.*
>     Nested_under    kubernetes
>     Add_prefix      k8s_
> 
> [OUTPUT]
>     Name                es
>     Match               *
>     Logstash_Format     On
>     Logstash_Prefix_Key k8s_namespace_name
>     ....
> ```
> 
> Still a very limited Option because Logstash_Prefix will be omitted and there is no way of any concatenation or use of multiple variables. In case you want to build the Index from a Label on a Pod for example you would need more nest filters to flatten the data. I'd prefer using "variables" to build the Lagstash Prefix without a custom Script as well.

Thanks, it working fine when the index name = namespace. it is possible to add logstash_k8s_namespace_name ?
How can i concat Logstash With k8s_namespace_name ?

**Comment by edsiper** [comment] 2021-01-25 15:50
Elasticsearch output plugin has been updated for logstash_prefix_key option. Changes:

```
    out_es: add support for record accessor on 'logstash_prefix_key' (#1670)
    
    The following patch adds 'record accessor' support for the
    'logstash_prefix_key' configuration property. This enable to have
    custom indices based on nested fields if required, e.g;
    
     {"key1": 1234, "kubernetes": {"labels: {"app": "prod"}}}
    
    You can configure a logstash prefix as follows:
    
     [OUTPUT]
         name                 es
         match                *
         logstash_format      on
         logstash_prefix_key  $kubernetes['labels']['app']
    
    The final index for the record above and the proposed config will generate:
    
     prod-2021.01.24
```

the changes will be part of Fluent Bit v1.7 release.

**Closed** 2021-01-25 15:52 UTC
Labels: enhancement, fixed

**Comment by offero** [comment] 2021-01-26 21:37
Can it only be 1 key or a template?

**Comment by edsiper** [comment] 2021-01-26 22:01
one key or nested keys, one key would be like ```$mykey```

**Comment by offero** [comment] 2021-01-27 14:35
Is there a way to template it in a previous filter?

**Comment by GeorgFleig** [comment] 2021-02-09 13:47
Thank you @edsiper for implementing access to nested fields!

If I understand correncly, it will not be possible to solve the use-case described in the issue with the current implementation. According to the issue description, the desired dynamic index name is `kube-<container_name>-<date>`. From your commit message introducing the change I figure it is only possible to archive an index name like `<container_name>-<date>`.

I guess this is also what @offero is asking for. Is there an efficient way to create a template for the prefix that contains the desired nested field(s)?

**Comment by offero** [comment] 2021-02-09 14:42
Exactly. Ideally I want 1 index per application name with a prefix and a date. Eg. kube-<pod.label.app>-<date>

**Comment by cmanzur** [comment] 2021-05-17 10:11
> Exactly. Ideally I want 1 index per application name with a prefix and a date. Eg. `kube-<pod.label.app>-<date>`

I made it work using:

```
[FILTER]
    Name             kubernetes
    Match            kube.*
    Merge_Log        Off
    Keep_Log         Off

[OUTPUT]
    Name  es
    Match kube.*
    Host ${ES_HOST}
    Logstash_Format On
    Logstash_Prefix_Key kubernetes['labels']['name']
```

Bu I want to **always** prepend a string to the index, like: **kube-**

Did you find any solution to this?

**Comment by ppoetz** [comment] 2021-06-10 08:04
Yep, fully agree with that. It would make index management a lot easier, if one could compose an index out of different fields and strings like:
`Logstash_Prefix    kubeapps-$kubernetes['namespace_name']-$kubernetes['labels']['custom_label']`
