### ISSUE TITLE
Large logs potentially cause buffer_chunk_limit errors in Fluentd

### ISSUE THREAD

**Issue by greggilbert** [fluent/fluent-bit#197] opened 2017-02-17 22:34 UTC
I'm using in_tail to push log data. Some of our logs are fairly large (200M+), and it seems like a lot of data is being pushed all at once. In Fluentd, I get this error:

```
[warn]: Size of the emitted data exceeds buffer_chunk_limit.
[warn]: This may occur problems in the output plugins ``at this server.``
[warn]: To avoid problems, set a smaller number to the buffer_chunk_limit
[warn]: in the forward output ``at the log forwarding server.``
```

I've changed the `buffer_chunk_limit` in Fluentd's `<match>` to be ridiculously high (1024m) and that stops the errors, but then I get this error: `buffer flush took longer time than slow_flush_log_threshold: plugin_id="object:3fac3a5d68c8" elapsed_time=39.554557704 slow_flush_log_threshold=20.0`

For reference, here's some of my Fluentd conf:
```
<match **>
  @type gelf
  host 10.200.10.41
  port 12201
  flush_interval 2s
  buffer_queue_limit 4096
  buffer_chunk_limit 1024m
  num_threads 4
</match>
```

**Comment by estroz** [comment] 2017-03-28 22:28
Are your log files very large right at the beginning of log forwarding, or do they grow to very large sizes over the course of your application running?

**Comment by amitkumarjha** [comment] 2017-05-11 09:45
Hi Did you find the solution for this issues

**Comment by edsiper** [comment] 2017-05-11 17:11
There is a fix in the last release of Fluent Bit that limits each outgoing chunk to a max of 2MB. It could be related.

**Comment by edsiper** [comment] 2017-05-11 23:53
For now I am closing this issue since it's not reproducible with latest versions. 

If the issue persist in your side, just comment here and I will re-open the ticket.

**Closed by edsiper** 2017-05-11 23:53 UTC

**Comment by amitkumarjha** [comment] 2017-05-12 07:17
Hi @edsiper 
Thanks for the reply.
Correct me if I am wrong: fluentd latest version is: Fluentd (v0.12, stable version)

**Comment by edsiper** [comment] 2017-05-16 03:49
yes, 0.12.x series is the stable one

**Comment by s-mansouri** [comment] 2017-10-31 08:57
Hi @edsiper 
I faced this problem and I use fluentd v0.14.16, I have about 100M log per days, my server has 252G of RAM with 12 processors,  I use one elasticseach node without replica and my td-agent config is:
     buffer_type memory
     buffer_chunk_limit 1g
     buffer_queue_limit 128
     flush_interval 10s
I get two warning in td-agent
```
fluent.warn{"elapsed_time":31.3985337018967,"slow_flush_log_threshold":20.0,"plugin_id":"object:3f951de96dac","message":"buffer flush took longer time than slow_flush_log_threshold: elapsed_time=31.398533701896667 slow_flush_log_threshold=20.0 plugin_id=\"object:3f951de96dac\""}
```
and

```
fluent.warn: {"retry_time":8,"next_retry_seconds":"2017-10-31 09:42:43 +0100","chunk":"55cd2c0c5685410d87dc620fcd6cde31","error":"#<Fluent::ElasticsearchOutput::ConnectionFailure: Could not push logs to Elasticsearch after 2 retries. read timeout reached>","message":"failed to flush the buffer. retry_time=8 next_retry_seconds=2017-10-31 09:42:43 +0100 chunk=\"55cd2c0c5685410d87dc620fcd6cde31\" error_class=Fluent::ElasticsearchOutput::ConnectionFailure error=\"Could not push logs to Elasticsearch after 2 retries. read timeout reached\""}
```
how can I fix this problem?

**Comment by edsiper** [comment] 2017-10-31 20:53
@s-mansouri this is related to Fluentd output plugin and it setup, not Fluent Bit. 

For more details about how to workaround the problem check the following documentation:

https://docs.fluentd.org/v0.12/articles/output-plugin-overview

> slow_flush_log_threshold section

**Comment by chrisolido** [comment] 2018-03-14 03:24
Im getting this issue even i have setup my forwarder to 

 buffer_chunk_limit 36m
 buffer_queue_limit 512

and my fluent.conf

<filter gb*>
  @type grep
  <regexp>
   key message
   pattern gb-svc.*
  </regexp>
</filter>


<match gb.**>
 type copy
 <store>
  @type elasticsearch
  log_level info
  host X.X.X.X
  user elastic
  password changeme
  port 9200
  index_name fluentd_all
  logstash_format true
  logstash_prefix fluentd
  logstash_dateformat %Y%m%d
  include_tag_key true
  tag_key @log_name
  buffer_chunk_limit 36m
  buffer_queue_limit 512
  flush_interval 2
 </store>
</match>

Still geting this error


2018-03-14 02:29:11 +0000 [warn]: Size of the emitted data exceeds buffer_chunk_limit.
2018-03-14 02:29:11 +0000 [warn]: This may occur problems in the output plugins ``at this server.``
2018-03-14 02:29:11 +0000 [warn]: To avoid problems, set a smaller number to the buffer_chunk_limit
2018-03-14 02:29:11 +0000 [warn]: in the forward output ``at the log forwarding server.``

**Comment by chrisolido** [comment] 2018-03-14 08:20
I have updated it to :

buffer_chunk_limit 1024m
buffer_queue_limit 512

Still same error.

**Comment by s-mansouri** [comment] 2018-03-31 19:13
My output in Fluentd is Elasticsearch and I faced with that error.
I realized this problem was because of Elasticsearch was not fast enough to save the data, so the Fluentd buffer becomes full. I changed some Elasticsearch configuration in order to save data faster and add more node to the Elasticsearch cluster, then my problem solved.

**Comment by VarunSrinivasa** [comment] 2019-03-04 01:43
@s-mansouri 
What configuration you changed in ElasticSearch , So that fluentd is not throwing buffer issue

**Comment by fly2tomato** [comment] 2019-05-14 02:36
> @s-mansouri
> What configuration you changed in ElasticSearch , So that fluentd is not throwing buffer issue

same question here :> @s-mansouri

**Comment by digitalsanity** [comment] 2020-03-03 09:49
My micro fluentd was getting overloaded and swapping while testing/catching up a 5GB log via forward.  After raising flush, reducing storage.backlog.mem_limit, storage.max_chunks_up and Mem_Buf_Limit it looks like I've effectively throttled/controlled backpressure on my setup.

Ideally, fluentd would have the ability to throttle/rate limit/iops limit on the forward input.  

[SERVICE]
    flush 15
..
    storage.backlog.mem_limit   2M
    storage.max_chunks_up 8
..

[INPUT]
..
    Buffer_Chunk_Size 64k
    Buffer_Max_Size 256k
    Mem_Buf_Limit 512k
