### ISSUE TITLE
[engine] caught signal (SIGSEGV) while fetching .log file

### ISSUE THREAD

**Issue by Alendill** [fluent/fluent-bit#6767] opened 2023-02-01 07:19 UTC
## Bug Report

**Describe the bug**
Me tried to using fluentbit to fetch and send some .log files of Springboot app which is running on k8s.
Fluentbit is deployed in the same pod with the app in sidecar mode, and log file sharing is using volume mount sharing.
But fluentbit stuck at "[engine] caught signal (SIGSEGV)".

**To Reproduce**
- Rubular link if applicable: No rubular link. 
- Example log message if applicable: 
```
[engine] caught signal (SIGSEGV)
#0 0x56230715fce0       in    ???() at ???:0
#1 0x5623072bf481      in    ???() at ???:0
#2 0x5623076c39a6      in    ???() at ???:0
#3 0xffffffffffffffff           in    ???() at ???:0
```
- Steps to reproduce the problem:

**Expected behavior**
As close as normal.

**Screenshots**
![0b55d913db17a466ef14ddf0b1bac74](https://user-images.githubusercontent.com/40451613/215976316-4cc64639-5067-4839-92e4-1f5bf1a73636.jpg)
![4b6fc7f31b2cbf35147e86ae83d7d3d](https://user-images.githubusercontent.com/40451613/215976376-0f044514-21ce-4b50-9513-c7eaaea77f13.jpg)

**Your Environment**
* Version used: fluentbit 2.8.0
* Configuration: 
```
[SERVICE]
  Flush               1
  Log_Level        debug
  Daemon          off
[INPUT]
  Name              tail
  Tag                  app-log.*
  Path                /demo/app/logs/*.log
[OUTPUT]
  Name              opentelemetry
  Match             *
  Host                opentelemetry-collector.opentelemetry.svc.cluster.local
  Port                4318
  Metrics_uri     /v1/metrics
  Logs_uri         /v1/logs
  Traces_uri       /v1/traces
  Log_response_payload    True
  add_label       index demp-app2_index
  add_label       Suppress_Type_Name  on
```
* Environment name and version (e.g. Kubernetes? What version?): Environment name=kubernetes, Version=1.23.14-gke.1800
* Server type and version: Cannot see it. But linux amd64
* Operating System and version: Cannot see it. But linux amd64
* Filters and plugins: None

**Additional context**

**Comment by patrick-stephens** [comment] 2023-02-01 08:13
If you switch the output plugin does it resolve it, e.g. to stdout? 

I'm wondering if this is a duplicate of the (resolved but not released yet) https://github.com/fluent/fluent-bit/issues/6720.

**Comment by Alendill** [comment] 2023-02-01 08:31
> 

Switch the output plugin to 'stdout' is okay. But we must use 'opentelemetry' this plugin.

**Comment by Syn3rman** [comment] 2023-02-01 10:00
@Alendill can you try building Fluent Bit from master to test if it is fixed?

**Comment by patrick-stephens** [comment] 2023-02-01 10:14
There is a master image (and packages) built nightly/on push but these should not be used for production (merely verifying this is indeed the issue):
- ghcr.io/fluent/fluent-bit/master:x86_64

A 2.0.9 release will be coming out soon with the fix in though.

**Comment by Alendill** [comment] 2023-02-02 02:41
> @Alendill can you try building Fluent Bit from master to test if it is fixed?

Sorry. I can't, because of company policy.

**Comment by Prims47** [comment] 2023-02-07 23:35
Hello,

I try the docker image `2.0.9-debug` with the same issue :(.

**Comment by Syn3rman** [comment] 2023-02-08 08:44
Can you send the detailed error message? I'm having trouble reproducing the issue

**Comment by Prims47** [comment] 2023-02-08 14:03
Of course:

I install fluent bit / opentelemetry via Helm chart.

# Fluent bit Version
```
image:
  repository: cr.fluentbit.io/fluent/fluent-bit
  tag: "2.0.9-debug"
```

# Fluent bit Configuration

```
[SERVICE]
        Daemon Off
        Flush 5
        Log_Level debug
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On
        
[INPUT]
        Name tail
        Path /var/log/containers/*.log
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
        Parser docker
        
[FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Buffer_Size 32K
        Merge_Log_Key data
        Kube_URL  https://kubernetes.default.svc.cluster.local:443
        
[OUTPUT]
       Name      opentelemetry
       Match    *
       Host       my-collector-collector.opentelemetry-operator-system.svc.cluster.local
       Port        4318
```

# Opentelemetry mode daemonset

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: my-collector
  namespace: opentelemetry-operator-system
spec:
  mode: daemonset
  config: |
    receivers:
      otlp:
        protocols:
          http:
    processors:

    exporters:
      logging:
        loglevel: debug

      loki:
        endpoint: "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"

    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: []
          exporters: [logging, loki]
```

# Fluent bi Log

```
Fluent Bit v2.0.9
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/02/08 14:00:57] [ info] [fluent bit] version=2.0.9, commit=4c0ca4fc5f, pid=1
[2023/02/08 14:00:57] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/02/08 14:00:57] [ info] [cmetrics] version=0.5.8
[2023/02/08 14:00:57] [ info] [ctraces ] version=0.2.7
[2023/02/08 14:00:57] [ info] [input:tail:tail.0] initializing
[2023/02/08 14:00:57] [ info] [input:tail:tail.0] storage_strategy='memory' (memory only)
[2023/02/08 14:00:57] [ info] [filter:kubernetes:kubernetes.0] https=1 host=kubernetes.default.svc.cluster.local port=443
[2023/02/08 14:00:57] [ info] [filter:kubernetes:kubernetes.0]  token updated
[2023/02/08 14:00:57] [ info] [filter:kubernetes:kubernetes.0] local POD info OK
[2023/02/08 14:00:57] [ info] [filter:kubernetes:kubernetes.0] testing connectivity with API server...
[2023/02/08 14:00:57] [ info] [filter:kubernetes:kubernetes.0] connectivity OK
[2023/02/08 14:00:57] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
[2023/02/08 14:00:57] [ info] [sp] stream processor started
[2023/02/08 14:00:57] [ info] [input:tail:tail.0] inotify_fs_add(): inode=397890 watch_fd=1 name=/var/log/containers/example_monitoring_example-24d1d405db5f03abbbf66b3f3b3ad9deac7c73e86e666950b7fbdc9f7e6b7aed.log
[2023/02/08 14:00:57] [ info] [input:tail:tail.0] inotify_fs_add(): inode=397715 watch_fd=2 name=/var/log/containers/kindnet-pshhg_kube-system_kindnet-cni-de141d5e86d8c86d8a14fee48b7d9dbf42cef7ecd24a55614345fd50d0dac38c.log
[2023/02/08 14:00:57] [ info] [input:tail:tail.0] inotify_fs_add(): inode=1057910 watch_fd=3 name=/var/log/containers/kube-proxy-254pc_kube-system_kube-proxy-b0c5953475429b52cdf9776df38cf8fe9e69c50bc5396c089a0c57345c77528a.log
[2023/02/08 14:00:57] [ info] [input:tail:tail.0] inotify_fs_add(): inode=397861 watch_fd=4 name=/var/log/containers/fluent-bit-pwnd4_monitoring_fluent-bit-147a78784bcce501a0c22925aa210132ad2ea984d9a41e42e1c2f26b93f8b921.log
[2023/02/08 14:00:57] [ info] [input:tail:tail.0] inotify_fs_add(): inode=397779 watch_fd=5 name=/var/log/containers/my-collector-collector-z5h7c_opentelemetry-operator-system_otc-container-07390fcb3962ef45ffe7dbc04d1869cbdf9f8c8574ddb4c8a1806f9f114d0611.log
[2023/02/08 14:00:57] [ warn] [input] tail.0 paused (mem buf overlimit)
[2023/02/08 14:00:57] [ info] [input] pausing tail.0
[2023/02/08 14:01:02] [ info] [output:opentelemetry:opentelemetry.0] my-collector-collector.opentelemetry-operator-system.svc.cluster.local:4318, HTTP status=200


[2023/02/08 14:01:02] [ info] [output:opentelemetry:opentelemetry.0] my-collector-collector.opentelemetry-operator-system.svc.cluster.local:4318, HTTP status=200


[2023/02/08 14:01:02] [engine] caught signal (SIGSEGV)
#0  0x56346f0dc1fb      in  protobuf_c_message_get_packed_size() at lib/fluent-otel-proto/proto_c/protobuf-c/protobuf-c.c:713
#1  0x56346f0dc167      in  repeated_field_get_packed_size() at lib/fluent-otel-proto/proto_c/protobuf-c/protobuf-c.c:675
#2  0x56346f0dc350      in  protobuf_c_message_get_packed_size() at lib/fluent-otel-proto/proto_c/protobuf-c/protobuf-c.c:744
#3  0x56346f0dc167      in  repeated_field_get_packed_size() at lib/fluent-otel-proto/proto_c/protobuf-c/protobuf-c.c:675
#4  0x56346f0dc350      in  protobuf_c_message_get_packed_size() at lib/fluent-otel-proto/proto_c/protobuf-c/protobuf-c.c:744
#5  0x56346f0dc167      in  repeated_field_get_packed_size() at lib/fluent-otel-proto/proto_c/protobuf-c/protobuf-c.c:675
#6  0x56346f0dc350      in  protobuf_c_message_get_packed_size() at lib/fluent-otel-proto/proto_c/protobuf-c/protobuf-c.c:744
#7  0x56346f0e3eb5      in  opentelemetry__proto__collector__logs__v1__export_logs_service_request__get_packed_size() at lib/fluent-otel-proto/proto_c/opentelemetry/proto/collector/logs/v1/logs_service.pb-c.c:20
#8  0x56346ef19e6c      in  flush_to_otel() at plugins/out_opentelemetry/opentelemetry.c:670
#9  0x56346ef1a2a4      in  process_logs() at plugins/out_opentelemetry/opentelemetry.c:794
#10 0x56346ef1b2d7      in  cb_opentelemetry_flush() at plugins/out_opentelemetry/opentelemetry.c:1030
#11 0x56346eb1e9ae      in  output_pre_cb_flush() at include/fluent-bit/flb_output.h:528
#12 0x56346f5853a6      in  co_init() at lib/monkey/deps/flb_libco/amd64.c:117
```

# Pods status

```
prims47@macbook-pro[15:01:55] [~/Documents/projet/opentelemetry] [main *]
-> % (⎈ |kind-kind:monitoring) kubectl get pods
NAME               READY   STATUS             RESTARTS   AGE
example            1/1     Running            0          78s
fluent-bit-5cmc2   0/1     CrashLoopBackOff   2          107s
fluent-bit-h4276   1/1     Running            3          107s
fluent-bit-pwnd4   1/1     Running            3          107s


prims47@macbook-pro[15:01:59] [~/Documents/projet/opentelemetry] [main *]
-> % (⎈ |kind-kind:monitoring) kubectl get pods
NAME               READY   STATUS             RESTARTS   AGE
example            1/1     Running            0          2m7s
fluent-bit-5cmc2   0/1     CrashLoopBackOff   3          2m36s
fluent-bit-h4276   0/1     CrashLoopBackOff   3          2m36s
fluent-bit-pwnd4   0/1     CrashLoopBackOff   3          2m36s


prims47@macbook-pro[15:02:49] [~/Documents/projet/opentelemetry] [main *]
-> % (⎈ |kind-kind:monitoring) kubectl get pods
NAME               READY   STATUS             RESTARTS   AGE
example            1/1     Running            0          2m12s
fluent-bit-5cmc2   0/1     CrashLoopBackOff   3          2m41s
fluent-bit-h4276   0/1     CrashLoopBackOff   3          2m41s
fluent-bit-pwnd4   1/1     Running            4          2m41s
```

**Comment by Prims47** [comment] 2023-02-11 11:56
I switch the output by forward in order to continue ma work

**Comment by Prims47** [comment] 2023-02-14 09:58
After severals investigation i found a good solution: Add the properties `batch_size` => https://github.com/fluent/fluent-bit/pull/6583/files. But it's not yet include inside the documentation

```
[OUTPUT]
        Name         opentelemetry
        Match        *
        Host           my-collector-collector.opentelemetry-operator-system.svc.cluster.local
        Port            4318
        batch_size 64
```

My logs:

```
Fluent Bit v2.0.9
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/02/14 09:50:24] [ info] [fluent bit] version=2.0.9, commit=4c0ca4fc5f, pid=1
[2023/02/14 09:50:24] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/02/14 09:50:24] [ info] [cmetrics] version=0.5.8
[2023/02/14 09:50:24] [ info] [ctraces ] version=0.2.7
[2023/02/14 09:50:24] [ info] [input:tail:tail.0] initializing
[2023/02/14 09:50:24] [ info] [input:tail:tail.0] storage_strategy='memory' (memory only)
[2023/02/14 09:50:24] [ info] [filter:kubernetes:kubernetes.0] https=1 host=kubernetes.default.svc.cluster.local port=443
[2023/02/14 09:50:24] [ info] [filter:kubernetes:kubernetes.0]  token updated
[2023/02/14 09:50:24] [ info] [filter:kubernetes:kubernetes.0] local POD info OK
[2023/02/14 09:50:24] [ info] [filter:kubernetes:kubernetes.0] testing connectivity with API server...
[2023/02/14 09:50:24] [ info] [filter:kubernetes:kubernetes.0] connectivity OK
[2023/02/14 09:50:24] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
[2023/02/14 09:50:24] [ info] [sp] stream processor started
[2023/02/14 09:50:24] [ info] [input:tail:tail.0] inotify_fs_add(): inode=3414389 watch_fd=1 name=/var/log/containers/example_monitoring_example-fc40fc1e63105c934c3bbdb0305d62dbc047379be4007f9cb3b34698ef968b15.log
[2023/02/14 09:50:27] [ info] [output:opentelemetry:opentelemetry.0] my-collector-collector.opentelemetry-operator-system.svc.cluster.local:4318, HTTP status=200


[2023/02/14 09:50:30] [ info] [output:opentelemetry:opentelemetry.0] my-collector-collector.opentelemetry-operator-system.svc.cluster.local:4318, HTTP status=200


[2023/02/14 09:50:33] [ info] [output:opentelemetry:opentelemetry.0] my-collector-collector.opentelemetry-operator-system.svc.cluster.local:4318, HTTP status=200


[2023/02/14 09:50:36] [ info] [output:opentelemetry:opentelemetry.0] my-collector-collector.opentelemetry-operator-system.svc.cluster.local:4318, HTTP status=200


[2023/02/14 09:50:39] [ info] [output:opentelemetry:opentelemetry.0] my-collector-collector.opentelemetry-operator-system.svc.cluster.local:4318, HTTP status=200


[2023/02/14 09:50:42] [ info] [output:opentelemetry:opentelemetry.0] my-collector-collector.opentelemetry-operator-system.svc.cluster.local:4318, HTTP status=200


[2023/02/14 09:50:45] [ info] [output:opentelemetry:opentelemetry.0] my-collector-collector.opentelemetry-operator-system.svc.cluster.local:4318, HTTP status=200


[2023/02/14 09:50:48] [ info] [output:opentelemetry:opentelemetry.0] my-collector-collector.opentelemetry-operator-system.svc.cluster.local:4318, HTTP status=200


[2023/02/14 09:50:51] [ info] [output:opentelemetry:opentelemetry.0] my-collector-collector.opentelemetry-operator-system.svc.cluster.local:4318, HTTP status=200


[2023/02/14 09:50:53] [ info] [output:opentelemetry:opentelemetry.0] my-collector-collector.opentelemetry-operator-system.svc.cluster.local:4318, HTTP status=200


[2023/02/14 09:50:56] [ info] [output:opentelemetry:opentelemetry.0] my-collector-collector.opentelemetry-operator-system.svc.cluster.local:4318, HTTP status=200


[2023/02/14 09:50:59] [ info] [output:opentelemetry:opentelemetry.0] my-collector-collector.opentelemetry-operator-system.svc.cluster.local:4318, HTTP status=200
```

**Comment by Syn3rman** [comment] 2023-02-14 11:12
Thanks @Prims47 for bringing this up, I'll update the documentation 🙂 
@Alendill do you still have this issue? If yes, can you provide a debug log?

**Comment by Alendill** [comment] 2023-02-16 05:57
> Thanks @Prims47 for bringing this up, I'll update the documentation 🙂 @Alendill do you still have this issue? If yes, can you provide a debug log?

Hey @Syn3rman , I update fluentbit to 2.0.9, but still has this issue.
I posted fluent-bit.conf and logs photos here. (Sorry I cannot post them directly because of company policy).
![699f73a88001c8e124c70a2d0213444](https://user-images.githubusercontent.com/40451613/219280491-876c385b-abd8-4f22-a750-a5ef37e06485.jpg)
![d5799461a35d4aa672f3872bcd249ec](https://user-images.githubusercontent.com/40451613/219280754-d2e3b7f1-56d6-4c7c-b7ed-e7a0dc8e39b3.jpg)

**Comment by Prims47** [comment] 2023-02-20 18:07
Hello @Syn3rman .

I need to mention something about the attribute `add_label`. For my side it's seems not to work.

```
[OUTPUT]
        Name       opentelemetry
        Match      *
        Host       my-collector-collector.opentelemetry-operator-system.svc.cluster.local
        Port       4318
        Logs_uri   /v1/logs
        batch_size 128
        add_label  app fluent-bit
        add_label  color blue
```

Log from Opentelemetry:

```
{"kind": "exporter", "data_type": "logs", "name": "logging"}
2023-02-20T18:05:34.048Z	info	LogsExporter	{"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
2023-02-20T18:05:34.048Z	info	ResourceLog #0
Resource SchemaURL:
ScopeLogs #0
ScopeLogs SchemaURL:
InstrumentationScope
LogRecord #0
ObservedTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2023-02-20 18:05:33.462556814 +0000 UTC
SeverityText:
SeverityNumber: Unspecified(0)
Body: Map({"kubernetes":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Pod\",\"metadata\":{\"annotations\":{},\"name\":\"example\",\"namespace\":\"monitoring\"},\"spec\":{\"containers\":[{\"args\":[\"/bin/sh\",\"-c\",\"while true; do echo hello $(date); sleep 3; done\"],\"image\":\"alpine\",\"name\":\"example\"}]}}\n"},"container_hash":"docker.io/library/alpine@sha256:69665d02cb32192e52e07644d76bc6f25abeb5410edc1c7a81a10ba3f0efb90a","container_image":"docker.io/library/alpine:latest","container_name":"example","docker_id":"1095e254fe25d2402e522a979f213adf54cb5596a46527291f2ecadf88599037","host":"kind-worker","namespace_name":"monitoring","pod_id":"2d839b4b-fea9-49eb-9f34-67d9a07ee070","pod_name":"example"},"log":"2023-02-20T18:05:33.462377609Z stdout F hello Mon Feb 20 18:05:33 UTC 2023"})
Trace ID:
Span ID:
Flags: 0
	{"kind": "exporter", "data_type": "logs", "name": "logging"}
2023-02-20T18:05:37.059Z	info	LogsExporter	{"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
2023-02-20T18:05:37.059Z	info	ResourceLog #0
Resource SchemaURL:
ScopeLogs #0
ScopeLogs SchemaURL:
InstrumentationScope
LogRecord #0
ObservedTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2023-02-20 18:05:36.464416441 +0000 UTC
SeverityText:
SeverityNumber: Unspecified(0)
Body: Map({"kubernetes":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Pod\",\"metadata\":{\"annotations\":{},\"name\":\"example\",\"namespace\":\"monitoring\"},\"spec\":{\"containers\":[{\"args\":[\"/bin/sh\",\"-c\",\"while true; do echo hello $(date); sleep 3; done\"],\"image\":\"alpine\",\"name\":\"example\"}]}}\n"},"container_hash":"docker.io/library/alpine@sha256:69665d02cb32192e52e07644d76bc6f25abeb5410edc1c7a81a10ba3f0efb90a","container_image":"docker.io/library/alpine:latest","container_name":"example","docker_id":"1095e254fe25d2402e522a979f213adf54cb5596a46527291f2ecadf88599037","host":"kind-worker","namespace_name":"monitoring","pod_id":"2d839b4b-fea9-49eb-9f34-67d9a07ee070","pod_name":"example"},"log":"2023-02-20T18:05:36.464262804Z stdout F hello Mon Feb 20 18:05:36 UTC 2023"})
Trace ID:
Span ID:
Flags: 0
	{"kind": "exporter", "data_type": "logs", "name": "logging"}
```

As you can see we have only body without the label.
Do you know why ?

**Comment by Prims47** [comment] 2023-02-20 18:37
@Alendill I was able to reproduce your bug with the log level of Fluentbit. Can you try to change debug to info and try ?

**Comment by Alendill** [comment] 2023-02-21 02:18
> @Alendill I was able to reproduce your bug with the log level of Fluentbit. Can you try to change debug to info and try ?

Hi @Prims47 , thank you. I changed log level debug to info, it seems running stably, but why?
![d1347052ba2eab3bfa428efbcd2ec88](https://user-images.githubusercontent.com/40451613/220230752-ab891d9f-8a88-4d20-9b7c-376d854e6704.jpg)

**Comment by Prims47** [comment] 2023-02-21 08:02
Need to ask to @Syn3rman. 

In the same time i will try to check the code code even if i am not a C develop 😄

**Closed** 2023-02-22 12:25 UTC
Labels: waiting-for-user, waiting-for-release
