### ISSUE TITLE
[Question]Internal queue full  & Task cannot be retried

### ISSUE THREAD

**Issue by userguy** [fluent/fluent-bit#1233] opened 2019-03-28 12:48 UTC
## Question Report

[error] [out_kafka] fluent-bit#producer-5: 
Failed to create socket: Too many open files (after 9555025590ms in state INIT)
Too many open files (after 9555025590ms in state INIT)

Failed to produce to topic TopicTest: Local: Queue full
[error] [sched] cannot do timeout_create()
[ warn] [out_kafka] internal queue is full, retrying in one second

[  Error] timerfd: Too many open files, errno=24 at /tmp/fluent-bit-1.0.1/lib/monkey/mk_core/mk_event_epoll.c:184

i have tail in input and i have 10 input and 10 output 
buffer as 5MB and 
Max buffer MAX  10MB

**Comment by edsiper** [comment] 2019-04-03 23:03
Please share your FULL configuration.

**Comment by userguy** [comment] 2019-04-23 06:46
[td-agent.txt](https://github.com/fluent/fluent-bit/files/3106148/td-agent.txt)

Hello Team , 

I have uploaded the configuration files , As of now i have solved the part of the problem which is too many files opened that was because of ulimit in centos 7 

Also i have three servers with 10 brokers each i.e 30 brokers with topics with three partition and 2 replica 

I am getting below error in log files of td-agent 

[2019/04/23 12:15:00] [ warn] [engine] Task cannot be retried: task_id=8 thread_id=2 output=kafka.3
[2019/04/23 12:15:01] [ warn] [engine] Task cannot be retried: task_id=4 thread_id=2 output=kafka.3
[2019/04/23 12:15:02] [ warn] [engine] Task cannot be retried: task_id=5 thread_id=2 output=kafka.1
[2019/04/23 12:15:05] [ warn] [engine] Task cannot be retried: task_id=6 thread_id=2 output=kafka.1
[2019/04/23 12:15:06] [ warn] [engine] Task cannot be retried: task_id=16 thread_id=2 output=kafka.9
[2019/04/23 12:15:10] [ warn] [engine] Task cannot be retried: task_id=7 thread_id=2 output=kafka.3
[2019/04/23 12:15:11] [ warn] [engine] Task cannot be retried: task_id=18 thread_id=2 output=kafka.9
[2019/04/23 12:15:12] [ warn] [engine] Task cannot be retried: task_id=2 thread_id=2 output=kafka.1
[2019/04/23 12:15:13] [ warn] [engine] Task cannot be retried: task_id=9 thread_id=2 output=kafka.3
[2019/04/23 12:15:16] [ warn] [engine] Task cannot be retried: task_id=5 thread_id=2 output=kafka.3


[2019/04/09 10:01:52] [ warn] [out_kafka] internal queue is full, retrying in one second
[2019/04/09 10:01:52] [ warn] [out_kafka] internal queue is full, retrying in one second
[2019/04/09 10:01:54] [ warn] [out_kafka] internal queue is full, retrying in one second
[2019/04/09 10:01:57] [ warn] [out_kafka] internal queue is full, retrying in one second
[2019/04/09 10:01:57] [ warn] [out_kafka] internal queue is full, retrying in one second
[2019/04/09 10:01:58] [ warn] [out_kafka] internal queue is full, retrying in one second
[2019/04/09 10:01:58] [ warn] [out_kafka] internal queue is full, retrying in one second
[2019/04/09 10:01:59] [ warn] [out_kafka] internal queue is full, retrying in one second
[2019/04/09 10:02:00] [ warn] [out_kafka] internal queue is full, retrying in one second
[2019/04/09 10:02:03] [ warn] [out_kafka] internal queue is full, retrying in one second
[2019/04/09 10:02:04] [ warn] [out_kafka] internal queue is full, retrying in one second
[2019/04/09 10:02:06] [ warn] [out_kafka] internal queue is full, retrying in one second
[2019/04/09 10:02:09] [ warn] [out_kafka] internal queue is full, retrying in one second
[2019/04/09 10:02:10] [ warn] [out_kafka] internal queue is full, retrying in one second

**Comment by userguy** [comment] 2019-04-23 07:45
currently there are 10 server where this config is running and there is no tuning done for kafka output .we are expecting every day around 70 million * 10 servers records  to be inserted in kafka from td-agent

**Comment by userguy** [comment] 2019-05-15 12:57
??

**Comment by edsiper** [comment] 2019-05-15 13:21
Hi, 

You are being hit by bug reported in #1317, that one was already fixed and the fix will be included in v1.1.1 in a few days.

Note: the problem is reproducible only when there is a lot of retries.

**Closed** 2019-06-13 18:09 UTC
Labels: bug, fixed
