### ISSUE TITLE
The latest (2.0.0) version not work with old configuration (<=1.9.9)

### ISSUE THREAD

**Issue by NhokCrazy199** [fluent/fluent-bit#6281] opened 2022-10-26 02:34 UTC
## Bug Report

**Describe the bug**
Latest version doesn't work with previous version config

**To Reproduce**
When I used **fluentbit:latest** version something went wrong
```
Fluent Bit v2.0.0
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/10/26 01:50:32] [ warn] [config] Read twice. path=/fluent-bit/etc/..2022_10_26_01_49_35.3452625185//filter-k8s.conf
[2022/10/26 01:50:32] [error] configuration file contains errors, aborting.
```
although this config worked for previous versions (<=1.9.9)

**Expected behavior**
Fluent Bit running

**Your Environment**
* Version used:  **fluent/fluent-bit:latest**
* Configuration:
```
fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Log_Level    debug
        Daemon       off
        Parsers_File parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

    @INCLUDE input-tail.conf
    @INCLUDE filter-k8s.conf
    @INCLUDE filter-stdout.conf
    @INCLUDE output-elasticsearch.conf

  input-tail.conf: |
    [INPUT]
        Name              tail
        Tag               company-prod-json.log
        Path              /var/log/company/*.log
        DB                /var/log/flb_company.db
        Mem_Buf_Limit     32M
        Buffer_Chunk_Size 2M
        Buffer_Max_Size   2M
        Refresh_Interval  10

  filter-k8s.conf: |
    [FILTER]
        Name   record_modifier
        Match  *
        Record namespace ${K8S_NAMESPACE}
        Record app_name ${K8S_APP_NAME}
        Record pod_name ${K8S_POD_NAME}
        Record pod_ip ${K8S_POD_IP}
        Record node_ip ${K8S_NODE_IP}

  filter-stdout.conf: |
    [FILTER]
        Name         parser
        Match        *
        Key_Name     log
        Parser       json
        Reserve_Data True

  parsers.conf: |
    [PARSER]
        Name            json
        Format          json
        time_type       string
        Time_Key        time
        Time_Format     %d-%m-%Y %H:%M:%S.%L
        Time_Keep       On
        Decode_Field_As escaped_utf8 log do_next
        Decode_Field_As json         log try_next
        Decode_Field_As escaped      log

  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        HTTP_User       elastic
        HTTP_Passwd     ${FLUENT_ELASTICSEARCH_PASSWD}
        Logstash_Format On
        Logstash_Prefix log-${K8S_NAMESPACE}-${K8S_APP_NAME}
        Retry_Limit     False
        Suppress_Type_Name On
 output-stdout.conf: |
    [OUTPUT]
        Name  stdout
        Match *

  output-null.conf: |
    [OUTPUT]
        Name  null
        Match *
```
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes:v1.24.4
* Server type and version: Debian GNU/Linux 10 (buster)
* Operating System and version: 4.19.0-22-amd64

**Comment**
I tried other configurations, when I try to leave out the `@INCLUDE` lines only `@INCLUDE input-tail.conf` can work, the other `@INCLUDE` all get the same error. I don't know where the problem is. I checked the changes for the latest version but didn't see the problem

**Comment by tpdlocke** [comment] 2022-10-26 09:27
Same problem for me. Unable to use 2.0.0

**Comment by drbugfinder-work** [comment] 2022-10-26 13:41
For us it helped to change the working dir to /fluent-bit/etc

**Comment by 030** [comment] 2022-10-26 14:55
Before 2.0.0 the following worked:

        - command:
          - /fluent-bit/bin/fluent-bit
          - -c
          - /fluent-bit/etc/custom/fluent-bit.conf

Since 2.0.0 the following error occurred:

[2022/10/26 14:51:05] [ warn] [config] Read twice. path=/fluent-bit/etc/custom/..2022_10_26_14_50_51.3633200127//filters.conf
[2022/10/26 14:51:05] [error] configuration file contains errors, aborting.

Specifying the workdir solved the issue:

        - command:
          - /fluent-bit/bin/fluent-bit
          - -c
          - fluent-bit.conf
          - -w
          - /fluent-bit/etc/custom

**Comment by oshelot** [comment] 2022-10-26 19:44
I upgraded today and now nothing works. No other changes. Per @NhokCrazy199 comment, seems related to INCLUDES. The service starts. All my configs are broken our in INCLUDE files. No ports, inbound or outbound are being opened.

 Running on Ubuntu 20.04.

**Comment by nokute78** [comment] 2022-10-26 20:34
Sorry for this issue. It is caused by https://github.com/fluent/fluent-bit/pull/6213 . 

I sent a patch https://github.com/fluent/fluent-bit/pull/6287 .
Could you check it ?

**Comment by NhokCrazy199** [comment] 2022-10-28 03:25
I don't think it's really the *work dir*. Because *fluentbit* obviously reads `fluent-bit.conf` and `parsers.conf` .
It is a fact that if I change the configuration files to ```fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Log_Level    debug
        Daemon       off
        Parsers_File parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

    [INPUT]
        Name              tail
        Tag               company-prod-json.log
        Path              /var/log/company/*.log
        DB                /var/log/flb_company.db
        Mem_Buf_Limit     32M
        Buffer_Chunk_Size 2M
        Buffer_Max_Size   2M
        Refresh_Interval  10

    [FILTER]
        Name   record_modifier
        Match  *
        Record namespace ${K8S_NAMESPACE}
        Record app_name ${K8S_APP_NAME}
        Record pod_name ${K8S_POD_NAME}
        Record pod_ip ${K8S_POD_IP}
        Record node_ip ${K8S_NODE_IP}

    [FILTER]
        Name         parser
        Match        *
        Key_Name     log
        Parser       json
        Reserve_Data True

    [OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        HTTP_User       elastic
        HTTP_Passwd     ${FLUENT_ELASTICSEARCH_PASSWD}
        Logstash_Format On
        Logstash_Prefix log-${K8S_NAMESPACE}-${K8S_APP_NAME}
        Retry_Limit     False
        Suppress_Type_Name On

  parsers.conf: |
    [PARSER]
        Name            json
        Format          json
        time_type       string
        Time_Key        time
        Time_Format     %d-%m-%Y %H:%M:%S.%L
        Time_Keep       On
        Decode_Field_As escaped_utf8 log do_next
        Decode_Field_As json         log try_next
        Decode_Field_As escaped      log

``` the error is gone.
But that's funny because I know it was INCLUDE that caused this error

**Comment by oshelot** [comment] 2022-10-28 03:53
Oh wow - I just realized the upgrade to 2.0.0. overwrote fluent-bit.conf - is this normal behavior?

**Comment by oshelot** [comment] 2022-10-28 04:09
Luckily I had a backup. If I take what's in an INCLUDE file and put in fluent-bit.conf, fluent-bit service starts normally. If I use INCLUDE, I get the following error.

```
Oct 28 04:01:43 flb-relay fluent-bit[4679]: [2022/10/28 04:01:43] [ warn] [config] Read twice. path=/etc/fluent-bit//esx-syslog.conf
Oct 28 04:01:43 flb-relay fluent-bit[4679]: [2022/10/28 04:01:43] [error] configuration file contains errors, aborting.
Oct 28 04:01:43 flb-relay systemd[1]: fluent-bit.service: Main process exited, code=exited, status=1/FAILURE
Oct 28 04:01:43 flb-relay systemd[1]: fluent-bit.service: Failed with result 'exit-code'.
Oct 28 04:01:43 flb-relay systemd[1]: fluent-bit.service: Scheduled restart job, restart counter is at 5.
Oct 28 04:01:43 flb-relay systemd[1]: fluent-bit.service: Start request repeated too quickly.
Oct 28 04:01:43 flb-relay systemd[1]: fluent-bit.service: Failed with result 'exit-code'.
```

**Comment by nokute78** [comment] 2022-10-29 21:40
The patch #6287 was released as v2.0.3.
https://fluentbit.io/announcements/v2.0.3/

**Comment by edsiper** [comment] 2022-10-30 03:43
@NhokCrazy199 @oshelot @drbugfinder-work would you please if v2.0.3 solves the issue ?

**Comment by edsiper** [comment] 2022-10-30 03:45
@drbugfinder-work already confirmed the patch works, closing the issue.

Please move to v2.0.3

**Closed by edsiper** 2022-10-30 03:45 UTC
Labels: waiting-for-user, status: waiting-for-triage

**Comment by drbugfinder-work** [comment] 2022-10-30 19:32
Tested successfully in v2.0.3

**Comment by LeoWinterDE** [comment] 2022-11-01 07:48
> Oh wow - I just realized the upgrade to 2.0.0. overwrote fluent-bit.conf - is this normal behavior?

I can confirm that, the config gets overwritten - like back in #5377

**Comment by markstos** [comment] 2022-11-08 19:44
I just upgraded from 1.9.9 to 2.0.4 on Ubuntu and the config file is overwritten (!!). 

This is a packaging problem with the Debian/Ubuntu package. The files in etc should be handled specially as "conffiles". But in the 2.0.4 package, they are treated as a regular files. Because of this issue, the new config files ovewrite the current ones without prompting, essentially disabling any logging you had setup and instead logging the CPU to STDOUT instead. 

The page explains about `conffiles` and how update the Debian/Ubuntu packaging to treat `/etc/` file specially avoid this happenin g in the future:

https://raphaelhertzog.com/2010/09/21/debian-conffile-configuration-file-managed-by-dpkg/
