### ISSUE TITLE
ALERT: Fluentbit.io is not working!!!! 

### ISSUE THREAD

**Issue by dextercrypt** [fluent/fluent-bit#7321] opened 2023-05-04 17:54 UTC
Hi Guys, 
This is to notify that the domain **fluentbit.io is not working** as the domain might have expired or something else has been down in the system. This will cause installations of fluent-bit to fail and also the website is not accessible.
Please look into this as soon as possible.

ERROR is as following: 

```
================================
 Fluent Bit Installation Script 
================================
This script requires superuser access to install packages.
You will be prompted for your password by sudo.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:10 --:--:--     0curl: (7) Failed to connect to packages.fluentbit.io port 443: Connection timed out
gpg: no valid OpenPGP data found.
deb [signed-by=/usr/share/keyrings/fluentbit-keyring.gpg] https://packages.fluentbit.io/ubuntu/bionic bionic main
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease                                                                                
Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                                         
Hit:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease                                        
Err:5 https://packages.fluentbit.io/ubuntu/bionic bionic InRelease                                       
  Could not connect to packages.fluentbit.io:443 (99.83.154.118), connection timed out
Reading package lists... Done                           
W: Failed to fetch https://packages.fluentbit.io/ubuntu/bionic/dists/bionic/InRelease  Could not connect to packages.fluentbit.io:443 (99.83.154.118), connection timed out
```

![Screenshot from 2023-05-04 23-18-43](https://user-images.githubusercontent.com/36314791/236287819-80f82c54-da20-4d1a-9c5c-aedbe013337c.png)

**Comment by patrick-stephens** [comment] 2023-05-04 18:26
Duplicate of #7320, DNS issue should be resolved now but may take some time to propagate.

**Comment by dextercrypt** [comment] 2023-05-04 18:27
> Duplicate of #7320, DNS issue should be resolved now but may take some time to propagate.

Thanks alot Patrick.

**Closed by patrick-stephens** 2023-05-04 18:26 UTC
Labels: status: waiting-for-triage
