### ISSUE TITLE
[error] net_tcp_connect: Can't get addr info

### ISSUE THREAD

**Issue by tomqwu** [fluent/fluent-bit#227] opened 2017-04-05 13:14 UTC
Fluentbit container exits after few mins of starting, and getting Can't get addr info
```
/fluent-bit # cat log/fluent-bit.log
[2017/04/04 16:20:25] [ info] [engine] started
[2017/04/04 16:20:25] [ info] [in_fw] binding 0.0.0.0:24224
[2017/04/04 16:20:35] [error] net_tcp_connect: Can't get addr info
[2017/04/04 16:20:40] [error] net_tcp_connect: Can't get addr info
[2017/04/04 16:20:50] [error] net_tcp_connect: Can't get addr info
[2017/04/04 16:20:55] [error] net_tcp_connect: Can't get addr info
[2017/04/04 16:23:14] [ info] [engine] started
[2017/04/04 16:23:14] [ info] [in_fw] binding 0.0.0.0:24224
[2017/04/04 16:23:59] [error] net_tcp_connect: Can't get addr info
[2017/04/04 16:24:15] [ info] [engine] started
[2017/04/04 16:24:15] [ info] [in_fw] binding 0.0.0.0:24224
[2017/04/04 16:26:36] [ info] [engine] started
[2017/04/04 16:26:36] [ info] [in_fw] binding 0.0.0.0:24224
[2017/04/04 16:27:06] [error] net_tcp_connect: Can't get addr info
[2017/04/04 21:36:41] [ info] [engine] started
[2017/04/04 21:36:41] [ info] [in_fw] binding 0.0.0.0:24224
[2017/04/04 21:49:41] [error] net_tcp_connect: Can't get addr info
[2017/04/04 21:51:20] [ info] [engine] started
[2017/04/04 21:51:20] [ info] [in_fw] binding 0.0.0.0:24224
[2017/04/04 21:51:35] [error] net_tcp_connect: Can't get addr info
[2017/04/04 21:51:41] [ info] [engine] started
[2017/04/04 21:51:41] [ info] [in_fw] binding 0.0.0.0:24224
[2017/04/04 22:41:41] [error] net_tcp_connect: Can't get addr info
[2017/04/05 13:11:39] [ info] [engine] started
[2017/04/05 13:11:39] [ info] [in_fw] binding 0.0.0.0:24224
```

Inside of container, I am able to ping & telnet the ES endpoint, not sure what is the issue here, the error message is very generic and not explicit on what's expectation for the endpoint here. 
```
[SERVICE]
    Flush     5
    Daemon    Off
    Log_Level info
    Log_File  /fluent-bit/log/fluent-bit.log

[INPUT]
    Name Forward
    Port 24224

[INPUT]
    Name tail
    Path /app/logs/
    DB   /tmp/fluentbit_applogs.db

[INPUT]
    Name tail
    Path /var/lib/docker/containers/*.log
    DB   /tmp/fluentbit_docker.db

[OUTPUT]
    Name  stdout
    Match *

[OUTPUT]
    Name  es
    Match *
    Host  ${ELASTICSEARCH_HOST}
    Port  ${ELASTICSEARCH_PORT}
    Index fluentbit
    Logstash_Format true
    Logstash_prefix ${LOGSTASH_PREFIX}
```

**Comment by tomqwu** [comment] 2017-04-05 13:54
After removing this line, fluent-bit stopped exit automatically, and no more error being logged. 
```
[INPUT]
    Name tail
    Path /var/lib/docker/containers/*.log
    DB   /tmp/fluentbit_docker.db
```

**Comment by edsiper** [comment] 2017-04-05 14:22
are you running 0.11.1 version ?

**Comment by tomqwu** [comment] 2017-04-05 14:24
yes I am running the latest 0.11.1 from this morning.

**Comment by edsiper** [comment] 2017-04-05 14:34
If I push some verbose messages for debugging in our GIT, are you able to pull the changes, recompile and test ?

**Comment by edsiper** [comment] 2017-04-05 14:55
Please do the following tests:

1. Log into the container and make sure the environment variables are set: 

```
echo $ELASTICSEARCH_HOST $ELASTICSEARCH_PORT
```

2. Please share here the Yaml file used to deploy Fluent Bit

**Comment by tomqwu** [comment] 2017-04-05 14:57
```
# echo $ELASTICSEARCH_HOST $ELASTICSEARCH_PORT
es-digital.xyz.ca 9200
```

**Comment by edsiper** [comment] 2017-04-05 15:00
In our 0.11 branch, I pushed pushed some changes that add more details to the reason why getaddrinfo() is failing, this is the branch:

https://github.com/fluent/fluent-bit/tree/0.11

Let me know if you need assistance to build it or I can build a Docker image for you

**Comment by tomqwu** [comment] 2017-04-05 15:03
thanks @edsiper it would be great if you can point me to the docker image

**Comment by edsiper** [comment] 2017-04-05 15:24
FYI: images are building, that will take about 30 min, I will ping you back once they are ready for testing.

**Comment by edsiper** [comment] 2017-04-05 15:51
Images are ready, steps:

Our default daemonset example file is here:

https://github.com/fluent/fluent-bit-kubernetes-daemonset/blob/master/fluent-bit-daemonset-elasticsearch.yaml#L20

As you can see, it specify to use the image fluent/fluent-bit-kubernetes-daemonset, but now there are  [new tags](https://hub.docker.com/r/fluent/fluent-bit-kubernetes-daemonset/tags/):

- 0.11-next
- latest

The yaml file points to latest, so make it sure it use 0.11-next:

```
image: fluent/fluent-bit-kubernetes-daemonset:0.11-next
```

then retry.

**Comment by tomqwu** [comment] 2017-04-05 16:46
I am not using it with kubernetes yet, I am testing it on docker standalone

**Comment by edsiper** [comment] 2017-04-05 16:49
please get this 0.11-next from: https://hub.docker.com/r/fluent/fluent-bit/tags/

**Comment by edsiper** [comment] 2017-04-07 22:34
v0.11.2 adds more verbose messages when using getaddrinfo(). New docker images are available:

```
docker pull fluent/fluent-bit:0.11.2
```

Please let me know if you finally solved the problem (DNS maybe?) or if you need some additional assistance.

**Comment by tomqwu** [comment] 2017-04-09 02:25
I was not able to reproduce the issue with newer version, let me do more testing next week.

**Comment by edsiper** [comment] 2017-04-10 22:28
@tomqwu did you were able to reproduce the problem again ?

**Comment by edsiper** [comment] 2017-04-12 16:24
Closing this issue for now, assuming it's not longer active. If the problem is still present, please open a new issue and reference this one.

**Closed by edsiper** 2017-04-12 16:24 UTC

**Comment by alihalabyah** [comment] 2018-08-06 09:25
@edsiper Actually I'm facing the same issue at the moment.

```
[ warn] net_tcp_fd_connect: getaddrinfo(host='vpc-aws-es-link'): Temporary failure in name resolution
```

**Comment by amit-uc** [comment] 2020-07-17 10:07
@alihalabyah were you able to solve that issue?

**Comment by amithapa** [comment] 2020-07-17 10:07
@alihalabyah Were you able to solve theissue?
