### ISSUE TITLE
I used the parser filter plugin to grade logs, but it didn't work

### ISSUE THREAD

**Issue by yonchin** [fluent/fluent-bit#651] opened 2018-06-20 10:05 UTC
**fluent-bit.conf :** 
`
[SERVICE]
  Flush         1
  Log_Level     info
  Daemon        off
  Parsers_File  parsers.conf

[INPUT]
  Name tail
  Tag  test
  Path /var/log/containers/*.log
  Parser docker
  DB /var/log/mycontainer.db

[FILTER]
  Name          parser
  Match         test*
  Key_Name      log
  Parser        mytest
  Unescape_Key  True
  Reserve_Data  True

[OUTPUT]
  Name            stdout
  Match           test*
`

**parsers.conf:** 
`
[PARSER]
  Name        docker
  Format      json
  Time_Key    time
  Time_Format %Y-%m-%dT%H:%M:%S.%L
  Time_Keep   On
  Decode_Field_As escaped_utf8 log

[PARSER]
  Name        mytest
  Format      regex
  Regex       /(.*) \[?(?<level>(notice|debu(?:g)?|i(?:nfo)?|warn(?:ing)?|err(?:or)?|crit(?:ical)?|fatal|severe|emerg(?:ency)?))\]? (?<message>.*)/i
`

**regex example:**  http://rubular.com/r/XcL6JlPB1c

**Comment by marckamerbeek** [comment] 2018-06-21 06:57
Hi Yonchin

Did you check the logging of fluent-bit? Have you enabled "debug" logging? Your config says "info".

One thing that might be an issue is the start of your regex. I'm not really sure, but I thought it should start with a ^.

**Comment by yonchin** [comment] 2018-06-21 10:04
@marckamerbeek  Thank you for your reply. I have found the reason, which is caused by the case identifier 'I'

**Comment by yonchin** [comment] 2018-06-22 04:32
But one problem I had was that when I put this rule in kubernetes, it didn't work

**Comment by marckamerbeek** [comment] 2018-06-22 05:14
Can you be more specific so maybe I can help you? I use the kubernetes plugin.

**Comment by edsiper** [comment] 2019-12-23 22:31
the user identified the root cause of the problem in the setup, closing this.

**Closed by edsiper** 2019-12-23 22:31 UTC
Labels: not-an-issue
