### ISSUE TITLE
CentOS 7 build failures

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#8606] opened 2024-03-20 08:45 UTC
## Bug Report

On new PRs, CentOS 7 CI workflow is failing with the following error:

```
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
Dockerfile.centos7:28
--------------------
  26 |         -DFLB_OUT_PGSQL=On ../
  27 |     
  28 | >>> RUN make -j "$(getconf _NPROCESSORS_ONLN)"
  29 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c make -j \"$(getconf _NPROCESSORS_ONLN)\"" did not complete successfully: exit code: 2
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c make -j \"$(getconf _NPROCESSORS_ONLN)\"" did not complete successfully: exit code: 2
```

ref: https://github.com/fluent/fluent-bit/actions/runs/8355812140/job/22871635010?pr=8605

**Comment by patrick-stephens** [comment] 2024-03-20 12:07
@edsiper it looks like a few commits were made direct to master and bypassed the CentOS 7 build checks - which unfortunately means it now fails to build for CentOS 7.
I think the offending commit is https://github.com/fluent/fluent-bit/commit/6e601c71a5bf7e1a5caaeec5cc17be292532cbff, prior to this it builds fine. There have been subsequent commits as well so the underlying cause needs to be fixed, merged and then PRs rebased to resolve this.

**Comment by patrick-stephens** [comment] 2024-03-20 12:09
You can reproduce quite easily to verify:
```
./packaging/build.sh -d centos/7
```
OR
```
docker build . -f ./dockerfiles/Dockerfile.centos7
```

In either case this means we cannot currently release for CentOS 7.

**Comment by patrick-stephens** [comment] 2024-03-20 12:28
It also looks like this fails on other CentOS targets so may be a more general problem:
- centos/8
```
[ 36%] Building C object lib/ctraces/src/CMakeFiles/ctraces-static.dir/ctr_id.c.o
In file included from sql-parser.y:16:
/tmp/fluent-bit/build/plugins/processor_sql/parser/processor-sql-parser_lex.h:213:41: error: expected identifier or '(' before numeric constant
 #define yywrap(yyscanner) (/*CONSTCOND*/1)
                                         ^
sql-parser.y:29:5: note: in expansion of macro 'yywrap'
make[2]: *** [plugins/processor_sql/parser/CMakeFiles/processor-sql-parser.dir/build.make:133: plugins/processor_sql/parser/CMakeFiles/processor-sql-parser.dir/processor-sql_parser.c.o] Error 1
```

**Comment by patrick-stephens** [comment] 2024-03-20 12:40
And AL2 plus older Ubuntu targets too failing in nightly builds: https://github.com/fluent/fluent-bit/actions/runs/8354528766

**Closed** 2024-03-20 13:37 UTC
Labels: bug
