### ISSUE TITLE
SIGSEGV [error] [engine_dispatch] could not retrieve chunk content, removing retry

### ISSUE THREAD

**Issue by sunoce** [fluent/fluent-bit#3078] opened 2021-02-15 15:14 UTC
## Bug Report

**Describe the bug**
Setup:
- Fluentbit runs as Daemon and processes service logs from my microservices
- Fluentbit wants to write to kafka, but kafka is not available so fluentbit has to buffer the logs 
- I want to test the case in which kafka might not be available under high pressure
- 900 logs per second are written from my service for about 5 min

With this Setup and the following configuration, fluentbit exits with a SIGSEGV and restarts the pod.

```
config:
  service: |
    [SERVICE]
      Flush 10
      Daemon Off
      Log_Level info
      storage.path /var/log/flb-storage/
      storage.sync normal
      storage.checksum On
      storage.backlog.mem_limit 50M
      storage.metrics On
      Parsers_File custom_parsers.conf
      HTTP_Server On
      HTTP_Listen 0.0.0.0
      HTTP_Port 2020
  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
      Name              tail
      Alias             proxy_tail
      storage.type      filesystem
      Tag               kube.proxy.*
      Path              /var/log/containers/prox*.log
      Parser		  cri
      Skip_Long_Lines   On
      Refresh_Interval  10
      DB /var/log/proxy.db
      Mem_Buf_Limit  50MB

    [INPUT]
      Name              tail
      Alias             services_tail
      storage.type      filesystem
      Tag               kube.service.*
      Path              /var/log/containers/service*.log
      Parser		  cri
      Skip_Long_Lines   On
      Refresh_Interval  10
      DB /var/log/app.db
      Mem_Buf_Limit  50MB

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
      Name             kubernetes
      Match            kube.proxy.*
      Kube_URL         https://kubernetes.default.svc:443
      Kube_CA_File     /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      Kube_Token_File  /var/run/secrets/kubernetes.io/serviceaccount/token
      Kube_Tag_Prefix  kube.proxy.var.log.containers.
      Merge_Log        On
      Merge_Log_Key    log_processed

    [FILTER]
      Name             kubernetes
      Match            kube.service.*
      Kube_URL         https://kubernetes.default.svc:443
      Kube_CA_File     /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      Kube_Token_File  /var/run/secrets/kubernetes.io/serviceaccount/token
      Kube_Tag_Prefix  kube.service.var.log.containers.
      Merge_Log        On
      Merge_Log_Key    log_processed

    [FILTER]
      Name parser
      Match kube.service.*
      Key_Name log
      Parser docker
      Reserve_Data On

    [FILTER]
      Name parser
      Match kube.proxy.*
      Key_Name log
      Parser haproxy
      Reserve_Data On

    [FILTER]
      Name parser
      Match kube.proxy.*
      Key_Name log
      Parser haproxysystem
      Reserve_Data On

    [FILTER]
      Name parser
      Match kube.proxy.*
      Key_Name message
      Parser docker
      Reserve_Data On

    [FILTER]
      Name          rewrite_tag
      Match         kube.proxy.*
      Rule          $type ^([a-zA-Z]+)$ kube.systemproxy false
      Emitter_Name  re_emitted
  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
      Name kafka
      Alias services_kafka_output
      Match kube.service.*
      Brokers kafka-logging-kafka-bootstrap.kafka.svc.cluster.local:9092
      Format json
      Topics services
      Timestamp_Format iso8601
      rdkafka.log.connection.close false
      rdkafka.request.required.acks 1
      Retry_Limit     5
      workers 2


    [OUTPUT]
      Name kafka
      Alias proxy_kafka_output
      Match kube.proxy.*
      Brokers kafka-logging-kafka-bootstrap.kafka.svc.cluster.local:9092
      Format json
      Topics proxy
      Timestamp_Format iso8601
      rdkafka.log.connection.close false
      rdkafka.request.required.acks 1
      Retry_Limit     5
      workers 2


    [OUTPUT]
      Name kafka
      Alias systemproxy_kafka_output
      Match kube.systemproxy
      Brokers kafka-logging-kafka-bootstrap.kafka.svc.cluster.local:9092
      Format json
      Topics systemproxy
      Timestamp_Format iso8601
      rdkafka.log.connection.close false
      rdkafka.request.required.acks 1
      Retry_Limit     5
      workers 2


    [OUTPUT]
      Name kafka
      Alias fluentbit_kafka_output
      Match kube.fluentbit.*
      Brokers kafka-logging-kafka-bootstrap.kafka.svc.cluster.local:9092
      Format json
      Topics fluentbit
      Timestamp_Format iso8601
      rdkafka.log.connection.close false
      rdkafka.request.required.acks 1
      Retry_Limit     5
      workers 2

  ## https://docs.fluentbit.io/manual/pipeline/parsers
  customParsers: |
    [PARSER]
      Name        docker
      Format      json
      Time_Key    timestamp
      Time_Format %Y-%m-%dT%H:%M:%S.%L
      Time_Keep   On
      Decode_Field_As   escaped    log

    [PARSER]
      Name        haproxy
      Format      regex
      Regex       ^\<(?<pri>[0-9]+)\>(?<timestamp>[^ ]* {1,2}[^ ]* [^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
      Time_Key    timestamp
      Time_Keep   On
      Time_Format %b %d %H:%M:%S

    [PARSER]
      Name        haproxysystem
      Format      regex
      Regex       ^\[(?<type>[a-zA-Z]+)\]\s(?<time>[0-9]+\/[0-9]+)\s\((?<pid>[0-9])\)\s(?:[^\:]*\:)? *(?<message>.*)$

    [PARSER]
      Name        cri
      Format      regex
      Regex       ^(?<containerd_time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$

    [PARSER]
      Name        docker-daemon
      Format      regex
      Regex       time="(?<time>[^ ]*)" level=(?<level>[^ ]*) msg="(?<msg>[^ ].*)"
      Time_Key    time
      Time_Format %Y/%m/%dT%H:%M:%S.%L
      Time_Keep   On
```

The following error occurs:

```
[2021/02/15 14:37:45] [ warn] [output:kafka:services_kafka_output] internal queue is full, retrying in one second
[2021/02/15 14:37:45] [error] [storage] format check failed: services_tail/1-1613399863.934440888.flb
[2021/02/15 14:37:45] [error] [storage] [cio file] file descriptor already exists: [fd=183] services_tail:1-1613399863.934440888.flb
[2021/02/15 14:37:45] [error] [input chunk] cannot retrieve temporary chunk
[2021/02/15 14:37:45] [error] [storage] [cio file] file descriptor already exists: [fd=183] services_tail:1-1613399863.934440888.flb
[2021/02/15 14:37:46] [error] % Failed to produce to topic services: Local: Queue full

[2021/02/15 14:37:46] [ warn] [output:kafka:services_kafka_output] internal queue is full, retrying in one second
[2021/02/15 14:37:46] [ warn] [engine] failed to flush chunk '1-1613399790.98465167.flb', retry in 436 seconds: task_id=1, input=services_tail > output=services_kafka_output (out_id=0)
[2021/02/15 14:37:47] [error] % Failed to produce to topic services: Local: Queue full

[2021/02/15 14:37:47] [ warn] [output:kafka:services_kafka_output] internal queue is full, retrying in one second
[2021/02/15 14:37:47] [error] [storage] format check failed: services_tail/1-1613399865.814790209.flb
[2021/02/15 14:37:47] [error] [storage] [cio file] file descriptor already exists: [fd=182] services_tail:1-1613399865.814790209.flb
[2021/02/15 14:37:47] [error] [input chunk] cannot retrieve temporary chunk
[2021/02/15 14:37:47] [error] [storage] [cio file] file descriptor already exists: [fd=182] services_tail:1-1613399865.814790209.flb
[2021/02/15 14:37:48] [error] % Failed to produce to topic services: Local: Queue full

[2021/02/15 14:37:48] [ warn] [output:kafka:services_kafka_output] internal queue is full, retrying in one second
[2021/02/15 14:37:48] [ warn] [engine] failed to flush chunk '1-1613399851.793978150.flb', retry in 14 seconds: task_id=37, input=services_tail > output=services_kafka_output (out_id=0)
[2021/02/15 14:37:49] [error] % Failed to produce to topic services: Local: Queue full

[2021/02/15 14:37:49] [ warn] [output:kafka:services_kafka_output] internal queue is full, retrying in one second
[2021/02/15 14:37:49] [error] [storage] format check failed: services_tail/1-1613399840.98305820.flb
[2021/02/15 14:37:49] [engine] caught signal (SIGSEGV)
[2021/02/15 14:37:49] [error] [storage] [cio file] file descriptor already exists: [fd=166] services_tail:1-1613399840.98305820.flb
[2021/02/15 14:37:49] [error] [engine_dispatch] could not retrieve chunk content, removing retry
#0  0x555f6aacf62f      in  __mk_list_del() at lib/monkey/include/monkey/mk_core/mk_list.h:87
#1  0x555f6aacf666      in  mk_list_del() at lib/monkey/include/monkey/mk_core/mk_list.h:93
#2  0x555f6aacfeea      in  flb_sched_request_destroy() at src/flb_scheduler.c:327
#3  0x555f6aad009e      in  flb_sched_event_handler() at src/flb_scheduler.c:407
#4  0x555f6aacceef      in  flb_engine_start() at src/flb_engine.c:659
#5  0x555f6aab2cd2      in  flb_lib_worker() at src/flb_lib.c:493
#6  0x7fabe5165fa2      in  ???() at ???:0
#7  0x7fabe48464ce      in  ???() at ???:0
#8  0xffffffffffffffff  in  ???() at ???:0
```

The first errors are expected.

In addition to this problem there is another problem with the crc32 checksum. If the pod is being restarted, he tries to read the existing flb files but canot read them because the format check fails. This leads to an endless row of problems and fluentbit crashes again.

Important:
I treid to figure out what is the problem and therefore removed both filters for the kube.services.* logs. When removing those filters, fluentbit does not crash.

**Expected behavior**
I would expect fluentbit to not crash in case kafka is not available.

**Your Environment**
* Version used: 1.7
* Configuration: shown above
* Environment name and version (e.g. Kubernetes? What version?): kubernetes 1.19
* Server type and version: linux
* Filters and plugins: see above

**Additional context**

I cannot rely on fluentbit in case kafka is not available - in this scenario fluentbit tries to restart over and over again and due to the problem with the crc32 checksum, it wont be able to write any logs to kafka again even if kafka is available again.

**Comment by sunoce** [comment] 2021-02-15 16:38
Note: If I do not use crc32, the error does not accour - So the problem seems to be related to the fact, that fluentbit cant parse some existing files with the error: format check failed

**Comment by edsiper** [comment] 2021-02-16 23:27
thanks for opening the ticket.

Issue is reproducible: root cause: upon retry deletion there is a linked list corruption. 

```
[SERVICE]
    flush         1
    log_level     info
    storage.path  /tmp/flb-issue/

[INPUT]
    name          dummy
    rate          1000
    storage.type  filesystem

[OUTPUT]
    name          http
    match         *
    host          127.0.0.1
    port          3049     
    retry_limit   false
```

note: reproduced with slightly modification in the code that will fail every single retry:

```
[2021/02/16 17:25:30] [error] [engine_dispatch] could not retrieve chunk content, removing retry
#0  0x55a0840e7a6d      in  __mk_list_del() at lib/monkey/include/monkey/mk_core/mk_list.h:87
#1  0x55a0840e7aa4      in  mk_list_del() at lib/monkey/include/monkey/mk_core/mk_list.h:93
#2  0x55a0840e8668      in  flb_sched_request_destroy() at src/flb_scheduler.c:327
#3  0x55a0840e8824      in  flb_sched_event_handler() at src/flb_scheduler.c:407
#4  0x55a0840e4c4f      in  flb_engine_start() at src/flb_engine.c:659
#5  0x55a0840c753f      in  flb_lib_worker() at src/flb_lib.c:493
#6  0x7f590dcae58f      in  start_thread() at ps/nptl/futex-internal.h:463
#7  0x7f590d63d222      in  ???() at ???:0
#8  0xffffffffffffffff  in  ???() at ???:0
Aborted (core dumped)

```

**Comment by edsiper** [comment] 2021-02-17 00:36
Fixed in:

- 9443ce17 scheduler: validate return status of dispatch_retry (#3078)
- 3b1bff00 engine: dispatch: if output task fails on init, destroy retry (#3078)

**Comment by edsiper** [comment] 2021-02-17 00:37
Thanks again for reporting this, the issue has been finally solved. 

We will do v1.7.1 release with the fix shortly.

**Closed by edsiper** 2021-02-17 00:37 UTC
Labels: bug, fixed

**Comment by sunoce** [comment] 2021-02-26 12:47
Thank you for your fast response - I will try it as soon as I have time and comment again here!
