### ISSUE TITLE
Stream processor allow GROUP BY on other keys than selected

### ISSUE THREAD

**Issue by HansMeijer-AvidentIT** [fluent/fluent-bit#1669] opened 2019-10-20 14:19 UTC
**Is your feature request related to a problem? Please describe.**
When using stream processor we use it as an aggregate function, i.e.:
CREATE STREAM agg_stream WITH (tag='json_subkey') AS SELECT json_field1['description'], logtype, level, origin['hostname'], SUM(summary_field) from STREAM:in_data GROUP BY json_field1['description'], logtype, level, origin['hostname'];
Instead we would like it to support also doing GROUP BY on fields that are not in the SELECT clause and fields and also have fields in the SELECT clause that are not in the GROUP BY.

**Describe the solution you'd like**
Preferrably in the above scenario we would like it to support this sample:
CREATE STREAM agg_stream WITH (tag='json_subkey') AS SELECT json_field1['description'], logtype, level, origin['hostname'], userinfo['username'], SUM(summary_field) from STREAM:in_data GROUP BY json_field1['description'], level, origin['hostname'], origin['ip'];

**Describe alternatives you've considered**
We can add some fields using both modifier filters and record modifier, but they will not suffice.
**Additional context**
We are trying to do some aggregation of records that are basically the same but differs on some fields, and these we do not want to aggregate on since they will disallow the aggregation to function.

**Comment by koleini** [comment] 2019-11-22 01:07
duplicate of https://github.com/fluent/fluent-bit/issues/1754

**Closed by koleini** 2019-11-22 01:07 UTC
