### ISSUE TITLE
Invalid configuration value at INPUT.Name

### ISSUE THREAD

**Issue by ashramsey** [fluent/fluent-bit#226] opened 2017-04-05 08:59 UTC
Hey, I've updated from v0.10.0 to 0.11.0 and now get the following error:

```
ash$ fluent-bit -c fluentbit_rails_to_es.conf
Fluent-Bit v0.11.0
Copyright (C) Treasure Data

Invalid configuration value at INPUT.Name
Error: Configuration file contains format errors. Aborting
```

My conf:

```
[SERVICE]
    Flush 5
    Daemon  Off
    Log_Level debug
[INPUT]
    Name    tail
    Path    ganymede/log/development.log
[OUTPUT]
    Name  es
    Match *
    Host  aws
    Port  80
    Index passiphae
    Type  passenger
```

Is anyone else experiencing this? Can I provide more info?

My OS is OSX Sierra 10.12.3

Cheers

**Comment by edsiper** [comment] 2017-04-05 14:19
@ashramsey 

a format error in the configuration means your indentation level is wrong at the left side (likely you have a mix of spaces with tabs).

I did a copy/paste of your config in a new file and it worked properly:

```
$ ../../build/bin/fluent-bit -c flb.conf 
Fluent-Bit v0.11.1
Copyright (C) Treasure Data

[2017/04/05 08:17:49] [ info] [engine] started
```

please copy paste your config in a new file and also make sure to upgrade to the newer 0.11.1 version, let me know how it goes.

**Comment by nokute78** [comment] 2017-04-05 23:13
in_tail is supported only for linux now.

Note: see also #208

**Comment by edsiper** [comment] 2017-04-10 22:28
@ashramsey are you using a non-linux system ?

**Comment by edsiper** [comment] 2017-04-12 16:25
Closing this issue as a duplicate of #208.

**Closed by edsiper** 2017-04-12 16:25 UTC
