### ISSUE TITLE
Storage backlog chunk validation failure on restart in 2.1.X (data loss)

### ISSUE THREAD

**Issue by amorey** [fluent/fluent-bit#7279] opened 2023-04-27 06:48 UTC
## Bug Report

Fluent Bit restarts result in storage backlog chunk validation failures in version 2.1.X. 

**To Reproduce**

Here is a docker compose project that can be used to show the expected behavior in version 2.0.11 and the unexpected behavior in version 2.1.2:

https://github.com/amorey/flb-backlog-bug

- Example log message:

```
[2023/04/27 06:11:37] [ info] [input:storage_backlog:storage_backlog.1] register tcp.0/1-1682575884.551412366.flb
[2023/04/27 06:11:37] [error] [input:storage_backlog:storage_backlog.1] chunk validation failed, data might be corrupted. No valid records found, the chunk will be discarded.
[2023/04/27 06:11:37] [error] [input:storage_backlog:storage_backlog.1] removing chunk tcp.0:1-1682575884.551412366.flb from the queue
```

- Steps to reproduce the problem:

1. Send a message to Fluent Bit that results in a flush failure and creates a new pending task
2. Restart Fluent Bit

**Expected behavior**

On restart, previously pending tasks should be added to the storage backlog queue:

```
[2023/04/27 06:10:54] [ info] [input:storage_backlog:storage_backlog.1] register tcp.0/1-1682575828.625496799.flb
[2023/04/27 06:10:54] [ info] [input:storage_backlog:storage_backlog.1] queueing tcp.0:1-1682575828.625496799.flb
```

**Screenshots**

See https://github.com/amorey/flb-backlog-bug for log snippets.

**Your Environment**
* Version used: 2.1.2
* Configuration: https://raw.githubusercontent.com/amorey/flb-backlog-bug/main/config/fluent-bit.conf
* Environment name and version (e.g. Kubernetes? What version?): Docker Desktop 4.18.0
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

This bug will result in data loss on system restarts if tasks are pending.

**Comment by leonardo-albertovich** [comment] 2023-04-27 11:06
Thanks so much for the report and thorough reproduction job you made. 

I don't think I'll be able to look into it immediately but I'm saving this issue to take a look at it as soon as I have a bit of time if no one else did it yet.

Just to have something to think about in background meanwhile: 

1. Have you dumped the chunk file that 2.1 fails to process? In that case, is it empty or does it look truncated?
2. Is your host machine a mac? (I'm just asking to know if that's something that could affect it)
3. If the answer to the previous question is yes, have you tried your repro in x86?
4. When you restart the container with `docker restart`, does it do it gracefully? you did set a high enugh `grace` value thogh.
5. Have you tried setting `storage.sync` to `full`? (just a question, not a workaround)

Please don't misunderstand me, if you are running this in a mac (which means the container is running an aarch64 distro) and the repro doesn't work in x86 it doesn't change anything, I'm just asking these questions so whenever I can think about it in background and try to find any leads.

**Comment by amorey** [comment] 2023-04-27 12:36
Thanks for your quick response!

> 1. Have you dumped the chunk file that 2.1 fails to process? In that case, is it empty or does it look truncated?

Here's a file that 2.1 fails to process:
[1-1682597842.350529742.flb](https://www.dropbox.com/s/494uekf5978wxp3/1-1682597842.350529742.flb?dl=0) (71 bytes)

And for comparison, here's a file that 2.0 processes successfully:
[1-1682598013.120670254.flb](https://www.dropbox.com/s/7d3u00wgqgrrtqt/1-1682598013.120670254.flb?dl=0) (53 bytes)

> 2. Is your host machine a mac? (I'm just asking to know if that's something that could affect it)

Yes, but it's an Intel Mac.

> 3. If the answer to the previous question is yes, have you tried your repro in x86?

When I run `docker image inspect fluent/fluent-bit:2.1.2-debug` I see `"Architecture": "amd64", "Os": "linux"`.

> 4. When you restart the container with docker restart, does it do it gracefully? you did set a high enugh grace value thogh.

It appears to be stopping gracefully. For example, here's the end of the log output from 2.1 before restart:
```
[2023/04/27 12:17:44] [ info] [task] tcp/tcp.0 has 1 pending task(s):
[2023/04/27 12:17:44] [ info] [task]   task_id=0 still running on route(s): forward/forward.0 
[2023/04/27 12:17:44] [ info] [task] storage_backlog/storage_backlog.1 has 0 pending task(s):
[2023/04/27 12:17:44] [ info] [engine] service has stopped (1 pending tasks)
[2023/04/27 12:17:44] [ info] [input] pausing storage_backlog.1
[2023/04/27 12:17:44] [ info] [output:forward:forward.0] thread worker #0 stopping...
[2023/04/27 12:17:44] [ info] [output:forward:forward.0] thread worker #0 stopped
[2023/04/27 12:17:44] [ info] [output:forward:forward.0] thread worker #1 stopping...
[2023/04/27 12:17:44] [ info] [output:forward:forward.0] thread worker #1 stopped
```

> 5. Have you tried setting storage.sync to full? (just a question, not a workaround)

Yes, I've tried setting storage.sync to "full" (as well as storage.checksum to "On") and the behavior is the same.

**Comment by leonardo-albertovich** [comment] 2023-04-27 13:42
Outstanding! That's more than enough information.

I had a few minutes so I opened both files in a hex editor, compared them (the headers match) and also fed them through [this online msgpack decoder](https://msgpack.solder.party/) (starting at 0x1F) and I don't see anything wrong with the data structure there.

So I think there's probably something silly in chunkio, maybe an assumption about the data format. 
I'll feed that chunk you shared to the latest version as soon as I have a minute or two and see if it complains and get back to you.

**Comment by amorey** [comment] 2023-04-27 14:06
Great! Thanks for the quick triage. I'm curious to hear what the source of the problem is.

**Comment by leonardo-albertovich** [comment] 2023-04-28 07:29
The problem is that `flb_mp_validate_log_chunk` was not updated to use the log event abstraction layer which means it manually unpacks the msgpack buffer for each chunk in order to verify it but when it tries to verify the timestamp field it fails because in the new format it's wrapped by an array (effectively transforming it into "headers" rather than a raw timestamp) in order to include metadata as a gradual approach.

I think it's an important issue so I'll make sure I send a PR to fix it today and let @edsiper know so we can make a release as soon as possible.

If you are curious, the broken check is https://github.com/fluent/fluent-bit/blob/master/src/flb_mp.c#L170 and adding an additional option such as `ts.type != MSGPACK_OBJECT_ARRAY` would effectively mitigate the issue but wouldn't verify the integrity of the timestamp or metadata field so rather than rush the fix with that one liner I'll take the time necessary to properly update the function today.

**Comment by amorey** [comment] 2023-04-28 11:04
Great to hear you figured out the issue and are working on a fix! Thanks for the quick turnaround. Are there unit tests for `flb_mp_validate_log_chunk` and for chunk handling across restarts more generally?

**Comment by leonardo-albertovich** [comment] 2023-04-28 11:14
I didn't check that but I assume it's not the case, otherwise it would've been caught before the release.

I spent as much time as I could ensuring that the existing tests passed and then creating new external tests but completely missed this use case.

Once I fix it I'll check the tests and let you know.

**Comment by leonardo-albertovich** [comment] 2023-05-01 23:23
Hi @anosulchik, there is a PR for this issue that's about to be merged and I think there will be a release early this week.

**Comment by anosulchik** [comment] 2023-05-03 22:10
@leonardo-albertovich I'd like to confirm that fluentbit freshly compiled from master HEAD doesn't discard the chunks as empty and enqueues  them. How often are new versions are usually released?

**Comment by leonardo-albertovich** [comment] 2023-05-04 05:30
Thank you very much for taking the time to share your results. I don't know the exact ETA for the release but I think it will be sooner rather than later, hopefully within this week.

I'll send an update as soon as I have a proper ETA.

**Comment by amorey** [comment] 2023-05-23 05:56
@leonardo-albertovich Any updates on this? It looks like there have been a couple of releases since the PR was created.

**Comment by leonardo-albertovich** [comment] 2023-05-23 08:28
Hi @amorey, version [2.1.3](https://github.com/fluent/fluent-bit/releases/tag/v2.1.3) released 5 days ago includes this correction.

**Comment by leonardo-albertovich** [comment] 2023-05-23 15:54
Could you create an improvement request issue? that way we might be able to address it as time allows.

**Comment by amorey** [comment] 2023-05-24 05:53
No prob, I created a feature request issue here https://github.com/fluent/fluent-bit/issues/7465. Protection against data loss is one of the key features of Fluent Bit so please try to address this soon 🙏

**Comment by leonardo-albertovich** [comment] 2023-05-24 07:05
Thank you! I'm closing this issue now because fluent-bit 2.1.3 has been out for about a week and I don't want people to get confused by it.

**Closed by leonardo-albertovich** 2023-05-24 07:05 UTC
Labels: status: waiting-for-triage
