### ISSUE TITLE
Mem_Buf_Limit does not work with 'M' (megabytes) or 'G' (gigabytes)

### ISSUE THREAD

**Issue by wittenst** [fluent/fluent-bit#327] opened 2017-07-12 21:44 UTC
Tried setting the above for several Inputs where I would use 1M for 1 Megabyte, but the fluentbit process did not seem to recognize the number, and the Input would keep pausing because of a small buffer.  If I use 1000k or equivalent, that number is recognized

**Comment by nokute78** [comment] 2017-07-12 22:43
Could you try to add "B" to unit?
(e.g. 300MB 1GB)

The issue is related to #325

**Comment by wittenst** [comment] 2017-07-12 22:50
It looks like that made the difference, thank you.  Can the docs be updated with that info?

**Comment by nokute78** [comment] 2017-07-13 14:03
Thank you for checking.

In my opinion, it is useful to allow both format, "1MB" and "1M".

@edsiper How do you think?
If you agree, I will modify.

**Comment by wittenst** [comment] 2017-07-13 16:26
I'm fine with either format, I just need to make sure the documentation is correct

**Comment by edsiper** [comment] 2017-07-13 19:45
The unit size logic have been changed, changes will be reflected on:

- Fluent Bit 0.11.14 (to be released on Monday 17th)
- Fluent Bit 0.12

Documentation have been updated for 0.12 [here](http://fluentbit.io/documentation/0.12/configuration/unit_sizes.html) and for 0.11 series once 0,11.14 becomes released.

**Comment by edsiper** [comment] 2017-07-13 19:48
Closing this as Fixed. If you face any issue with the newer versions, we can reopen it.

**Closed by edsiper** 2017-07-13 19:48 UTC
Labels: bug, fixed
