### ISSUE TITLE
in_tail: already rotated files are processing from the beginning

### ISSUE THREAD

**Issue by mraczynska** [fluent/fluent-bit#1145] opened 2019-02-27 11:46 UTC
I am using fluent-bit to tail Docker logs with docker max-files option and input files pattern .log*
Sometimes, in fluent-bit debug logs I see that already rotated files are adding to scan queue and are processing from the beginning. It leads to a duplication of logs from docker container. 
I can change my input file pattern to .log (without .1, .2, .3 suffix) but in this case I can miss container logs while my app is running and I restart fluent-bit or it stops working.

This is my configuration file.
`[INPUT]`
`    Name   		tail`
`    Path        	/var/lib/docker/containers/*/*.log*`
`    Parser      	docker`
`    DB          	/var/fluentbit/logs.db`
`[OUTPUT]`
`    Name stdout`
`    Match *`

And this is part of debug logs:
`[2019/02/26 16:54:34] [debug] [task] created task=0x56136a909070 id=0 OK
[2019/02/26 16:54:35] [debug] [in_tail] removed /var/lib/docker/containers/447bd69e52eba702b933b126ac4056fde537697d30513506afc7a0e541ea6cf3/447bd69e52eba702b933b126ac4056fde537697d30513506afc7a0e541ea6cf3-json.log.2
[2019/02/26 16:54:35] [debug] [in_tail] rotated: /var/lib/docker/containers/447bd69e52eba702b933b126ac4056fde537697d30513506afc7a0e541ea6cf3/447bd69e52eba702b933b126ac4056fde537697d30513506afc7a0e541ea6cf3-json.log.1 -> /var/lib/docker/containers/447bd69e52eba702b933b126ac4056fde537697d30513506afc7a0e541ea6cf3/447bd69e52eba702b933b126ac4056fde537697d30513506afc7a0e541ea6cf3-json.log.2
[2019/02/26 16:54:35] [debug] [in_tail] scanning path /var/lib/docker/containers/*/*.log*
[2019/02/26 16:54:35] [debug] [in_tail] add to scan queue /var/lib/docker/containers/447bd69e52eba702b933b126ac4056fde537697d30513506afc7a0e541ea6cf3/447bd69e52eba702b933b126ac4056fde537697d30513506afc7a0e541ea6cf3-json.log.1, offset=0
[2019/02/26 16:54:35] [debug] [in_tail] rotated: /var/lib/docker/containers/447bd69e52eba702b933b126ac4056fde537697d30513506afc7a0e541ea6cf3/447bd69e52eba702b933b126ac4056fde537697d30513506afc7a0e541ea6cf3-json.log -> /var/lib/docker/containers/447bd69e52eba702b933b126ac4056fde537697d30513506afc7a0e541ea6cf3/447bd69e52eba702b933b126ac4056fde537697d30513506afc7a0e541ea6cf3-json.log.1
[2019/02/26 16:54:35] [debug] [in_tail] scanning path /var/lib/docker/containers/*/*.log*
[2019/02/26 16:54:35] [debug] [in_tail] add to scan queue /var/lib/docker/containers/447bd69e52eba702b933b126ac4056fde537697d30513506afc7a0e541ea6cf3/447bd69e52eba702b933b126ac4056fde537697d30513506afc7a0e541ea6cf3-json.log, offset=0
[2019/02/26 16:54:35] [debug] [in_tail] file=/var/lib/docker/containers/447bd69e52eba702b933b126ac4056fde537697d30513506afc7a0e541ea6cf3/447bd69e52eba702b933b126ac4056fde537697d30513506afc7a0e541ea6cf3-json.log promote to TAIL_EVENT
[2019/02/26 16:54:35] [debug] [in_tail] file=/var/lib/docker/containers/447bd69e52eba702b933b126ac4056fde537697d30513506afc7a0e541ea6cf3/447bd69e52eba702b933b126ac4056fde537697d30513506afc7a0e541ea6cf3-json.log.1 promote to TAIL_EVENT
[2019/02/26 16:54:39] [debug] [task] created task=0x56136a9092d0 id=0 OK`

Have you any suggestions for pattern which should I use and how can above problems be solved?

**Comment by edsiper** [comment] 2019-03-25 21:38
Hi, 

As you stated the problem is here in the configuration:

```
Path /var/lib/docker/containers/*/*.log*
```

you are telling Fluent Bit to process all rotated files due to file match file.log.1 .. file.log.N. That's expected behavior, but not expected config. 

If you are missing containers logs for some reason, we should track that specific issue independently, if you have a reproducible test case I will be happy to troubleshoot and find a solution.

For now, I am closing this issue, please open a new one to track the problem described of missed logs.

**Closed by edsiper** 2019-03-25 21:38 UTC
Labels: not-an-issue
