### ISSUE TITLE
Getting "Error: Invalid coroutine stack size" ever Coro_Stack_Size=24576

### ISSUE THREAD

**Issue by P-A-R-U-S** [fluent/fluent-bit#1315] opened 2019-05-06 23:51 UTC
## Error: Getting "Error: Invalid coroutine stack size" ever Coro_Stack_Size=24576

**Describe the bug**
Trying to run fluent-but in verbose mode **/opt/fluent-bit/fluent-bit-1.0.6/build/bin/fluent-bit -v** and getting following error below. Looks like coroutine stack need to be increased, but I"m already have Coro_Stack_Size=24576 based on documentation: https://docs.fluentbit.io/manual/configuration/file#config_section

**Expected behavior**
Show verbose info.

**Screenshots**
<img width="963" alt="Screen Shot 2019-05-06 at 4 26 37 PM" src="https://user-images.githubusercontent.com/1575452/57261347-445f4400-701c-11e9-8107-9797c5a0f1f9.png">
<img width="687" alt="Screen Shot 2019-05-06 at 4 25 24 PM" src="https://user-images.githubusercontent.com/1575452/57262997-ac655880-7023-11e9-8182-0eda640612a1.png">

**Comment by edsiper** [comment] 2019-06-13 18:18
I was not able to reproduce the problem, I tried:

- v1.0.6
- v1.1.2
- GIT master (1.2)

are you still facing the issue ?, are you running it on Linux or MacOS ?

**Comment by edsiper** [comment] 2019-07-16 10:01
if you can reproduce the issue let me know so we can reopen this ticket. closing for now.

**Closed by edsiper** 2019-07-16 10:01 UTC
Labels: timeout, waiting-for-user

**Comment by parker20121** [comment] 2019-07-31 02:13
I installed fluent-bit on an Alpine docker image, and got the same error when I tried to start it with fluent-bit -v. Once I pointed it to the configuration file using the -c flag, everything worked fine.

**Comment by edsiper** [comment] 2019-07-31 02:50
fyi: Alpine (musl) is not supported.
