### ISSUE TITLE
in_tail does not track container logs after rotation by dockerd

### ISSUE THREAD

**Issue by zette** [fluent/fluent-bit#287] opened 2017-06-01 14:23 UTC
fluent-bit: 0.11.7 (https://github.com/fluent/fluent-bit-docker-image/tree/master/0.11) - running in container with /var/lib/docker/containers attached as volume
docker: 17.04.0-ce
OS: CentOS Linux 7

fluent-bit config:

```
[SERVICE]
    Flush        2
    Daemon       Off
    Log_Level    info
    Log_File     /fluent-bit/log/fluent-bit.log
    Parsers_File parsers.conf

[INPUT]
    Name tail
    path /docker/**/*.log
    DB /var/log/fluentd-docker.db
    Mem_Buf_Limit 20MB
    Parser docker

[OUTPUT]
    Name forward
    Match *
    Host xxx
    Port 24224
```

Docker running with default JSON log driver, and enable log file rotation every 100MB: --log-opt max-size=100m

It seems that fluent-bin in_tail looses track of log file, after ther log file gets rotated. It does seem not happen every rotation, so it is a little bit harder to catch, but often enough to be a dealbreaker. With my system it is like about every hour or so.
After that event I need to manually remove fluent-bit DB file and restart it.

**Comment by edsiper** [comment] 2017-06-13 22:38
I've tried to replicate the problem with the following steps:

1: Create a container that prints logs without stop:

```
FROM ubuntu

RUN echo '-c i=0; while true; do echo "bbbbbbbbbbbbbbbbbbbCCCCCCCCCCCCCCC"; done' > /bootstrap.sh
RUN chmod +x /bootstrap.sh

CMD /bootstrap.sh
```

2. Build and Start the container:

```
$ docker build -t bug_287 ubuntu
$ docker run --log-driver json-file --log-opt max-size=10m bug_287
```

3. Watch log file generated:

- Logs path /var/lib/docker/containers/c8c80c9ffcd5497de5e6534683d88e594f0d69647bfc7d0bbf2da40032a7ba23
- Log file:
c8c80c9ffcd5497de5e6534683d88e594f0d69647bfc7d0bbf2da40032a7ba23-json.log

Stat the log file (first):

```
File: c8c80c9ffcd5497de5e6534683d88e594f0d69647bfc7d0bbf2da40032a7ba23-json.log
Size: 7945406   	Blocks: 15520      IO Block: 4096   regular file
Device: 804h/2052d	Inode: 24519130    Links: 1
Access: (0640/-rw-r-----)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-06-13 16:22:51.816324133 -0600
Modify: 2017-06-13 16:30:14.649543046 -0600
Change: 2017-06-13 16:30:14.649543046 -0600
 Birth: -
```

Stat the log file, second time:

```
File: c8c80c9ffcd5497de5e6534683d88e594f0d69647bfc7d0bbf2da40032a7ba23-json.log
Size: 6542785   	Blocks: 12784      IO Block: 4096   regular file
Device: 804h/2052d	Inode: 24519130    Links: 1
Access: (0640/-rw-r-----)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-06-13 16:22:51.816324133 -0600
Modify: 2017-06-13 16:30:16.509612298 -0600
Change: 2017-06-13 16:30:16.509612298 -0600
 Birth: -
```

As you can see there is no "rotation" as it sounds, what Docker is doing is overriding the log file content once it reach it limit and start from zero, this mode in log-rotation context is called "copy truncate". There is no new file generated and file Inode keeps the same.

Using this setup is almost impossible to detect a rotation because:

- there is no new file generated
- Docker just truncate and wrtite from position zero

For this case I'd suggest you setup logrotate tool and let it take care of rotation where rotated files are renamed and new logs comes to a new file with a different inode.

**Comment by edsiper** [comment] 2017-06-14 02:00
Update

I've found that if you append the max-file option the files will be rotated, that option defines how many rotated files will be created, e.g:

```
docker run --log-driver json-file --log-opt max-size=10m --log-opt max-file=5 bug_287
```

please re-try with that option and send us some feedback.

**Comment by edsiper** [comment] 2017-06-15 17:45
@zette did you were able to reproduce the problem after the changes suggested ?

**Comment by zette** [comment] 2017-06-16 18:19
I'll check it on monday. 
One strange thing is that fluend tail input plugin works with current setup without problems, and fluent-bit has problems.

**Comment by edsiper** [comment] 2017-06-16 18:38
are you using the  __--log-opt max-file X__ option?

**Comment by zette** [comment] 2017-06-16 18:52
I recall that I'm using both --log-opt max-size and --log-opt max-file. But I do not have remote access to that env right now. I'll let You know on monday, when I get to office.

**Comment by zette** [comment] 2017-06-20 07:15
On dev environment I'm using only --log-opt max-size option.
But as mentioned earlier it is working just fine with "big" fluentd forwarder.

**Comment by edsiper** [comment] 2017-06-20 17:45
@zette I am trying to reproduce the problem, one question: what's your average number of lines generated per second ?

**Comment by zette** [comment] 2017-06-21 13:04
Not more that 20/s in idle.

**Comment by edsiper** [comment] 2017-06-21 14:39
I've found a problem when files are rotated, still troubleshooting...

**Comment by edsiper** [comment] 2017-06-23 22:45
Issue have been fixed in 0.11.10 release. 

Docker images have been updated. Please use 0.11.10 Docker image.

note: if the issue persist in your environment, feel free to request to re-open this issue, closing for now.

Fixed.

**Closed by edsiper** 2017-06-23 22:45 UTC
Labels: bug

**Comment by ayushmathur86** [comment] 2018-05-02 10:44
Hi @edsiper , I'm facing the same issue eventhough the following configuration is present for docker log file rotation:
```--log-driver=json-file --log-opt max-size=2G --log-opt max-file=10
I can see multiple files being generated, i.e. log files are being rotated once they hit 2G size mark, but fluentd is still reading the main file (*-json.log) and not the others (*log.1, .2, etc).

**Comment by yusufgungor** [comment] 2020-04-26 20:41
Hi, we are having a really strange sitution. some of our container log files "read from head" randomly and we could not find the reason. Pos file seems like this:

`/var/log/containers/ourApplication-7f59799d7d-dl72n_ourNamespace_ourApplication-container-c01fe8f43d78c8b471dd61267cf8888612f5011ed9bd1c3c7f736b98af320f0b.log   ffffffffffffffff    00000000004f06ad
/var/log/containers/ourApplication-7f59799d7d-dl72n_ourNamespace_ourApplication-container-c01fe8f43d78c8b471dd61267cf8888612f5011ed9bd1c3c7f736b98af320f0b.log   ffffffffffffffff    00000000004f06ad
/var/log/containers/ourApplication-7f59799d7d-dl72n_ourNamespace_ourApplication-container-c01fe8f43d78c8b471dd61267cf8888612f5011ed9bd1c3c7f736b98af320f0b.log   ffffffffffffffff    00000000004f06ad
/var/log/containers/ourApplication-7f59799d7d-dl72n_ourNamespace_ourApplication-container-c01fe8f43d78c8b471dd61267cf8888612f5011ed9bd1c3c7f736b98af320f0b.log   0000000002a9d174    00000000004f06ad `

Do you have any idea? This occures at random intervals between 5-30 minutes and cause to multiplexed logs in elasticsearch.

`2020-04-26 19:19:28 +0000 [debug]: [faraday-containers.log] tailing paths: target = /var/log/containers/ourApplication-7f59799d7d-dl72n_ourNamespace_ourApplication-container-c01fe8f43d78c8b471dd61267cf8888612f5011ed9bd1c3c7f736b98af320f0b.log | existing = /var/log/containers/ourApplication-7f59799d7d-dl72n_ourNamespace_ourApplication-container-c01fe8f43d78c8b471dd61267cf8888612f5011ed9bd1c3c7f736b98af320f0b.log`

Fluentd in_tail logs shows that, same log file is tailing again even it also exist on "existing" list.

Docker rotation config is as below: 
/etc/docker/daemon.json
`{
  "live-restore": true,
  "log-driver": "json-file",
  "log-opts":  {
     "max-size": "50m",
     "max-file": "5"
  }
}`
