### ISSUE TITLE
Error  when storing logs into influxdb

### ISSUE THREAD

**Issue by jenningsloy318** [fluent/fluent-bit#376] opened 2017-09-13 09:08 UTC
I have configured fluentbit to send  journald logs  `/var/log/journal`into influxdb,  for `show series`, I can see many series stored in influxdb. 
```
#show series
docker.service,seq=99962
docker.service,seq=99963
docker.service,seq=99964
docker.service,seq=99965
docker.service,seq=99966
docker.service,seq=99967
docker.service,seq=99968
docker.service,seq=99969
docker.service,seq=9997
docker.service,seq=99970
docker.service,seq=99971
docker.service,seq=99972
docker.service,seq=99973
docker.service,seq=99974
docker.service,seq=99975
docker.service,seq=99976
docker.service,seq=99977
docker.service,seq=99978
docker.service,seq=99979
docker.service,seq=9998
docker.service,seq=99980
docker.service,seq=99981
docker.service,seq=99982
docker.service,seq=99983
docker.service,seq=99984
docker.service,seq=99985
docker.service,seq=99986
docker.service,seq=99987
docker.service,seq=99988
docker.service,seq=99989
docker.service,seq=9999
docker.service,seq=99990
docker.service,seq=99991
docker.service,seq=99992
docker.service,seq=99994
docker.service,seq=99995
docker.service,seq=99996
docker.service,seq=99997
docker.service,seq=99998
```
but `select * from docker.service` show nothing.

when I swith the output plugin to `stdout`, one entry of the output is listed as below:

```
[698] docker.service: [1504098388.000000245, {"_PID"=>"3436", "_UID"=>"0", "_GID"=>"0", "_COMM"=>"dockerd", "_EXE"=>"/usr/bin/dockerd", "_CMDLINE"=>"/usr/bin/dockerd", "_CAP_EFFECTIVE"=>"3fffffffff", "_SYSTEMD_CGROUP"=>"/kubesvc.slice/docker.service", "_SYSTEMD_UNIT"=>"docker.service", "_SYSTEMD_SLICE"=>"kubesvc.slice", "_BOOT_ID"=>"78db3cbd30cb4c0f9b08b52244d6f88f", "_MACHINE_ID"=>"94b52f20059d43be9b0055ffbd24b4e6", "_HOSTNAME"=>"cnpvgl56588417", "_TRANSPORT"=>"journal", "PRIORITY"=>"3", "CONTAINER_ID"=>"cc2bc7c29909", "CONTAINER_ID_FULL"=>"cc2bc7c299099e528d13e11dc8a06e27976e4d1504ba6d65d5acf68367afcf51", "CONTAINER_NAME"=>"k8s_kube-controller-manager_kube-controller-manager-cnpvgl56588417_default_def610e34b855dc0cce42a2ade3e9e6e_14", "CONTAINER_TAG"=>"docker_k8s_kube-controller-manager_kube-controller-manager-cnpvgl56588417_default_def610e34b855dc0cce42a2ade3e9e6e_14_cc2bc7c29909", "MESSAGE"=>"I0830 13:06:28.220045       7 pv_controller.go:393] synchronizing bound PersistentVolumeClaim[monitoring/gf-data-pvc]: volume "pvc-90cf6943-7733-11e7-b22d-30e1715dbd38" found: phase: Bound, bound to: "monitoring/gf-data-pvc (uid: 90cf6943-7733-11e7-b22d-30e1715dbd38)", boundByController: false", "_SOURCE_REALTIME_TIMESTAMP"=>"1504098388220175", "kubernetes"=>{"name_prefix"=>"k8s", "container_name"=>"kube-apiserver", "container_hash"=>"", "pod_name"=>"kube-apiserver-cnpvgl56588417", "namespace_name"=>"default", "pod_id"=>"ffe3f78a-8a11-11e7-8c91-30e1715dbd38", "annotations"=>{"kubernetes.io/config.hash"=>"1b48952c3f142f764e689390a14f494f", "kubernetes.io/config.mirror"=>"1b48952c3f142f764e689390a14f494f", "kubernetes.io/config.seen"=>"2017-08-26T11:52:31.829026005+08:00", "kubernetes.io/config.source"=>"file"}, "host"=>"cnpvgl56588417"}}]
```
Seems there is somthing wrong when fluent-bit storing the logs into influxdb? 

total conf of fluent-bit:
```
Fluent Bit Enterprise - SOS Report
==================================
The following report aims to be used by Fluent Bit and Fluentd Enterprise
Customers of Treasure Data. For more details visit:
    https://fluentd.treasuredata.com
[Fluent Bit]
    Edition             Community Edition
    Version             0.12.0
    Built Flags          JSMN_PARENT_LINKS JSMN_STRICT FLB_HAVE_TLS FLB_HAVE_SQLDB FLB_HAVE_BUFFERING FLB_HAVE_TRACE FLB_HAVE_FLUSH_LIBCO FLB_HAVE_SYSTEMD FLB_HAVE_FORK FLB_HAVE_PROXY_GO FLB_HAVE_JEMALLOC JEMALLOC_MANGLE FLB_HAVE_REGEX FLB_HAVE_C_TLS FLB_HAVE_SETJMP FLB_HAVE_ACCEPT4 FLB_HAVE_INOTIFY
[Operating System]
    Name                Linux
    Release             4.8.0-49-lowlatency
    Version             #52~16.04.1-Ubuntu SMP PREEMPT Thu Apr 20 11:58:08 UTC 2017
[Hardware]
    Architecture        x86_64
    Processors          32
[Built Plugins]
    Inputs              cpu mem kmsg tail proc disk systemd netif dummy head health serial stdin tcp mqtt lib forward random syslog
    Filters             grep stdout kubernetes parser record_modifier
    Outputs             counter es exit file forward http influxdb kafka-rest nats null plot stdout td lib flowcounter
[SERVER] Runtime configuration
    Flush               1
    Daemon              Off
    Log_Level           Trace
[INPUT] Instance
    Name                systemd.0 (systemd, id=0)
    Flags               DYN_TAG
    Threaded            No
    Tag                 *
    Max_Entries         500
    Path                /var/log/journal
    Systemd_Filter      _SYSTEMD_UNIT=docker.service
    Systemd_Filter      _TRANSPORT=journal
    DB                  /fluent-bit/db/journald.db
[FILTER] Instance
    Name                kubernetes.0 (kubernetes, id=0)
    Match               *
    Kube_URL            https://kubernetes.default.svc:443
    use_journal         On
    Merge_JSON_Log      On
[OUTPUT] Instance
    Name                influxdb.0 (influxdb, mask_id=1)
    Match               *
    TLS Active          No
    Retry Limit         1
    Host.TCP_Port       8086
    Host.Name           10.58.137.244
    Database            k8slog
    Sequence_Tag        seq
```

**Comment by edsiper** [comment] 2017-09-13 22:22
would you please try the following from the command line and write back the output:

```
bin/fluent-bit -i systemd -p Sytemd_Filter=_SYSTEMD_UNIT=docker.service -o counter -f 1
```

**Comment by jenningsloy318** [comment] 2017-09-14 05:04
Hi @edsiper 
Here is the output:
```
Fluent-Bit v0.12.1
Copyright (C) Treasure Data

[2017/09/14 13:03:56] [ info] [engine] started
1505365437.238896,2147 (total = 2147)
1505365437.240245,2163 (total = 4310)
1505365437.241873,2165 (total = 6475)
1505365437.243127,2153 (total = 8628)
1505365437.244366,2124 (total = 10752)
1505365437.245963,2164 (total = 12916)
1505365437.247208,2141 (total = 15057)
1505365437.248949,2164 (total = 17221)
1505365437.250969,2153 (total = 19374)
1505365437.253635,2146 (total = 21520)
1505365437.254924,2150 (total = 23670)
1505365437.256183,2155 (total = 25825)
1505365437.257755,2147 (total = 27972)
1505365437.259602,2169 (total = 30141)
1505365438.347879,2132 (total = 32273)
1505365438.350036,2157 (total = 34430)
1505365438.352202,2208 (total = 36638)
1505365438.354118,2213 (total = 38851)
1505365438.356042,2184 (total = 41035)
1505365438.357917,2209 (total = 43244)
1505365438.360242,2207 (total = 45451)
1505365438.362102,2186 (total = 47637)
1505365438.364004,2190 (total = 49827)
1505365438.366140,2167 (total = 51994)
1505365438.367887,2182 (total = 54176)
1505365438.369975,2193 (total = 56369)
1505365438.371676,2186 (total = 58555)
```

**Comment by edsiper** [comment] 2017-09-18 22:06
@jenningsloy318 in version 0.12.1 there is a problem when defining multiple filters on systemd plugin, would you please test 0.12.2 since that one comes with the fix ?

**Comment by jenningsloy318** [comment] 2017-09-21 05:49
@edsiper  after upgrading to 0.12.2, still no output when executing `select * from docker.service`.

and also more measrements are found, but the conf  is not changed.

```
> show measurements
name: measurements
------------------
name
docker.service
init.scope

>
```

**Comment by edsiper** [comment] 2017-09-21 17:37
@jenningsloy318 

I've found the problem is that our plugin (out_influxdb) is not quoting text properly leading to a broken protocol format. 

I will try to sort this out for 0.12.4 release (0.12.3 is out this week)

**Comment by jenningsloy318** [comment] 2017-09-22 01:38
@edsiper  Thank you so much for your effort.  waiting for the 0.12.4 release.

**Comment by jenningsloy318** [comment] 2017-10-07 07:54
@edsiper ,

Can you estimate when this bug will be fixed?

**Comment by edsiper** [comment] 2017-10-09 17:57
@jenningsloy318 

It's just fixed on [0.12 branch](https://github.com/fluent/fluent-bit/tree/0.12). 

I am planning to release Fluent Bit 0.12.6 at the end of the week, for now if you can try the 0.12 branch would be helpful. Let me know how it goes.

**Comment by jenningsloy318** [comment] 2017-10-12 03:30
hi @edsiper 

I sitll got no luck. I use 0.12.5 image from dockerhub.  I can see the logs with http error:
```
[2017/10/12 11:26:45] [debug] [out_influxdb] http_do=0 http_status=400
```

and  `select * from docker.service` show nothing.

Did you have tested this already?  not sure if I have something  wrong in the configuration.

**Comment by edsiper** [comment] 2017-10-12 03:57
@jenningsloy318 

the changes are on GIT Master (source code), I will try to provide you a test image shortly.

**Comment by edsiper** [comment] 2017-10-13 22:46
I've just released [Fluent Bit v0.12.6](http://fluentbit.io/announcements/v0.12.6/) which contains the changes for this issue.

You can try the newest docker image fluent/fluent-bit:0.12.6

**Comment by jenningsloy318** [comment] 2017-10-14 07:15
@edsiper

I am  testing v0.12.6, but still got no luck. still nothing appears when executing `select * from docker.service`. not sure if I need to adjust my conf 
```
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    trace
    [INPUT]
        Name           systemd
        Max_Entries     500
        Tag             *
        Path           /var/log/journal
        Systemd_Filter  _SYSTEMD_UNIT=docker.service
        DB              /fluent-bit/journald.db
    [FILTER]
        Name            kubernetes
        Kube_URL        https://kubernetes.default.svc:443
        Match           *
        use_journal     On



    [OUTPUT]
        Name          influxdb
        Match         *
        Host          influx-host
        Port          8086
        Database      k8slog
        Sequence_Tag  seq

```


from the error message: 
```
[2017/10/14 15:11:49] [debug] [out_influxdb] http_do=0 http_status=204
```

**Comment by edsiper** [comment] 2017-10-14 07:28
If you get HTTP status 204 means it was OK, no errors.

On Oct 14, 2017 01:15, "jenningsloy318" <notifications@github.com> wrote:

@edsiper <https://github.com/edsiper>

I am testing v0.12.6, but still got no luck. still nothing appears when
executing select * from docker.service. not sure if I need to adjust my conf

    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    trace
    [INPUT]
        Name           systemd
        Max_Entries     500
        Tag             *
        Path           /var/log/journal
        Systemd_Filter  _SYSTEMD_UNIT=docker.service
        DB              /fluent-bit/journald.db
    [FILTER]
        Name            kubernetes
        Kube_URL        https://kubernetes.default.svc:443
        Match           *
        use_journal     On



    [OUTPUT]
        Name          influxdb
        Match         *
        Host          influx-host
        Port          8086
        Database      k8slog
        Sequence_Tag  seq


from the error message:

[2017/10/14 15:11:49] [debug] [out_influxdb] http_do=0 http_status=204

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fluent/fluent-bit/issues/376#issuecomment-336616311>,
or mute the thread

**Comment by jenningsloy318** [comment] 2017-10-14 07:46
@edsiper  I see what I am missing, now I can see the content.

```
name: docker.service
--------------------
time                    CONTAINER_ID    CONTAINER_ID_FULL                                                       CONTAINER_NAME                                                                                  CONTAINER_TAG                                                                                                            MESSAGE                                                                                                                                                                          PRIORITY        SYSLOG_FACILITY SYSLOG_IDENTIFIER       _BOOT_ID                                _CAP_EFFECTIVE  _CMDLINE         _COMM   _EXE                    _GID    _HOSTNAME       _MACHINE_ID                             _PID    _SOURCE_REALTIME_TIMESTAMP      _SYSTEMD_CGROUP                 _SYSTEMD_SLICE  _SYSTEMD_UNIT   _TRANSPORT       _UID    seq
1507921562000000706     ec62bc5f4076    ec62bc5f40761e0339959cf35952d67be8aa6092249f67572c3470569c198558        k8s_kube-apiserver_kube-apiserver-cnpvgl56588417_default_1b48952c3f142f764e689390a14f494f_22    docker_k8s_kube-apiserver_kube-apiserver-cnpvgl56588417_default_1b48952c3f142f764e689390a14f494f_22_ec62bc5f4076 I1013 19:06:02.706230       7 handler.go:150] kube-apiserver: PUT "/api/v1/namespaces/kube-system/endpoints/kube-controller-manager" satisfied by gorestful with webservice /api/v1      3                                                       82d9803b203e497394a10707c7872c7c        3fffffffff      /usr/bin/dockerd dockerd /usr/bin/dockerd        0       cnpvgl56588417  94b52f20059d43be9b0055ffbd24b4e6        2873    1507921562706482                /kubesvc.slice/docker.service   kubesvc.slice   docker.service  journal          0       1
```

Thanks

**Comment by jenningsloy318** [comment] 2017-10-14 08:18
@edsiper 

from the logs, I don't see the pod/k8s related labels, is there anything wrong ?

**Comment by edsiper** [comment] 2017-10-14 15:32
I am not sure if Influxdb supports nested records/maps, I will do some research to figure out how to fix it.

**Closed** 2019-04-03 23:06 UTC
Labels: bug, fixed
