### ISSUE TITLE
logfmt does not preserve time when Time_Keep=On

### ISSUE THREAD

**Issue by LionelCons** [fluent/fluent-bit#2311] opened 2020-06-30 14:15 UTC
When defining a parser filter using the `logfmt` parser, the `Time_Keep` option is ignored.

This can be seen in https://github.com/fluent/fluent-bit/blob/master/src/flb_parser_logfmt.c. `time_lookup` is initialised to the current time regardless of whether `Time_Keep` is true or false. `time_lookup` can only change if the time key is found.

(tested on v1.4.6 but the bug seems to be in master too)

**Comment by edsiper** [comment] 2020-08-03 18:43
I cannot reproduce the issue, I tried the following test:

test.log 

```
baseUrl="/" route=getName hostname=localhost protocol=http name=matthew time=1196479815
baseUrl="/" route=getName hostname=localhost protocol=http name=james
```

parsers.conf

```
[PARSER]
    name        bug
    format      logfmt
    time_key    time
    time_format %s
    time_keep   false
```

## test with time_keep false

```
$ fluent-bit -R parsers.conf -i tail -p path=test.log -p parser=bug -o stdout -f 1
Fluent Bit v1.6.0
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2020/08/03 12:41:59] [ info] [engine] started (pid=1529594)
[2020/08/03 12:41:59] [ info] [storage] version=1.0.5, initializing...
[2020/08/03 12:41:59] [ info] [storage] in-memory
[2020/08/03 12:41:59] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/08/03 12:41:59] [ info] [sp] stream processor started
[2020/08/03 12:41:59] [ info] inotify_fs_add(): inode=16517071 watch_fd=1 name=test.log
[0] tail.0: [1196458215.000000000, {"baseUrl"=>"/", "route"=>"getName", "hostname"=>"localhost", "protocol"=>"http", "name"=>"matthew"}]
[1] tail.0: [1596480119.000000000, {"baseUrl"=>"/", "route"=>"getName", "hostname"=>"localhost", "protocol"=>"http", "name"=>"james"}]
```

## test with time_keep true

```
fluent-bit -R parsers.conf -i tail -p path=test.log -p parser=bug -o stdout -f 1
Fluent Bit v1.6.0
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2020/08/03 12:42:56] [ info] [engine] started (pid=1529991)
[2020/08/03 12:42:56] [ info] [storage] version=1.0.5, initializing...
[2020/08/03 12:42:56] [ info] [storage] in-memory
[2020/08/03 12:42:56] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/08/03 12:42:56] [ info] [sp] stream processor started
[2020/08/03 12:42:56] [ info] inotify_fs_add(): inode=16517071 watch_fd=1 name=test.log
[0] tail.0: [1196458215.000000000, {"baseUrl"=>"/", "route"=>"getName", "hostname"=>"localhost", "protocol"=>"http", "name"=>"matthew", "time"=>"1196479815"}]
[1] tail.0: [1596480176.000000000, {"baseUrl"=>"/", "route"=>"getName", "hostname"=>"localhost", "protocol"=>"http", "name"=>"james"}]
```

**Comment by LionelCons** [comment] 2020-08-04 06:58
In my use case, the parsing is done in two stages: first one to extract the time (`regex`) and second one to break down the fields (`logfmt`).

Here is how to reproduce the problem as I saw it.

```
1196479815 baseUrl="/" route=getName hostname=localhost protocol=http name=matthew
1196479816 baseUrl="/" route=getName hostname=localhost protocol=http name=james
```

```
[PARSER]
    Name         parser1
    Format       regex
    Regex        ^(?<time>\d+)\s+(?<raw>.+)$
    Time_Key     time
    Time_Format  %s

[PARSER]
    Name         parser2
    Format       logfmt
    Time_Keep    true
```

```
[INPUT]
    Name   tail
    Tag    bug
    Path   test.log
    Parser parser1

[FILTER]
    Name     parser
    Match    bug
    Parser   parser2
    Key_Name raw
```

`parser1` works fine and at this stage the time is correct. If I only use it I get:
```
[0] bug: [1196483415.000000000, {"raw"=>"baseUrl="/" route=getName hostname=localhost protocol=http name=matthew"}]
[1] bug: [1196483416.000000000, {"raw"=>"baseUrl="/" route=getName hostname=localhost protocol=http name=james"}]
```

`parser2` breaks down the fields but does not preserve the time. When I use it after `parser1` I get:
```
[0] bug: [1596524200.000000000, {"baseUrl"=>"/", "route"=>"getName", "hostname"=>"localhost", "protocol"=>"http", "name"=>"matthew"}]
[1] bug: [1596524200.000000000, {"baseUrl"=>"/", "route"=>"getName", "hostname"=>"localhost", "protocol"=>"http", "name"=>"james"}]
```

**Comment by edsiper** [comment] 2020-08-04 19:17
@LionelCons thanks for clarifying.

I've addressed the issue in GIT master and I will backport the changes to 1.5. Please test GIT master.

```
$ ../../build/bin/fluent-bit -c conf 
Fluent Bit v1.6.0
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2020/08/04 13:16:10] [ info] [engine] started (pid=50579)
[2020/08/04 13:16:10] [ info] [storage] version=1.0.5, initializing...
[2020/08/04 13:16:10] [ info] [storage] in-memory
[2020/08/04 13:16:10] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/08/04 13:16:10] [ info] [sp] stream processor started
[2020/08/04 13:16:10] [ info] inotify_fs_add(): inode=16517071 watch_fd=1 name=test.log
[0] bug: [1196458215.000000000, {"baseUrl"=>"/", "route"=>"getName", "hostname"=>"localhost", "protocol"=>"http", "name"=>"matthew"}]
[1] bug: [1196458216.000000000, {"baseUrl"=>"/", "route"=>"getName", "hostname"=>"localhost", "protocol"=>"http", "name"=>"james"}]
```

note: the remaining part is the strptime(3) required fix. but is not associated to this issue.

**Comment by LionelCons** [comment] 2020-08-05 07:14
I have tested master and I confirm that this bug is now fixed. Thanks!

**Comment by edsiper** [comment] 2020-08-05 14:46
thanks, closing.

**Closed by edsiper** 2020-08-05 14:46 UTC
Labels: bug, fixed
