### ISSUE TITLE
input "head" fails to upload to elasticsearch due to special characters

### ISSUE THREAD

**Issue by mahdi-asadpour-rr** [fluent/fluent-bit#294] opened 2017-06-15 12:44 UTC
For the input type of "head", uploading to the elasticsearch fails because: the corresponding value field (precisely, head_config->buf) contains new line characters which are not accepted as valid json by the elasticsearch server (error: [debug] [out_es] HTTP Status=500). The solution is to escape special characters, e.g. `\x0a` --> `\\x0a`.

**Comment by nokute78** [comment] 2017-06-15 13:59
@mahdi-asadpour-rr Thank you for reporting.
I updated in_head and it will work like "$ head -n" and each records don't contain '\n'.
Could you check #295 ?

**Comment by edsiper** [comment] 2017-06-15 15:29
I could reproduce the problem, the error from Elasticsearch is:

```
HTTP/1.1 500 Internal Server Error
content-type: application/json; charset=UTF-8
content-length: 463

{"error":{"root_cause":[{"type":"json_parse_exception","reason":"Unrecognized token 'MemFree': was expecting ('true', 'false' or 'null')\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@4426b361; line: 1, column: 9]"}],"type":"json_parse_exception","reason":"Unrecognized token 'MemFree': was expecting ('true', 'false' or 'null')\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@4426b361; line: 1, column: 9]"},"status":500}
```

I suspect the problem is on msgpack2json routine.

**Comment by mahdi-asadpour-rr** [comment] 2017-06-15 15:49
@nokute78 Thank you for the change. I can confirm that with your changes I don't see that error again (i.e., [out_es] HTTP Status=200) and the index is created in the elasticsearch server. But the problem is the number of entries in that index is 0, meaning that no "head" entry is added, which might need a separate bug report!

**Comment by edsiper** [comment] 2017-06-15 15:52
@mahdi-asadpour-rr looks like the thing is: if a packaged string contains a \n, the output json (decoded from msgpack) becomes invalid

**Comment by mahdi-asadpour-rr** [comment] 2017-06-15 16:30
@edsiper correct, but with changes made by @nokute78 the record doesn't contain \n anymore. Still, some other part of the output json might not be valid though.

**Comment by edsiper** [comment] 2017-06-15 18:55
@mahdi-asadpour-rr I have pushed a fix into GIT master, would you please double-check in your side if it works properly ?

**Comment by mahdi-asadpour-rr** [comment] 2017-06-16 14:50
@edsiper Thanks! It fixes the issue.

**Closed** 2017-06-16 16:12 UTC
Labels: bug
