### ISSUE TITLE
[ warn] [in_syslog] error parsing log message

### ISSUE THREAD

**Issue by romanvbabenko** [fluent/fluent-bit#362] opened 2017-08-22 19:31 UTC
Ubuntu 16.04
Architecture: amd64
Version: 0.12.0
```
/etc/rsyslog.conf
...
*.* @@192.168.33.6:42185
```

/etc/td-agent-bit/td-agent-bit.conf
```
[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    trace
    Parsers_File parsers.conf

[INPUT]
    Name         syslog
    Mode         tcp
    Listen       192.168.33.6
    Port         42185

[OUTPUT]
    Name  stdout
    Match *
```

/var/log/syslog
```
Aug 22 19:28:21 ubuntu-xenial td-agent-bit[2758]: [2017/08/22 19:28:21] [ warn] [in_syslog] error parsing log message
```

**Comment by edsiper** [comment] 2017-08-23 03:54
what Syslog format rsyslog is using ? rfc5424 or rfc3164?

**Comment by romanvbabenko** [comment] 2017-08-23 05:12
I tried both provided by Parser parameter. The result was the same.
The format is default for

Vagrant box: v0rtex/xenial64
 
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

**Comment by edsiper** [comment] 2017-09-25 18:50
@romanvbabenko 

my apologizes for the delay.

I've found the problem is a setup on rsyslog side, I have updated our documentation pointing out some hints for rsyslog setup:

- [Rsyslog to Fluent Bit: Network mode over TCP](http://fluentbit.io/documentation/0.12/input/syslog.html#rsyslog_to_fluentbit_network)

Please let me know if that works.

**Comment by edsiper** [comment] 2017-09-26 16:41
Closing this issue as solved, if is there any remaining question just posted here again.

**Closed by edsiper** 2017-09-26 16:41 UTC
Labels: fixed, question
