### ISSUE TITLE
Tail plug-in fails to keep track of state of file when parser is used

### ISSUE THREAD

**Issue by 2x-bullet-time** [fluent/fluent-bit#499] opened 2018-02-01 16:14 UTC
I have noticed tail plugin does not obey the state of the file when a parser is defined. Plugin will always start at the head of the file unless parser is blanked out. This issue can also be replicated using command line:

fluent-bit --parser=parsers.conf -i tail -p path=/var/log/syslog -p db=/var/log/xyz.sqlite -p parser=syslog-custom -o stdout

This command will work as expected if parser parameter is taken out. 
This is my sosreport:

```

[Fluent Bit]
    Edition             Community Edition
    Version             0.12.12
    Built Flags          JSMN_PARENT_LINKS JSMN_STRICT FLB_HAVE_TLS FLB_HAVE_SQLDB FLB_HAVE_BUFFERING FLB_HAVE_FLUSH_LIBCO FLB_HAVE_FORK FLB_HAVE_PROXY_GO FLB_HAVE_REGEX FLB_HAVE_C_TLS FLB_HAVE_SETJMP FLB_HAVE_ACCEPT4 FLB_HAVE_INOTIFY

[Operating System]
    Name                Linux
    Release             4.1.15
    Version             #3 SMP PREEMPT Fri Jul 7 11:18:13 PDT 2017

[Hardware]
    Architecture        armv7l
    Processors          1

[Built Plugins]
    Inputs              cpu mem kmsg tail proc disk netif dummy head health serial stdin tcp mqtt lib forward random syslog
    Filters             grep stdout kubernetes parser record_modifier
    Outputs             counter es exit file forward http influxdb kafka-rest nats null plot stdout retry td lib flowcounter

[SERVER] Runtime configuration
    Flush               5
    Daemon              Off
    Log_Level           Debug

[INPUT] Instance
    Name                tail.0 (tail, id=0)
    Flags               DYN_TAG
    Threaded            No
    Tag                 tail.0
    Path                /var/log/syslog
    db                  /var/log/landing_files.sqlite
    Parser              syslog-custom


[OUTPUT] Instance
    Name                stdout.0 (stdout, mask_id=1)
    Match               *
    TLS Active          No
    Retry Limit         1
```
I am hoping I have done something wrong on my end. Thanks!

**Comment by edsiper** [comment] 2018-02-05 19:45
@2x-bullet-time thanks for raising this issue.

I did some local tests and the problem that I found in in_tail plugin, is that if a parser fails against a log line (bad regex), that content is missed, the right behavior is to keep that information in "raw text" mode. I placed a fix for that behavior in GIT master and 0.12 branches.

**Comment by 2x-bullet-time** [comment] 2018-02-05 21:33
Thank you for your work. I will give it a try!

**Comment by 2x-bullet-time** [comment] 2018-02-05 23:36
@edsiper 
I pulled down the latest version of master branch and recompiled it locally. When executing this command "fluent-bit -i tail -p path=/var/log/syslog -p db=/var/log/landing_files.db -o stdout", the tailing function works fine. However, when I run the following configuration file without a parser, in_tail will always read from beginning of file. This is my simple configuration file:

```
[SERVICE]
    Flush     5
    Parsers_File    parsers.conf
    Log_Level    info
[INPUT]
    Name    tail
    Path    /var/log/syslog
    db    /var/log/landing_files.db
    ##Parser    syslog-custom
##[FILTER]
    ##Name    grep
    ##Match    *
    ##Regex    process_name pppd
##[FILTER]
    ##Name    record_modifier
    ##Match    *
    ##Record    deviceURN 1234
    ##Record    deviceName Testing-Unit
[OUTPUT]
    Name stdout
    Match *
``` 

This is the sosreport associated with the above configuration file:
```
[Fluent Bit]
    Edition             Community Edition
    Version             0.13.0
    Built Flags          JSMN_PARENT_LINKS JSMN_STRICT FLB_HAVE_TLS FLB_HAVE_SQLDB FLB_HAVE_BUFFERING FLB_HAVE_FLUSH_LIBCO FLB_HAVE_FORK FLB_HAVE_PROXY_GO FLB_HAVE_REGEX FLB_HAVE_C_TLS FLB_HAVE_ACCEPT4 FLB_HAVE_INOTIFY

[Operating System]
    Name                Linux
    Release             4.1.15
    Version             #3 SMP PREEMPT Fri Jul 7 11:18:13 PDT 2017

[Hardware]
    Architecture        armv7l
    Processors          1

[Built Plugins]
    Inputs              cpu mem kmsg tail proc disk netif dummy head exec health serial stdin tcp mqtt lib forward random syslog
    Filters             grep stdout kubernetes parser record_modifier
    Outputs             counter es exit file forward http influxdb kafka-rest nats null plot stdout retry td lib flowcounter

[SERVER] Runtime configuration
    Flush               5
    Daemon              Off
    Log_Level           Info

[INPUT] Instance
    Name                tail.0 (tail, id=0)
    Flags               DYN_TAG
    Threaded            No
    Tag                 tail.0
    Path                /var/log/syslog
    db                  /var/log/landing_files.db


[OUTPUT] Instance
    Name                stdout.0 (stdout, mask_id=1)
    Match               *
    TLS Active          No
    Retry Limit         1
```

This is the sosreport associated with the above command:
```
[Fluent Bit]
    Edition             Community Edition
    Version             0.13.0
    Built Flags          JSMN_PARENT_LINKS JSMN_STRICT FLB_HAVE_TLS FLB_HAVE_SQLDB FLB_HAVE_BUFFERING FLB_HAVE_FLUSH_LIBCO FLB_HAVE_FORK FLB_HAVE_PROXY_GO FLB_HAVE_REGEX FLB_HAVE_C_TLS FLB_HAVE_ACCEPT4 FLB_HAVE_INOTIFY

[Operating System]
    Name                Linux
    Release             4.1.15
    Version             #3 SMP PREEMPT Fri Jul 7 11:18:13 PDT 2017

[Hardware]
    Architecture        armv7l
    Processors          1

[Built Plugins]
    Inputs              cpu mem kmsg tail proc disk netif dummy head exec health serial stdin tcp mqtt lib forward random syslog
    Filters             grep stdout kubernetes parser record_modifier
    Outputs             counter es exit file forward http influxdb kafka-rest nats null plot stdout retry td lib flowcounter

[SERVER] Runtime configuration
    Flush               5
    Daemon              Off
    Log_Level           Info

[INPUT] Instance
    Name                tail.0 (tail, id=0)
    Flags               DYN_TAG
    Threaded            No
    Tag                 tail.0
    path                /var/log/syslog
    db                  /var/log/landing_files.db
    Routes              stdout.0


[OUTPUT] Instance
    Name                stdout.0 (stdout, mask_id=1)
    Match               *
    TLS Active          No
    Retry Limit         1
```
in_tail plugin does not keep track of the state of the file when parser is used, either in command or config-file mode.

This is the sosreport associated with a configuration file with parser enabled:

```
[Fluent Bit]
    Edition             Community Edition
    Version             0.13.0
    Built Flags          JSMN_PARENT_LINKS JSMN_STRICT FLB_HAVE_TLS FLB_HAVE_SQLDB FLB_HAVE_BUFFERING FLB_HAVE_FLUSH_LIBCO FLB_HAVE_FORK FLB_HAVE_PROXY_GO FLB_HAVE_REGEX FLB_HAVE_C_TLS FLB_HAVE_ACCEPT4 FLB_HAVE_INOTIFY

[Operating System]
    Name                Linux
    Release             4.1.15
    Version             #3 SMP PREEMPT Fri Jul 7 11:18:13 PDT 2017

[Hardware]
    Architecture        armv7l
    Processors          1

[Built Plugins]
    Inputs              cpu mem kmsg tail proc disk netif dummy head exec health serial stdin tcp mqtt lib forward random syslog
    Filters             grep stdout kubernetes parser record_modifier
    Outputs             counter es exit file forward http influxdb kafka-rest nats null plot stdout retry td lib flowcounter

[SERVER] Runtime configuration
    Flush               5
    Daemon              Off
    Log_Level           Info

[INPUT] Instance
    Name                tail.0 (tail, id=0)
    Flags               DYN_TAG
    Threaded            No
    Tag                 tail.0
    Path                /var/log/syslog
    db                  /var/log/landing_files.db
    Parser              syslog-custom


[OUTPUT] Instance
    Name                stdout.0 (stdout, mask_id=1)
    Match               *
    TLS Active          No
    Retry Limit         1

```

Thanks!

**Comment by 2x-bullet-time** [comment] 2018-02-05 23:55
@edsiper 
When executing command "fluent-bit -i tail -p path=/var/log/syslog -p db=/var/log/landing_files.db -o stdout --verbose", in_tail plugin is able to pick up the offset value according to this log:

```
[2018/02/05 23:51:06] [ info] [engine] started
[2018/02/05 23:51:06] [debug] [in_tail] inotify watch fd=20
[2018/02/05 23:51:06] [debug] [in_tail] scanning path /var/log/syslog
[2018/02/05 23:51:06] [debug] [in_tail] add to scan queue /var/log/syslog, offset=3594
[2018/02/05 23:51:06] [debug] [router] default match rule tail.0:stdout.0
[2018/02/05 23:51:06] [debug] [in_tail] file=/var/log/syslog promote to TAIL_EVENT
```

However, it fails to detect it in these scenario(config file without parser, config file with parser, command with parser) according to this log:
```
[2018/02/05 23:54:51] [ info] [engine] started
[2018/02/05 23:54:51] [debug] [in_tail] inotify watch fd=19
[2018/02/05 23:54:51] [debug] [in_tail] scanning path /var/log/syslog
[2018/02/05 23:54:51] [debug] [in_tail] add to scan queue /var/log/syslog, offset=0
[2018/02/05 23:54:51] [debug] [router] input=tail.0 'DYNAMIC TAG'
[2018/02/05 23:54:51] [debug] [input tail.0] [mem buf] size = 4291
[2018/02/05 23:54:51] [debug] [in_tail] file=/var/log/syslog read=3594 lines=41
[2018/02/05 23:54:51] [debug] [in_tail] file=/var/log/syslog promote to TAIL_EVENT
```
Thanks!

**Comment by 2x-bullet-time** [comment] 2018-02-06 21:31
I gave it another try using your apache log and here is the result:

in_tail plugin behaves properly when it is invoked via command line. However, it does not utilize offset when it is executed using a configuration file. 

Here is the configuration file (db + parser):
```
[SERVICE]
    Flush     1
    Parsers_File    parsers.conf
    Log_Level    debug
    Daemong    Off
[INPUT]
    Name    tail
    path    /var/log/apache.log
    DB    /var/log/landing_files.db
    Parser    apache
    Routes    stdout.0
[OUTPUT]
    Name stdout
    Match *
```
Sosreports from both modes are identical.

**Comment by 2x-bullet-time** [comment] 2018-02-06 21:37
I gave it another try using your apache log and here is the result:

in_tail plugin behaves properly when it is invoked via command line. However, it does not utilize offset when it is executed using a configuration file. 

Here is the configuration file (db + parser):
```
[SERVICE]
    Flush     1
    Parsers_File    parsers.conf
    Log_Level    debug
    Daemon    Off
[INPUT]
    Name    tail
    path    /var/log/apache.log
    DB    /var/log/landing_files.db
    Parser    apache
[OUTPUT]
    Name    stdout
    Match    *

```
Interestingly, my syslog regex is able to parse

**Comment by 2x-bullet-time** [comment] 2018-02-07 00:28
This might be a system/conf specific problem. I used the same set up on my ubuntu VM and it was working just fine in either mode. I will close this issue for now. Thank you.

**Comment by 2x-bullet-time** [comment] 2018-02-07 17:58
Hello :)
Could it be the problem of running fluent-bit on an armv7l? Fluent-bit PPA didn't seem to supply a build for armv7l. I had to compile fluent-bit source code using cmake on the armv7l machine. On the other hand, I was able to get an amd64 td-agent-bit build on my ubuntu VM from PPA.

**Comment by edsiper** [comment] 2018-02-07 18:14
@2x-bullet-time once compiled in your armv7l, do you still face the issue ?

**Comment by BoundInfinity** [comment] 2018-02-07 18:58
@edsiper 
opps. Sorry for not being clear. I had to compile fluent-bit source code on the armv7l machine because the machine could not fetch an armv7l td-agent-bit build from PPA. I also had to compile cmake because fluent-bit required cmake to compile. I have been facing this issue since then on the armv7l machine. I went through the same compilation steps on an Ubuntu VM running on windows 10 and in_tail plugin worked properly. The plugin also worked in the amd64 td-agent-bit build on the Ubuntu VM. I have also tired compiling fluent-bit on the armv7l machine with the FLB_ALL flag to no avail.

**Comment by 2x-bullet-time** [comment] 2018-02-07 19:07
@edsiper 
opps. Sorry for not being clear. I had to compile fluent-bit source code on the armv7l machine because the machine could not fetch an armv7l td-agent-bit build from PPA. I also had to compile cmake because fluent-bit required cmake to compile. I have been facing this issue since then on the armv7l machine. I went through the same compilation steps on an Ubuntu VM running on windows 10 and in_tail plugin worked properly. The plugin also worked in the amd64 td-agent-bit build on the Ubuntu VM. I have also tried compiling fluent-bit on the armv7l machine with FLB_ALL flag to no avail. Could it be that certain differences might need to be accounted for when compiling fluent-bit for an armv7l architecture? Please excuse my limited knowledge working with low level machinery.

**Comment by edsiper** [comment] 2018-02-07 19:09
@2x-bullet-time ok, so there are two concerns: 

- 1. missing armv7l packages
- 2. tail not working properly.

I will focus on #2. would you please specify the kernel version and linux distribution that device/machine uses ?

**Comment by 2x-bullet-time** [comment] 2018-02-07 19:32
@edsiper armv7l machine works properly if parameters are inserted as a part of the command as opposed to a config file. Is tail still an issue? 

The kernel+dist come with a custom board.  The kernel is a custom variation of 4.1.15 and distro is Debian GNU/Linux 8.10 (jessie)

**Comment by edsiper** [comment] 2018-02-07 20:13
@2x-bullet-time it's preferred to set all parameters either in the config file or in the command line only, avoid to mix them up (only use config file).

**Comment by 2x-bullet-time** [comment] 2018-02-07 20:18
@edsiper Yea. I tested it with all parameters in config file vs. in command.

**Comment by edsiper** [comment] 2018-02-07 20:20
@2x-bullet-time to clarify: when you are using the configuration file, do you see an unexpected behavior ?

**Comment by 2x-bullet-time** [comment] 2018-02-07 20:21
@edsiper Yes. The behavior is observed when a configuration file is used.

**Comment by edsiper** [comment] 2018-02-07 20:30
please paste "command line arguments"  that works and the configuration file content..

**Comment by 2x-bullet-time** [comment] 2018-02-07 20:46
command line arguments:
```
fluent-bit -R parsers.conf -i tail -p path=/var/log/apache.log -p parser=apache -p db=/var/log/landing_files.db -o stdout -f 1
```

configuration file content:
```
[SERVICE]
    Flush    1
    Parsers_File    parsers.conf
    Log_Level    debug
    Daemon    Off
[INPUT]
    Name    tail
    Path    /var/log/apache.log
    DB    /var/log/landing_files.db
    Parser    apache
[OUTPUT]
    Name    stdout
    Match    *
```

**Comment by edsiper** [comment] 2018-02-08 22:40
@2x-bullet-time do you know if the problem can be reproduced in a Raspberry Pi or similar ?

**Comment by 2x-bullet-time** [comment] 2018-02-09 20:57
@edsiper Hello. I am able to reproduce this problem on a bbb. Here is the sosreport from the exact same setup:

```
[Fluent Bit]
    Edition             Community Edition
    Version             0.13.0
    Built Flags          JSMN_PARENT_LINKS JSMN_STRICT FLB_HAVE_TLS FLB_HAVE_SQLDB FLB_HAVE_FLUSH_LIBCO FLB_HAVE_FORK FLB_HAVE_PROXY_GO FLB_HAVE_REGEX FLB_HAVE_C_TLS FLB_HAVE_ACCEPT4 FLB_HAVE_INOTIFY

[Operating System]
    Name                Linux
    Release             4.9.45-ti-r57
    Version             #1 SMP PREEMPT Fri Aug 25 22:58:38 UTC 2017

[Hardware]
    Architecture        armv7l
    Processors          1

[Built Plugins]
    Inputs              cpu mem kmsg tail proc disk netif dummy head exec health serial stdin tcp mqtt lib forward random syslog
    Filters             grep stdout kubernetes parser record_modifier
    Outputs             counter es exit file forward http influxdb kafka-rest nats null plot stdout td lib flowcounter

[SERVER] Runtime configuration
    Flush               1
    Daemon              Off
    Log_Level           Debug

[INPUT] Instance
    Name                tail.0 (tail, id=0)
    Flags               DYN_TAG
    Threaded            No
    Tag                 tail.0
    Path                /var/log/apache.log
    DB                  /var/log/landing_files.db
    Parser              apache


[OUTPUT] Instance
    Name                stdout.0 (stdout, mask_id=1)
    Match               *
    TLS Active          No
    Retry Limit         1
```

**Comment by edsiper** [comment] 2018-02-13 21:40
bbb == beaglebone black ?, if so, which OS version (image URL?)

**Comment by 2x-bullet-time** [comment] 2018-02-13 22:35
Yea. It is a beaglebone black. /etc/dogtag gives:
``` 
BeagleBoard.org Debian Image 2017-08-31
```

I checked BeagleBoard.org and this is the only image corresponds to that date: 
http://debian.beagleboard.org/images/bone-debian-9.1-lxqt-armhf-2017-08-31-4gb.img.xz

**Comment by edsiper** [comment] 2018-09-13 02:30
@2x-bullet-time 

I've tried to replicate without success the issue you just described in a beagle bone black board using the debian image you have provided. The database file offsets are set properly (except when Fluent Bit don't have write access to /var/log/... but a message is triggered)

would you please check if you can reproduce the problem with Fluent Bit 0.14.1 version ?

**Comment by edsiper** [comment] 2018-12-20 22:22
Closing due to timeout.

**Closed by edsiper** 2018-12-20 22:22 UTC
Labels: bug, fixed, timeout, waiting-for-user
