### ISSUE TITLE
Updating to 1.0.5 breaks communication with Fluentd

### ISSUE THREAD

**Issue by bhvishal9** [fluent/fluent-bit#1228] opened 2019-03-27 10:50 UTC
Hi, 

We are using fluent-bit and forwarding logs to fluentd, which is sending it to AWS cloudwatch. This is our fluent-bit configuration

```  output-forward.conf: |
    [OUTPUT]
        Name            forward
        Match           *
        Host            ${FORWARD_HOST}
        Port            ${FORWARD_PORT}
        tls             On
        # see fluentd <transport tls> config
        tls.verify      Off
        tls.debug       1
        shared_key      ${FLUENT_SHARED_KEY}
        # Setting the retry counts to unlimited, see fluentd scheduler configuration (https://docs.fluentbit.io/manual/configuration/scheduler)
        Retry_Limit     False
```

Fluentd configuration:
```<source>
      @type forward

      <transport tls>
        insecure true
        generate_cert_country DE
        generate_cert_state Berlin
        generate_cert_locality Berlin
        generate_cert_common_name fluentd.logging.svc.cluster.local
      </transport>

      <security>
        self_hostname fluentd.logging.svc.cluster.local
        shared_key "#{ENV['FLUENT_SHARED_KEY']}"
      </security>
    </source>
```

Now this configuration is working fine with fluent-bit version 1.0.4 and fluentd version 1.2.2, but when we upgrade fluent-bit to 1.0.5, everything breaks. Fluent-bit does try to send data to fluentd but the handshake is not successful and no events in fluentd. Below are the fluent-bit logs:

```[2019/03/27 10:25:34] [debug] [out_forward] request 2137436 bytes to flush
[2019/03/27 10:25:35] [debug] [out_fw] 3862 entries tag='kube.fluent-bit-xh2zs_logging_fluent-bit-95f9f00ef61134433065668833eb80572c8c47e70ece176936c006ce186c5a2b.log' tag_len=109
[2019/03/27 10:25:35] [debug] [out_forward] request 832286 bytes to flush
[2019/03/27 10:25:35] [debug] [out_fw] 1504 entries tag='kube.fluent-bit-xh2zs_logging_fluent-bit-95f9f00ef61134433065668833eb80572c8c47e70ece176936c006ce186c5a2b.log' tag_len=109
[2019/03/27 10:25:35] [debug] [out_forward] request 906 bytes to flush
[2019/03/27 10:25:35] [debug] [out_fw] 2 entries tag='systemd.kubelet.service' tag_len=23
[2019/03/27 10:25:36] [debug] [out_forward] request 2136781 bytes to flush
[2019/03/27 10:25:36] [debug] [out_fw] 3861 entries tag='kube.fluent-bit-xh2zs_logging_fluent-bit-95f9f00ef61134433065668833eb80572c8c47e70ece176936c006ce186c5a2b.log' tag_len=109
```

## Expected Behaviour

Updating the version should work. In the changelog, it is mentioned "Don't assumed 'secure' mode just because TLS is on.", which is pretty vague.

**Comment by edsiper** [comment] 2019-03-27 15:48
I am looking at the change in question in 1.0.5 version for out_forward:

https://github.com/fluent/fluent-bit/commit/d89dc36926404f90b992f43e34c49d3763f2efdc

Basically it says that will run 'Forward in secure mode' IF a shared_key exists. Since your Configmap have "TLS On" and a "Shared_Key" I don't understand what's the issue you are facing. 

I will do some local tests.

**Comment by edsiper** [comment] 2019-03-27 16:32
Found the root cause of the problem, d89dc36 breaks secured mode configuration since it do not check first if a shared_key exists. Working in a fix.

**Comment by edsiper** [comment] 2019-03-27 16:41
I am just going to revert that change since stunnel is designed to be used with daemons not-aware of TLS, that's not the case of Fluentd. In Fluent Bit we have the pending functionality in in_forward that will be fixed this year. Running Fluent Bit securely must use Forward Protocol and further Forward handshake. 

@bhvishal9 my apologizes, I will make a new release with the fix in place within the next hours.

**Comment by edsiper** [comment] 2019-03-27 22:32
https://fluentbit.io/announcements/v1.0.6/

**Closed by edsiper** 2019-03-27 22:32 UTC
Labels: bug, fixed
