### ISSUE TITLE
Stream processor Missing sub-key in Aggregate function 

### ISSUE THREAD

**Issue by HansMeijer-AvidentIT** [fluent/fluent-bit#1446] opened 2019-07-18 09:01 UTC
## Bug Report

**Describe the bug**
This gives an error: "SELECT key['nestedkey'], SUM(key['nestedsumkey']) FROM STREAM:instream GROUP BY key['nestedkey']"

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
json structure:
{
"key": {
      "nestedkey": "SomeKey",
      "nestedsumkey": 23
    }
}
```

**Expected behavior**
It should be possible to aggregate using nested keys.
In this case it generates an error. It would also be good if it could follow SQL standard so you could group on a subpart of columns but in the SELECT have all columns and aggregate function on the specific column, like: "SELECT notnestedkey,  key['nestedkey1'],  key['nestedkey2'],  key['nestedkey3'], sum( key['nestedsumkey']) FROM STREAM:instream group by notnestedkey,  key['nestedkey1'];"

**Screenshots**

**Your Environment**

* Version used: 1.1.3
* Configuration: TCP input and stream processor and STDOUT.
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version: Linux 
* Operating System and version: Debian 9.9
* Filters and plugins: TCP input plugin, Stream processor and Stdout Plugin

**Additional context**
This issue could help achieve aggregations of duplicate rows and minimize network trafic.
This should be helpful for others to have as well.

**Comment by edsiper** [comment] 2019-07-24 19:49
thanks. we are working on this.

**Comment by hansmeijerprotegrity** [comment] 2019-09-09 13:50
Any news on this? I see that some changes has been done in regards of the stream processor and sub keys but not related to aggregation/group by.

**Comment by koleini** [comment] 2019-09-09 14:08
This is implemented and will be included in the next release (the feature is already merged into the master branch).

**Comment by hansmeijerprotegrity** [comment] 2019-09-09 14:57
Thanks, any samples you can provide since i have the git version and if possible i would like to test it as soon as possible since we will use this as a vital part of the implementation. I have the master git branch and i can see that things has been worked on. So i would also be able to test it.

**Comment by koleini** [comment] 2019-09-09 15:26
You can find sample queries with subkeys used for running tests in ﻿here:
https://github.com/fluent/fluent-bit/blob/master/tests/internal/stream_processor.c

**Comment by HansMeijer-AvidentIT** [comment] 2019-09-15 16:27
Unfortunately the samples does not provide any information on how to do aggregation with "GROUP BY" on nested fields. I tried according to the other samples to handle it but it does not seem to work.
A sample of a query i try to execute:
Exec   CREATE STREAM pty_agg WITH (tag='json_subkey') AS SELECT highkey['sub2'], sum(highkey['amount'])  from STREAM:tcp_in_data WINDOW TUMBLING (5 SECOND) GROUP BY highkey['sub2'];
Is it so that "aggregation using GROUP BY" not included?

**Comment by koleini** [comment] 2019-09-19 21:27
@HansMeijer-AvidentIT Correct, sub-key extraction is not added to `GROUP BY` functionality. We will work to fix it soon, Thanks!

**Comment by koleini** [comment] 2019-09-24 15:38
@HansMeijer-AvidentIT subkeys are now supported in GROUP BY statement. You can see the examples used in the unit tests. Please check and let us know if things are working for you.

**Comment by HansMeijer-AvidentIT** [comment] 2019-09-27 14:21
Hi
i still cant get it to work using the unittest samples.I rebuilt fluent-bit
with latest checkout and i have a streamprocessor conf like this:
[STREAM_TASK]
    Name   aggregate_test
    Exec   CREATE STREAM pty_agg WITH (tag='json_subkey') AS SELECT
SUM(map['sub1']['sub3']) from STREAM:tcp_in_data WINDOW TUMBLING (1 SECOND);

The fluent-bit conf:
[SERVICE]
    Flush           1
    Daemon          off
    Log_Level       debug
    Streams_File ./stream_processor.conf

[INPUT]
    Name         tail
    Path         ./samples-subkeys.json
    Tag          json_nested
    Alias        in_data

[OUTPUT]
    Name         stdout
    Match        *

I am probably missing something.

Please advice.

Kind regards
Hans
Ps. i attach the config files, also the file "samples-subkeys.json" is the
one in the tests folder of fluent-bit source tree.


Den tis 24 sep. 2019 kl 17:39 skrev Masoud Koleini <notifications@github.com

**Comment by koleini** [comment] 2019-09-27 15:18
Do you receive any error message, or you get nothing on stdout from your stream?

One thing that I can see is, your tail input is tagged `in_data`, while your stream reads from `STREAM:tcp_in_data`. Can you replace `tcp_in_data` with `in_data` in your query and see if it works?

**Comment by HansMeijer-AvidentIT** [comment] 2019-09-28 10:26
Hi,
i did replace the in_data_tcp with in_data but no changes in the test, i
attach the config files for fluent-bit and stream_processor again.
I do not see any errors or others, i also tested with only SUM as further
down and then i get an output but not what is expected.
This is the output:
Fluent Bit v1.3.0
Copyright (C) Treasure Data

[2019/09/28 12:22:54] [debug] [storage] [cio stream] new stream registered:
in_data
[2019/09/28 12:22:54] [ info] [storage] initializing...
[2019/09/28 12:22:54] [ info] [storage] in-memory
[2019/09/28 12:22:54] [ info] [storage] normal synchronization mode,
checksum disabled, max_chunks_up=128
[2019/09/28 12:22:54] [ info] [engine] started (pid=14480)
[2019/09/28 12:22:54] [debug] [engine] coroutine stack size: 24576 bytes
(24.0K)
[2019/09/28 12:22:54] [debug] [in_tail] inotify watch fd=20
[2019/09/28 12:22:54] [debug] [in_tail] scanning path ./samples-subkeys.json
[2019/09/28 12:22:54] [debug] [in_tail] add to scan queue
./samples-subkeys.json, offset=0
[2019/09/28 12:22:54] [debug] [router] match rule tail.0:stdout.0
[2019/09/28 12:22:54] [debug] [storage] [cio stream] new stream registered:
pty_agg
[2019/09/28 12:22:54] [ info] [sp] stream processor started
[2019/09/28 12:22:54] [ info] [sp] registered task: pty_aggregate
[2019/09/28 12:22:54] [debug] [in_tail] file=./samples-subkeys.json
read=543 lines=9
[2019/09/28 12:22:54] [debug] [in_tail] file=./samples-subkeys.json promote
to TAIL_EVENT
[0] json_nested: [1569666174.664237893, {"log"=>"{"id": 0, "map": {"sub1":
{"sub2": {"color": "blue"}}}}"}]
[1] json_nested: [1569666174.664246033, {"log"=>"{"id": 1, "map": {"sub1":
{"sub2": {"color": "red"}}}}"}]
[2] json_nested: [1569666174.664247067, {"log"=>"{"id": 2, "map": {"sub1":
{"sub2": 123}}}"}]
[3] json_nested: [1569666174.664248127, {"log"=>"{"id": 3, "map": {"sub1":
{"sub2": "123", "stype": "a"}, "mtype": 0}}"}]
[4] json_nested: [1569666174.664249090, {"log"=>"{"id": 4, "map": {"color":
"blue"}}"}]
[5] json_nested: [1569666174.664250056, {"log"=>"{"id": 5, "map": {"sub1":
{"sub3": "100", "stype": "a"}, "mtype": 0}}"}]
[6] json_nested: [1569666174.664251023, {"log"=>"{"id": 6, "map": {"sub1":
{"sub3": "0.50", "stype": "b"}, "mtype": 1}}"}]
[7] json_nested: [1569666174.664251973, {"log"=>"{"id": 7, "map": {"sub1":
{"sub3": "5.50", "stype": "a"}, "mtype": 0}}"}]
[8] json_nested: [1569666174.664252951, {"log"=>"{"id": 8, "map": {"sub1":
{"sub3": "10.50", "stype": "b"}, "mtype": 2}}"}]
[2019/09/28 12:22:54] [debug] [task] created task=0x556e9c889a60 id=0 OK
[2019/09/28 12:22:54] [debug] [task] destroy task=0x556e9c889a60 (task_id=0)


With this stream processor conf : Exec   CREATE STREAM pty_agg WITH
(tag='json_subkey') AS SELECT SUM(map['sub1']['sub3']) from STREAM:in_data
WINDOW TUMBLING (1 SECOND);

The output is:
Fluent Bit v1.3.0
Copyright (C) Treasure Data

[2019/09/28 12:24:40] [debug] [storage] [cio stream] new stream registered:
in_data
[2019/09/28 12:24:40] [ info] [storage] initializing...
[2019/09/28 12:24:40] [ info] [storage] in-memory
[2019/09/28 12:24:40] [ info] [storage] normal synchronization mode,
checksum disabled, max_chunks_up=128
[2019/09/28 12:24:40] [ info] [engine] started (pid=14530)
[2019/09/28 12:24:40] [debug] [engine] coroutine stack size: 24576 bytes
(24.0K)
[2019/09/28 12:24:40] [debug] [in_tail] inotify watch fd=20
[2019/09/28 12:24:40] [debug] [in_tail] scanning path ./samples-subkeys.json
[2019/09/28 12:24:40] [debug] [in_tail] add to scan queue
./samples-subkeys.json, offset=0
[2019/09/28 12:24:40] [debug] [router] match rule tail.0:stdout.0
[2019/09/28 12:24:40] [debug] [storage] [cio stream] new stream registered:
pty_agg
[2019/09/28 12:24:40] [ info] [sp] stream processor started
[2019/09/28 12:24:40] [ info] [sp] registered task: pty_aggregate
[2019/09/28 12:24:40] [debug] [in_tail] file=./samples-subkeys.json
read=543 lines=9
[2019/09/28 12:24:40] [debug] [in_tail] file=./samples-subkeys.json promote
to TAIL_EVENT
[0] json_nested: [1569666280.022185212, {"log"=>"{"id": 0, "map": {"sub1":
{"sub2": {"color": "blue"}}}}"}]
[1] json_nested: [1569666280.022192325, {"log"=>"{"id": 1, "map": {"sub1":
{"sub2": {"color": "red"}}}}"}]
[2] json_nested: [1569666280.022193271, {"log"=>"{"id": 2, "map": {"sub1":
{"sub2": 123}}}"}]
[3] json_nested: [1569666280.022194151, {"log"=>"{"id": 3, "map": {"sub1":
{"sub2": "123", "stype": "a"}, "mtype": 0}}"}]
[4] json_nested: [1569666280.022195074, {"log"=>"{"id": 4, "map": {"color":
"blue"}}"}]
[5] json_nested: [1569666280.022195935, {"log"=>"{"id": 5, "map": {"sub1":
{"sub3": "100", "stype": "a"}, "mtype": 0}}"}]
[6] json_nested: [1569666280.022196780, {"log"=>"{"id": 6, "map": {"sub1":
{"sub3": "0.50", "stype": "b"}, "mtype": 1}}"}]
[7] json_nested: [1569666280.022197626, {"log"=>"{"id": 7, "map": {"sub1":
{"sub3": "5.50", "stype": "a"}, "mtype": 0}}"}]
[8] json_nested: [1569666280.022198493, {"log"=>"{"id": 8, "map": {"sub1":
{"sub3": "10.50", "stype": "b"}, "mtype": 2}}"}]
[2019/09/28 12:24:41] [debug] [task] created task=0x557e833b6db0 id=0 OK
[2019/09/28 12:24:41] [debug] [task] destroy task=0x557e833b6db0 (task_id=0)
[0] json_subkey: [1569666281.000796100, {"SUM(map['sub1']['sub3'])"=>0}]
[2019/09/28 12:24:42] [debug] [task] created task=0x557e833b6db0 id=0 OK
[2019/09/28 12:24:42] [debug] [task] destroy task=0x557e833b6db0 (task_id=0)

Regards
Hans

Den fre 27 sep. 2019 kl 17:18 skrev Masoud Koleini <notifications@github.com

**Comment by edsiper** [comment] 2019-09-28 18:12
I think the problem is that your tail section you are not applying a parser, so it assumes the data are raw bytes without structure so the content becomes inside a main key called __log__, e.g:

```
{"log"=>"{"id": 8, "map": {"sub1":{"sub3": "10.50", "stype": "b"}, "mtype": 2}}"}]
```

make sure to enable the Parsers_File and the parser, e.g:

```
[SERVICE]
    Flush           1
    Daemon          off
    Log_Level       debug
    Parsers_file    parsers.conf
    Streams_File ./stream_processor.conf

[INPUT]
    Name         tail
    Path         ./samples-subkeys.json   
    Tag          json_nested
    Alias        in_data
    Parser     json

[OUTPUT]
    Name         stdout
    Match        *
```

**Comment by HansMeijer-AvidentIT** [comment] 2019-09-29 09:51
Thanks!
That fixed it, sorry for disturbing but really appreciate the help. I will
continue testing and if i encounter anything i hope it is ok if i report it.

Kind regards
Hans

Den lör 28 sep. 2019 kl 20:12 skrev Eduardo Silva <notifications@github.com

**Comment by edsiper** [comment] 2019-09-29 16:53
you are welcome, feel free to report any upcoming error/problem you find.

I will close this ticket for now, for a new issue open a new issue.

**Closed by edsiper** 2019-09-29 16:53 UTC
Labels: enhancement, work-in-process
