### ISSUE TITLE
Question: Support for multiple ES outputs in same fluent-bit config?

### ISSUE THREAD

**Issue by brycefisher** [fluent/fluent-bit#515] opened 2018-02-20 17:33 UTC
My end goal is to be able to ship different kinds of logs to different indices in ElasticSearch. I've been able to send docker logs to a specific ElasticSearch index; but I would like to send various log files made other applications to different ElasticSearch indices on the same ElasticSearch cluster. I tried to use `Tag` on tail inputs and `Match` on different es outputs, but fluent-bit didn't accept this configuration. Is it likely I used the configuration incorrectly? Is this use case supported by fluent-bit? Thanks so much!

**Comment by edsiper** [comment] 2018-02-20 17:42
@brycefisher please share your configuration file.

**Comment by edsiper** [comment] 2018-02-26 22:32
ping

**Comment by edsiper** [comment] 2018-03-05 21:46
Closing as fixed.

**Closed by edsiper** 2018-03-05 21:46 UTC
Labels: fixed, question

**Comment by ArturZurawski** [comment] 2019-09-30 16:19
Hi,

I have the same problem. Trying to push logs from different input to different indices in same ES. My config:

```
[INPUT]
    Name      forward
    unix_path /tmp/fluent-bit/sock
    Tag       app.${ENV}

[INPUT]
    Name   tail
    Path   /host/var/log/ecs/ecs-*
    Tag    ecs.${ENV}

[OUTPUT]
    Name            es
    Match           ecs.*
    Host            ${ES_HOST}
    Port            443
    Logstash_Format On
    Retry_Limit     False
    Logstash_Prefix ecs-${ENV}
    tls             On
    tls.verify      Off

[OUTPUT]
    Name            es
    Match           app.*
    Host            ${ES_HOST}
    Port            443
    Logstash_Format On
    Retry_Limit     False
    Logstash_Prefix app-${ENV}
    tls             On
    tls.verify      Off
```

**Comment by edsiper** [comment] 2019-09-30 16:22
@ArturZurawski 

please for new issues, open a new ticket.

Forward input plugin cannot be tagged since records "already comes with a tag", so your tag is not enforced, that could be the root cause of the problem
