### ISSUE TITLE
Cross compiling failure against v0.11.0 with Yocto

### ISSUE THREAD

**Issue by cosmo0920** [fluent/fluent-bit#219] opened 2017-03-31 08:33 UTC
Fluent-Bit v0.11.0 does not build with Yocto toolchain.
I've got building failure.
It caused by onigmo which had been introduced in v0.11.0.

build log is: 
[log.do_compile.zip](https://github.com/fluent/fluent-bit/files/884960/log.do_compile.zip)

Yocto recipe is: 
[fluent-bit_0.11.0.bb](https://github.com/clear-code/meta-fluent/blob/479ff76609d02c37cc0fe4ef5be4cd5a9212fb3c/recipes-fluent/fluent-bit/fluent-bit_0.11.0.bb)

**Comment by edsiper** [comment] 2017-03-31 11:07
I did a local test and it builds fine:

```
$ bitbake fluentbit
WARNING: Host distribution "Ubuntu-16.10" has not been validated with this version of the build system; you may possibly experience unexpected failures. It is recommended that you use a tested distribution.
Loading cache: 100% |######################################################| Time: 0:00:00
Loaded 1321 entries from dependency cache.
Parsing recipes: 100% |####################################################| Time: 0:00:00
Parsing of 868 .bb files complete (867 cached, 1 parsed). 1322 targets, 50 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION        = "1.32.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "universal"
TARGET_SYS        = "i586-poky-linux"
MACHINE           = "qemux86"
DISTRO            = "poky"
DISTRO_VERSION    = "2.2.1"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              
meta-poky         
meta-yocto-bsp    = "morty:a3fa5ce87619e81d7acfa43340dd18d8f2b2d7dc"

Initialising tasks: 100% |#################################################| Time: 0:00:00
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
NOTE: Tasks Summary: Attempted 408 tasks of which 394 didn't need to be rerun and all succeeded.

Summary: There was 1 WARNING message shown.
```

would you please try to build libonigmo as a standalone lib with your own toolchain ?, it could be related to the toolchain you are using.

**Comment by cosmo0920** [comment] 2017-04-03 02:09
Umm..., my using toolchain is for RZ/G Yocto 1.6.1. 
I think that it is too old to build Fluent-Bit with this old Yocto.
Closing this in favor of #205.

---

```
Build Configuration:
BB_VERSION        = "1.22.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "Ubuntu-14.04"
TARGET_SYS        = "arm-poky-linux-gnueabi"
MACHINE           = "iwg20m"
DISTRO            = "poky"
DISTRO_VERSION    = "1.6.1"
TUNE_FEATURES     = "armv7a vfp neon callconvention-hard cortexa15"
TARGET_FPU        = "vfp-neon"
```

**Comment by cosmo0920** [comment] 2017-04-03 02:13
Ah, wait. Your configuration won't run cross compiling:

```
TUNE_FEATURES     = "m32 i586"
```

I'd tried to run cross compiling against Cortex-A15 arm board (RZ/G1M).

```
TUNE_FEATURES     = "armv7a vfp neon callconvention-hard cortexa15"
```

Could you try to build for Raspberry pi 2 or 3?
I think that it will be reproduce this problem.

**Comment by edsiper** [comment] 2017-04-26 15:53
Closing this issue since @cosmo0920 already confirmed that through PR #243 fixed the problems.

v0.11.4: http://fluentbit.io/announcements/v0.11.4/

**Closed by edsiper** 2017-04-26 15:53 UTC
