### ISSUE TITLE
rpm upgrade overwrites exsiting config settings

### ISSUE THREAD

**Issue by JungleGenius** [fluent/fluent-bit#1031] opened 2019-01-15 23:37 UTC
Updating from package td-agent-bit.x86_64 0:1.0.1-1 to package td-agent-bit.x86_64 0:1.0.2-1 overwrites parsers.conf and td-agent-bit.conf.

Expected behavior is to preserve the existing config files and their settings. 

e.g.  parsers.conf.rpmnew td-agent-bit.conf.rpmnew etc.

**Comment by chsnell** [comment] 2019-01-28 21:42
This appears to be a Duplicate of #980

**Comment by JungleGenius** [comment] 2019-02-21 16:33
Agree sorry about that.

**Closed** 2019-02-21 16:34 UTC
