### ISSUE TITLE
Fluentbit unable to get K8 meta data => Could not get meta fir POD XXXXXXX

### ISSUE THREAD

**Issue by rubans** [fluent/fluent-bit#3143] opened 2021-03-02 11:18 UTC
## Bug Report

**Describe the bug**
With fluent-bit v1.5, getting errors in the pod logs related to getting meta :
"could not get meta fir POD XXXXXXX"

Config:
 filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
[warn] [filter:kubernetes:kubernetes:0] could not get meta fir POD XXXXXXX
```
- Steps to reproduce the problem:
Just grab and deploy on GKE cluster (v1.19+)
**Expected behavior**

**Screenshots**

**Your Environment**

* Version used:1.15 FluentVit
* Configuration: GKE
* Environment name and version (e.g. Kubernetes? What version?): GKE 1.19
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

Have tested connecting to the K8s API internally within the cluster using the same creds (Crts and had all worked without any issue)

**Comment by agup006** [comment] 2021-03-02 23:48
@rubans I beileve we fixed this in Slack with proper permissions for the DaemonSet. I'm going to close this - feel free to reopen if you feel the issue is not resolved.

**Closed by agup006** 2021-03-02 23:48 UTC
