### ISSUE TITLE
Disruptive change on Time_Format in version 1.6.3

### ISSUE THREAD

**Issue by mpucholblasco** [fluent/fluent-bit#2758] opened 2020-11-10 12:14 UTC
## Bug Report

Versions 1.6.2 and below supported the `Time_Format` parser `%Y-%m-%dT%H:%M:%S.%L` for the following examples:
* `2020-11-10T11:11:26+00:00`
* `2020-11-10T11:40:00.161Z`

However, from version 1.6.3 (maybe it's related to #2722 ), the following error appears:
```
[2020/11/10 11:12:13] [ warn] [parser:json_logstash] invalid time format %Y-%m-%dT%H:%M:%S.%L for '2020-11-10T11:10:36+00:00'
```

Tried with parser `%Y-%m-%dT%H:%M:%S.%L%z`, but the error persisted:
```
[2020/11/10 11:23:12] [error] [parser] cannot parse '2020-11-10T11:23:12+00:00'
[2020/11/10 11:23:12] [ warn] [parser:json_logstash] invalid time format %Y-%m-%dT%H:%M:%S.%L%z for '2020-11-10T11:23:12+00:00'
```

Also tried parser `%Y-%m-%dT%H:%M:%S%z`, but another error appears:
```
[2020/11/10 11:44:00] [error] [parser] cannot parse '2020-11-10T11:44:00.041Z'
[2020/11/10 11:44:00] [ warn] [parser:json_logstash] invalid time format %Y-%m-%dT%H:%M:%S%z for '2020-11-10T11:44:00.041Z'
```

Seems that previous parser is more permissive than current one.

**Expected behavior**
`Time_Format` should be compatible with previous versions or have an alternative that does not imply changing all log formats.

**Your Environment**
* Version used: 1.6.3

**Comment by fujimotos** [comment] 2020-11-20 10:05
@mpucholblasco  Thank you for reporting. I will follow up this issue
and investigate what's wrong with the current code.

**Comment by stevenernst131** [comment] 2020-11-20 21:41
@fujimotos I have also been investigating this and had a repro with version 1.5.4. I experimented with a number of different versions and found that the error started appearing on version 1.5.3.

**Comment by ThomasEscobar** [comment] 2020-11-23 12:53
I've just upgrade from version 1.5.2 to 1.5.3 myself, and started hitting the same error. I have tested and confirmed that downgrading to 1.5.2 solves the issue, so that's what I will do for now.

```
[2020/11/23 11:23:16] [ warn] [parser:vq-syslog-parser-secure] invalid time format %Y-%m-%dT%H:%M:%S.%L%Z for '2020-11-23T11:23:16.000+00:00'
```

**Comment by edsiper** [comment] 2020-11-24 23:22
@fujimotos ping

**Comment by fujimotos** [comment] 2020-11-27 09:07
@mpucholblasco Hm. I can see what is causing this issue. 

The core issue of

    2020-11-10T11:11:26+00:00

is that it does not match the specified time format:

    %Y-%m-%dT%H:%M:%S.%L

The old implementation "worked" because it erroneously returned
0 even when the time format does not match the input time string.

In this light, the current behaviour is actually correct.

**Comment by ThomasEscobar** [comment] 2020-11-27 09:14
@fujimotos What about the example I gave above, my time format matches the time I am trying to parse, still I am having this new issue since 1.5.3.

**Comment by mpucholblasco** [comment] 2020-11-27 09:17
Hi @fujimotos ,
yes, I assumed this (sorry if it was not clear on my initial comment), however, as previous versions were "flexible" with this configuration and seems that it's also happening to more people...

**Comment by fujimotos** [comment] 2020-11-27 09:17
@ThomasEscobar I believe your issue is different from @mpucholblasco. 

The `strptime()` implementation in Fluent Bit does not support `+00:00` style
time format. It only support `+0000` (or `-0000`).

I'm planning to add support for that (the issue is tracked in #2625), so please
wait for me

**Comment by fujimotos** [comment] 2020-11-27 09:31
@mpucholblasco Above being said, I actually believe your requirement is legitimate.

> * `2020-11-10T11:11:26+00:00`
> * `2020-11-10T11:40:00.161Z`

Since real data often contains heterogeneous time fields like these,
I agree that there should be some way to be resilient against them.

So I've just submitted a patch #2813 that adds a new option `Time_Strict` to
make Fluent Bit permissive on varying time fields.

With this patch, you can set up your parser as follows:

```ini
[PARSER]
    ...
    Time_Format %Y-%m-%dT%H:%M:%S.%L
    Time_Strict Off
```

... and Fluent Bit will return a best guess even if a time field does
not match exactly against the format. For example:

    "2020-11-10T11:11:26.132"   => 2020-11-10T11:11:26.132000Z
    "2020-11-10T11:11:26+00:00" => 2020-11-10T11:11:26.000000Z

**Comment by mpucholblasco** [comment] 2020-11-27 09:52
It's perfect, thanks a lot @fujimotos . The only thing that could be confusing is that default parameter is `true` (according to my low-level knowledge of C), so documentation should clarify this case to avoid future problems or adjust the default value to `false`. It would be interesting to add documentation also on upgrade because some people could be affected.

Thanks again!

**Comment by fujimotos** [comment] 2020-11-28 02:34
#2625 has been merged. Close this ticket.

**Closed by fujimotos** 2020-11-28 02:34 UTC
Labels: bug

**Comment by fujimotos** [comment] 2020-11-28 02:46
@mpucholblasco Thank you for feedback. Your observation is correct.
The default value is set to be true (for now).

I feared that changing the behaviour to non-strict might lead to another
bug report "fluent bit should emit errors on invalid time field").

The doc update will follow soon...

@ThomasEscobar I think this new option will be useful for your case as well.
(Although I'm planning to add the support for `+00:00` in near future)
