### ISSUE TITLE
using vi on a test log

### ISSUE THREAD

**Issue by wittenst** [fluent/fluent-bit#313] opened 2017-06-29 20:32 UTC
We were testing the fluent-bit executable against some test log files, and used the option to  setup a sqlite database, sending the data to either stdout or a fluentd setup on another box.  We are receiving segmentation errors if we vi a monitored log file to add some text and save (as a test).  This happens in most directories.   If we put the log file in /tmp and do this, we don't run into the issue.  If we use other methods to modify the ("echo line >> file", nano as examples), we don't run into the issue.  We're using fluentd-bit v 0.11.11 on Linux systems

Thanks

**Comment by edsiper** [comment] 2017-06-29 20:58
is this appending data with vi or removing content and placing a new one ?

**Comment by wittenst** [comment] 2017-06-29 20:58
appending

**Comment by edsiper** [comment] 2017-06-29 21:07
Please switch to Emacs (just kidding)

I managed to reproduce the problem

**Comment by scottbuettner** [comment] 2017-06-29 21:08
I've been working with @wittenst on this, it appears (from the SQLite file) that the issue is related to vi's swap files, which are created with the same filename as the opened file, with a '~' suffix character. I attempted to get the Exclude_Path directive to exclude these files but was unsuccessful.

**Comment by edsiper** [comment] 2017-06-29 21:10
I was able to reproduce it without database file, it's an unhandled case due to Vi swapping files. A fix will be available shortly. Thanks for helping to catching this.

**Comment by edsiper** [comment] 2017-06-29 21:12
Inode changes between file editing:

```
$ stat vi.txt |grep Inode
Device: 804h/2052d	Inode: 19818637    Links: 1

$ vim vi.txt 
$ stat vi.txt |grep Inode
Device: 804h/2052d	Inode: 19818638    Links: 1

$ vim vi.txt 
$ stat vi.txt |grep Inode
Device: 804h/2052d	Inode: 19818637    Links: 1
```

**Comment by edsiper** [comment] 2017-06-30 05:21
@wittenst @scottbuettner I pushed a fix on 0.11 branch, would you please give it a try ?

**Comment by scottbuettner** [comment] 2017-06-30 13:52
Well, it isn't segfaulting anymore... but it's re-ingesting the entire file after vi saves it.

The vi swap file shows up in the sqlite db, is it perhaps reading lines from that, and that's why the whole file contents are re-emitted? IE the added line is read in from the correct file, and the original contents of the file are read in from the vi swap file (with the ~ suffix)?

**Comment by edsiper** [comment] 2017-06-30 14:26
The problem is that Vim is not suitable to test Fluent Bit or any other log collection tool. 

If you look at the database file, you will that Vi rename the files (rotate) and then it does a deletion every time some new content is saved. If you look at the inode numbers of that file you will see that a new file is being created every time, for hence Fluent Bit threat every filename with different inode number as a different file, so it read it from the beginning.

The best way to test adding lines to a file is using echo, e.g:

```
$ echo "first line" >> file.txt
$ echo "second line" >> file.txt
```

**Comment by edsiper** [comment] 2017-06-30 14:30
The patch have been merged into 0.11 and master (0.12), not longer an issue.

Fixed.

**Closed by edsiper** 2017-06-30 14:30 UTC
Labels: bug

**Comment by wittenst** [comment] 2017-06-30 19:52
It looks like I'm seeing a new issue in the 0.12 version

If I move a file and call it another name, we get a segmentation fault and the fluent-bit process stops:


[root@fluentdtest build]# bin/fluent-bit -c ~/fluent-0112.conf
Fluent-Bit v0.11.12
Copyright (C) Treasure Data

[2017/06/30 13:34:29] [ info] [engine] started
[0] tail.0: [1498851269, {"log"=>"This is a test from the 0.11.12 agent"}]
Segmentation fault

[root@fluentdtest tmp]# cat ~/fluent-0112.conf
[INPUT]
    Name tail
    Path /var/tmp/test-0112.log
    DB /var/tmp/test-0112.db

[OUTPUT]
    Name stdout
    Match *

I tested the move with the 0.11.11 agent, I did not see this problem

**Comment by edsiper** [comment] 2017-06-30 20:47
@wittenst last commit was incomplete. Recent one looks ok. Please pull the latest changes.

**Comment by wittenst** [comment] 2017-06-30 21:09
thanks, i'm not seeing the issue anymore

**Comment by edsiper** [comment] 2017-06-30 21:15
thanks for checking. I will release next version early next week.
