### ISSUE TITLE
kubernetes-filter results in wrong container- and pod-name

### ISSUE THREAD

**Issue by LarsKumbier** [fluent/fluent-bit#322] opened 2017-07-06 15:20 UTC
In our setup, we have several fluent-bit-containers with the kubernetes-filter active, which forward the messages to a fluentd-instance. For some reason, the `container_name` is wrong for only one specific container in 10% or the cases, in which the `container_name`, `pod_name`, and other kubernetes-data is set to the wrong pod.

Most messages' kubernetes metadata is correct, it's really just one container. However, this just stopped after being wrong for 2 days and stopped being wrong after redeploying the correct and wrong asserted pods.

A correct example:
```
## container_name
aurora-mobile

## kubernetes
{"pod_name":"aurora-mobile-green-2004576257-1djjk","namespace_name":"default","container_name":"aurora-mobile","docker_id":"8f4437d7d6ed9b4801a0e767c439343c8c3730e78d0b9f07d838bae60b241346","pod_id":"98bb3618-61db-11e7-b877-000d3ab14d57","labels":{"feature":"false","instance":"green","pod-template-hash":"2004576257","randomid":"0ada8f1b1fb6852352e09befb10852f0","service":"aurora-mobile"},"annotations":{"kubernetes.io/created-by":"{\\\"kind\\\":\\\"SerializedReference\\\",\\\"apiVersion\\\":\\\"v1\\\",\\\"reference\\\":{\\\"kind\\\":\\\"ReplicaSet\\\",\\\"namespace\\\":\\\"default\\\",\\\"name\\\":\\\"aurora-mobile-green-2004576257\\\",\\\"uid\\\":\\\"98b63035-61db-11e7-b877-000d3ab14d57\\\",\\\"apiVersion\\\":\\\"extensions\\\",\\\"resourceVersion\\\":\\\"415206\\\"}}\\n"}}

## tag
kube.node-logs.var.log.containers.aurora-mobile-green-2004576257-1djjk_default_aurora-mobile-8f4437d7d6ed9b4801a0e767c439343c8c3730e78d0b9f07d838bae60b241346.log
```

An incorrect example:
```
## container_name
aurora-mobile

## kubernetes
{"pod_name":"aurora-mobile-green-1324312572-45267","namespace_name":"default","container_name":"aurora-mobile","docker_id":"fd1961b1c7a06313ee41dd9290af3b3b4b5101b9d52bcc1163dda99885b91d0b","pod_id":"1b4f929b-608f-11e7-b877-000d3ab14d57","labels":{"feature":"false","instance":"green","pod-template-hash":"1324312572","randomid":"0ada8f1b1fb6852352e09befb10852f0","service":"aurora-mobile"},"annotations":{"kubernetes.io/created-by":"{\\\"kind\\\":\\\"SerializedReference\\\",\\\"apiVersion\\\":\\\"v1\\\",\\\"reference\\\":{\\\"kind\\\":\\\"ReplicaSet\\\",\\\"namespace\\\":\\\"default\\\",\\\"name\\\":\\\"aurora-mobile-green-1324312572\\\",\\\"uid\\\":\\\"1b4d4a82-608f-11e7-b877-000d3ab14d57\\\",\\\"apiVersion\\\":\\\"extensions\\\",\\\"resourceVersion\\\":\\\"42509\\\"}}\\n"}}

## tag
kube.node-logs.var.log.containers.crs-green-2504878274-xs6vj_default_crs-server-0c01943a5b445011dc002e2527e3e6464b8f303c6f7b3109da7aad3f3649183d.log
```

As can be seen from the tag, the container_name should be crs-server and not aurora-mobile.

**Comment by edsiper** [comment] 2017-07-07 22:03
@LarsKumbier in your cluster where Fluent Bit runs, do you have more than 256 pods ?

**Comment by edsiper** [comment] 2017-07-10 23:34
@LarsKumbier I've release v0.11.13 which comes with a fix (enhancement for collisions) in the hash table used by the filter.

Would you please test the image fluent/fluent-bit:0.11.13 ?

**Comment by edsiper** [comment] 2017-07-13 17:03
Since I cannot longer reproduce the problem with the last release [0.11.13](http://fluentbit.io/announcements/v0.11.13/) I am closing this issue. If you face it again, we can re-open it.

Fixed.

**Closed by edsiper** 2017-07-13 17:03 UTC
Labels: bug, fixed

**Comment by adinaclaudia** [comment] 2017-07-15 11:51
@edsiper Thanks a lot for the fix. 

I have tested v0.11.13 for some days and the bug does not seem to reproduce anymore. We don't have more than 256 pods, only about 60, but the issue was not reproducible all the time. That's why it's hard to assert it's fixed for good, but for now it looks fine. If we see it again, we'll write back.

**Comment by edsiper** [comment] 2017-07-15 20:04
@adinaclaudia thanks for testing the fix!
