### ISSUE TITLE
Elasticsearch error Illegal unquoted character 

### ISSUE THREAD

**Issue by FUSAKLA** [fluent/fluent-bit#338] opened 2017-07-27 11:14 UTC
Hi we get error when sending messages to elasticsearch containing ESC characters.
elasticsearch verison is 5.2.2
fluentbit version is 0.11.15

 The error from elasticsearch is:
```
{"index":{"_index":"logstash-2017.07.27","_type":"fluentd","_id":"AV2DZ50CSuzAFUyeAQND","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse [log]","caused_by":{"type":"i_o_exception","reason":"Illegal unquoted character ((CTRL-CHAR, code 27)): has to be escaped using backslash to be included in string value\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@2ba5aa1c; line: 1, column: 265]"}}}}
```

It's caused by this message:
```
{"_flb_time":"2017-07-27T07:36:36", "tag":"parser.noparse.cluster.kubernetes.var.log.containers.localeserver-2549321706-1x423_mapy-testing_localeserver-dbf15084a10c04345c63d92787ed4e73780e173dbd84472a6e096ace3139842e.log", "log":"2017/07/27 11:36:36 I1: [30155]: ESC[1;34mIESC[0m Creating base cursor {psqlwrapper.py:cursor():328}\n", "stream":"stderr", "container_id":"dbf15084a10c04345c63d92787ed4e73780e173dbd84472a6e096ace3139842e", "container_name":"localeserver", "pod_name":"localeserver-2549321706-1x423", "host":"skube-w03.dev", "app_name":"localeserver", "namespace_name":"mapy-testing", "cluster":"kubernetes", "log_format":"noparse", "@timestamp":"2017-07-27T09:36:36.657784564Z"}
{"index":{"_index":"logstash-2017.07.27","_type":"fluentd"}}
```

The probable cause is this part `ESC[1;34mIESC[0m` which should by color signature i think.

Maybe there is problem with escaping message sent to elasticsearch?

**Comment by FUSAKLA** [comment] 2017-07-27 11:17
@dohnto @FuFikCZ

**Comment by edsiper** [comment] 2017-07-27 16:41
I will check it, checking on jsonlint.com the following entry looks valid:

```json
{
	"_flb_time": "2017-07-27T07:36:36",
	"tag": "parser.noparse.cluster.kubernetes.var.log.containers.localeserver-2549321706-1x423_mapy-testing_localeserver-dbf15084a10c04345c63d92787ed4e73780e173dbd84472a6e096ace3139842e.log",
	"log": "2017/07/27 11:36:36 I1: [30155]: ESC[1;34mIESC[0m Creating base cursor {psqlwrapper.py:cursor():328}\n",
	"stream": "stderr",
	"container_id": "dbf15084a10c04345c63d92787ed4e73780e173dbd84472a6e096ace3139842e",
	"container_name": "localeserver",
	"pod_name": "localeserver-2549321706-1x423",
	"host": "skube-w03.dev",
	"app_name": "localeserver",
	"namespace_name": "mapy-testing",
	"cluster": "kubernetes",
	"log_format": "noparse",
	"@timestamp": "2017-07-27T09:36:36.657784564Z"
}
```

**Comment by edsiper** [comment] 2017-07-27 17:17
@FUSAKLA 

I tested here with Fluent Bit 0.12 and 0.11.15 and no issues. My Elasticserach is 5.4.0:

```json
{"took":164,"errors":false,"items":[{"index":{"_index":"fluent-bit","_type":"flb_type","_id":"AV2FBySUIvJ-PXwvAAyB","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"created":true,"status":201}}]}
```

on elastic side:

```json
      {
        "_index" : "logstash-2017.07.27",
        "_type" : "flb_type",
        "_id" : "AV2FDTLOIvJ-PXwvAAyQ",
        "_score" : 1.0,
        "_source" : {
          "@timestamp" : "2017-07-27T17:17:00Z",
          "_flb_time" : "2017-07-27T07:36:36",
          "tag" : "parser.noparse.cluster.kubernetes.var.log.containers.localeserver-2549321706-1x423_mapy-testing_localeserver-dbf15084a10c04345c63d92787ed4e73780e173dbd84472a6e096ace3139842e.log",
          "log" : "2017/07/27 11:36:36 I1: [30155]: ESC[1;34mIESC[0m Creating base cursor {psqlwrapper.py:cursor():328}\n",
          "stream" : "stderr",
          "container_id" : "dbf15084a10c04345c63d92787ed4e73780e173dbd84472a6e096ace3139842e",
          "container_name" : "localeserver",
          "pod_name" : "localeserver-2549321706-1x423",
          "host" : "skube-w03.dev",
          "app_name" : "localeserver",
          "namespace_name" : "mapy-testing",
          "cluster" : "kubernetes",
          "log_format" : "noparse",
          "@timestamp" : "2017-07-27T09:36:36.657784564Z"
        }
```

**Comment by dohnto** [comment] 2017-07-28 06:03
@edsiper Thanks for looking at this. Have you replaced the ESC with appropriate character?
I have uploaded the original json (with real escape character) to https://uploadfiles.io/y6eza (sorry for such a solution, but I dont know how to paste it to any well known pastebin like solution).

As an alternative, you can use base64 to decode the file:
```bash
# what I did to encode it
$ cat github.txt | base64
eyJfZmxiX3RpbWUiOiIyMDE3LTA3LTI3VDA3OjM2OjI2IiwgInRhZyI6InBhcnNlci5ub3BhcnNl
LmNsdXN0ZXIua3ViZXJuZXRlcy52YXIubG9nLmNvbnRhaW5lcnMubG9jYWxlc2VydmVyLTI1NDkz
MjE3MDYtMXg0MjNfZGJmMTUwODRhMTBjMDQzNDVjNjNkOTI3ODdlZDRlNzM3ODBlMTczZGJkODQ0
NzJhNmUwOTZhY2UzMTM5ODQyZS5sb2ciLCAibG9nIjoiMjAxNy8wNy8yNyAxMTozNjoyNiBJMTog
WzMwNDYyXTogG1sxOzM0bUkbWzBtIENyZWF0aW5nIGJhc2UgY3Vyc29yIHtwc3Fsd3JhcHBlci5w
eTpjdXJzb3IoKTozMjh9XG4iLCAic3RyZWFtIjoic3RkZXJyIiwgImNsdXN0ZXIiOiJrdWJlcm5l
dGVzIiwgImxvZ19mb3JtYXQiOiJub3BhcnNlIiwgIkB0aW1lc3RhbXAiOiIyMDE3LTA3LTI3VDA5
OjM2OjI2LjY0MTgzNzA0M1oifQo=
```

Just use `base64 -d` to decode it.

**Comment by edsiper** [comment] 2017-07-28 21:15
@dohnto I've pushed a fix into GIT Master (fluent/fluent-bit:0.12-dev is building). The fix format the special characters to UTF-8 string for JSON.

note: still doing more tests.

**Comment by FUSAKLA** [comment] 2017-07-31 07:25
It looks OK but we are trying it on the `0.12-dev` branch and we are getting loads of other errors.
I'm not sure in what state the branch is against the `0.11` or from which the stable docker image is built.

Are you planning to release some `0.11.*` version with this fix or do you plan releasing it in `0.12` version?

**Comment by edsiper** [comment] 2017-07-31 13:51
II am working in a fix for the root cause of the problem: missing utf-8 decoding to unicode codepoints when converting to JSON.

The solution will be available on git master (0.12) and also backported to 0.11

**Comment by edsiper** [comment] 2017-07-31 23:17
@FUSAKLA @dohnto 

I've pushed the required fixes to git master (0.12), would you please do some extra checks on your side ?

note: fluent/fluent-bit:0.12-dev has been updated.

**Comment by FUSAKLA** [comment] 2017-08-01 10:26
So.. the fix still looks ok the same way as i wrote in previous message.
The certain message i reported is correctly escaped and displayed even in kibana.

The problem is we are troubleshooting some issues with mappings in elasticsearch so we have 
loads of other errors in fluent-bit logs, but one doesn't seem to be related and looks wierd.

```
[2017/08/01 10:23:19] [ warn] [engine] Task cannot be retried: task_id=0 thread_id=3 output=es.0
rors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors""took""errors"[out_flowcounter] [1501582982, {"counts":8641, "bytes":7785636, "counts/minute":144, "bytes/minute":129760 }]
```

Did you experience something similar?

**Comment by edsiper** [comment] 2017-08-01 16:30
@FUSAKLA I remember that I saw those errors once, cannot remember why. Do you have a way to reproduce it ?

**Comment by FUSAKLA** [comment] 2017-08-01 18:39
Yes it's more like we cannot avoid them. Unfotunatelly as i said we have more errors in the communication with elastic so it's hard to tell what is the cause.

The retry could imply some problem with the fix of logging elasticsearch errors and retrying on fail.
Maybe the only problem is log output with repeated `"errors""took"`.

As we discussed in the previous issue if the problem is persistent it will eventually end with the retry count exceed and than i suppose this is valid log? Just the message is wierd.

But that is just guess.

**Comment by edsiper** [comment] 2017-08-05 05:06
If retries are exceeded, the data is dropped. To avoid that situation you can set Retry_Limit False in the output section.

I am closing this ticket since the main problem have been addressed. If you have a reproducible case (or any hints about the weird errors), please let me know.

Fixed.

**Closed by edsiper** 2017-08-05 05:06 UTC
Labels: bug, fixed
