### ISSUE TITLE
chunk cannot be retried fluent-bit 2.2.0

### ISSUE THREAD

**Issue by ihabzee** [fluent/fluent-bit#8236] opened 2023-12-01 00:44 UTC
I started getting the same error after upgrading to version 2.2.0. below my configuration. 

```
[error] [engine] chunk '28-1701388503.990707058.flb' cannot be retried: task_id=0, input=tail.2 > output=stackdriver.0
[debug] [task] task_id=0 reached retry-attempts limit 1/1
[debug] [out flush] cb_destroy coro_id=1
[debug] [upstream] KA connection #148 to logging.googleapis.com:443 is now available
[debug] [upstream] KA connection #148 to logging.googleapis.com:443 has been assigned (recycled)
[debug] [output:stackdriver:stackdriver.0] task_id=0 assigned to thread #0
[ warn] [engine] failed to flush chunk '28-1701388503.990707058.flb', retry in 9 seconds: task_id=0, input=tail.2 > output=stackdriver.0 (out_id=0)
```

My current configuration: 

```
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     debug
        Daemon        off
        Parsers_File  parsers.conf
    @INCLUDE input-application.conf
    @INCLUDE output-gcp.conf
    # @INCLUDE filter-log.conf
  input-application.conf: |
    [INPUT]
        Name  tail
        Tag custom_tag.*
        Path  /var/log/apache/*.json
        Parser json
        Buffer_Max_Size 5MB
        Buffer_Chunk_Size 400k
  output-gcp.conf: |
    [OUTPUT]
        Name  stackdriver
        Match *
        resource  gce_instance
        severity_key  level
        labels_key    array
        tag_prefix    errors.
        k8s_cluster_name k8-cluster
        k8s_cluster_location us-west1
  parsers.conf: |
    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
```

**Comment by patrick-stephens** [comment] 2023-12-01 11:22
Please follow the issue template to capture all required information.

The default number of retries is 1 and it's hit that: https://docs.fluentbit.io/manual/administration/scheduling-and-retries#configuring-retries
```
[debug] [task] task_id=0 reached retry-attempts limit 1/1
```

I think the real issue is why it cannot send to stackdriver, retries is unrelated.

What version did you update from?
If you revert to that version does start working? To confirm it is not a rotated credential issue or something stuck in an old pod.
Can you verify the pod networking is still correct?

**Comment by patrick-stephens** [comment] 2023-12-01 11:23
This is possibly a duplicate of https://github.com/fluent/fluent-bit/issues/8188

**Closed** 2023-12-01 16:49 UTC
Labels: duplicate, waiting-for-user, status: waiting-for-triage
