### ISSUE TITLE
Memory leak in grep filter

### ISSUE THREAD

**Issue by tranchitella** [fluent/fluent-bit#796] opened 2018-09-25 18:37 UTC
## Bug Report

**Describe the bug**
The grep filter has a memory leak: the memory consumption of fluent-bit keeps growing when the grep filter is used.

**Your Environment**
* Version used: 0.14.3
* Configuration: kubernetes (using stable/fluent-bit helm chart)
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.11.3
* Server type and version: Ubuntu 16.04 LTS
* Filters and plugins: grep

**Comment by edsiper** [comment] 2018-09-25 18:38
@tranchitella thanks for reporting this problem.

would you please share your configuration file example and some data to reproduce the case ?

**Comment by tranchitella** [comment] 2018-09-25 19:05
The minimal config file we use to reproduce the problem in our k8s cluster:

```
    [SERVICE]
        Flush            1
        Daemon           Off
        Log_Level        info
        Parsers_File     parsers.conf
        ignore_older     600s

    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        Parser           docker
        Tag              kube.*
        Refresh_Interval 5
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On

    [FILTER]
        Name             kubernetes
        Match            kube.*
        Kube_URL         https://kubernetes.default.svc:443
        Kube_CA_File     /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File  /var/run/secrets/kubernetes.io/serviceaccount/token
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [FILTER]
        Name             grep
        Match            kube.*
        Regex            log \[TAG\]|rtpengine.*MOS

    [OUTPUT]
        Name             null
        Match            *
```

Tomorrow morning I'm trying to reproduce it outside k8s from command line.

**Comment by edsiper** [comment] 2018-10-02 18:29
please share some docker container log files (/var/log/containers/) that are associated to the issue.

**Comment by lewisheadden** [comment] 2018-10-04 00:41
I can confirm I am also seeing this with a similar Kubernetes setup (removing grep filter kept memory usage stable around 32M but otherwise would grow up to 1.5G). I will also try and get you some log files tomorrow or Friday.

**Comment by edsiper** [comment] 2018-10-05 00:53
thanks

**Comment by tantra35** [comment] 2018-10-10 21:21
We see the same situation for grep filter, but it seems that leak all filters

**Comment by tantra35** [comment] 2018-10-10 21:28
In our case increase of memory consumption about 4-5 MB at hour

![default](https://user-images.githubusercontent.com/1377084/46767093-99d4ac00-ccec-11e8-9e62-3663c099b8f2.png)

**Comment by tantra35** [comment] 2018-10-10 21:37
grep filter have potentional memleak when call `flb_regex_do`, in cases when this function return value > 0(in such case `struct flb_regex_search *result` may contain unfree pointer to  `result->region` allocated by `onig_region_new`), and try to fix this, but this doesn't help

**Comment by edsiper** [comment] 2018-10-10 23:36
Thanks everybody for the info and hints on this. I will dig on this during
the next week (on PTO)

**Comment by marcuslindfeldt** [comment] 2018-10-21 10:31
We are also seeing this issue with the grep filter when we exclude kube-probe logs. The pods get OOMKilled after a couple of hours.

```
[FILTER]
    Name grep
    Match kube.*
    Exclude log ^.*kube-probe.*$
```

**Comment by edsiper** [comment] 2018-10-24 12:28
@marcuslindfeldt I tried to repdocue locally without success, would you please share the kube-prob log that helps to trigger the problem?

**Comment by marcuslindfeldt** [comment] 2018-10-25 13:28
@edsiper I don't think this is related to specific logs. The kubernetes healthcheck probe checks all pods with specified readiness/liveness checks. My fluentbit pods have 200mb memory limits and they have restarted 50 times in 6 hours

**Comment by edsiper** [comment] 2018-10-25 13:35
Since I tried to reproduce locally without success and the memory leak is only reproducible with Grep filter, I need the logs to troubleshoot and find the condition/root_cause of the problem

**Comment by tantra35** [comment] 2018-10-27 11:45
@edsiper  I agree with @marcuslindfeldt memleak doens't related to any specific logs, also i must say that on logs that was provided memleak 100% reproducible. If needed, we can empirically localize place of leak by coment some peace of code and then recompile

**Comment by edsiper** [comment] 2018-10-29 02:39
@tantra35 thanks, I missed something in my previous setup, I can reproduce the issue!

**Comment by edsiper** [comment] 2018-10-29 04:13
Found the root cause of the problem:

If a filter remove __all__ the content of a dyntag buffer, it final size is zero and the engine skip the reference since there is nothing to process, but the context remain.

Issue fixed on 9fc067a1.

**Comment by tantra35** [comment] 2018-10-30 16:03
We just tested version with patch, and confirm that issue seems resolved

![default](https://user-images.githubusercontent.com/1377084/47732030-6c897700-dc76-11e8-915d-a4118c3c473d.png)

Thanks @edsiper

**Comment by edsiper** [comment] 2018-10-30 16:36
great, I will do a new release shortly (this week).

**Closed** 2018-10-31 03:10 UTC
Labels: bug, fixed
