### ISSUE TITLE
Azure output plugin not sending logs with HTTP Proxy environment variables

### ISSUE THREAD

**Issue by SanyaKochhar** [fluent/fluent-bit#2779] opened 2020-11-17 02:41 UTC
## Bug Report

**Describe the bug**

I have been running fluent bit as a sidecar container in my kubernetes pod with the Azure output plugin. I am trying to use the http/s proxy environment variable added in v1.6.4. I'm passing in the http proxy environment variables using a k8s secret and can see the env vars being set when I exec into the container but logs do not get sent to the log analytics instance. Response code 200 is not returned. (I have tested curl requests from another container successfully against the proxy)

**To Reproduce**
- Run fluent bit as a sidecar using tail input, grep (or any) filter, cri parser, Azure output plugin
- Define http proxy server host and port in a k8s secret
```
apiVersion: v1
kind: Secret
metadata:
  name: proxy-config
stringData:
  HTTP_PROXY: "http://<host>:<port>"
  HTTPS_PROXY: "http://<host>:<port>"
```
- Pass in the secret in the sidecar container spec:
```
          envFrom:
            - secretRef:
                name: proxy-config
```
- Deploy in a cluster with the proxy server

Container debug log output is as follows:

```[2020/11/16 23:25:19] [ info] Configuration:
[2020/11/16 23:25:19] [ info]  flush time     | 5.000000 seconds
[2020/11/16 23:25:19] [ info]  grace          | 5 seconds
[2020/11/16 23:25:19] [ info]  daemon         | 0
[2020/11/16 23:25:19] [ info] ___________
[2020/11/16 23:25:19] [ info]  inputs:
[2020/11/16 23:25:19] [ info]      tail
[2020/11/16 23:25:19] [ info] ___________
[2020/11/16 23:25:19] [ info]  filters:
[2020/11/16 23:25:19] [ info]      grep.0
[2020/11/16 23:25:19] [ info] ___________
[2020/11/16 23:25:19] [ info]  outputs:
[2020/11/16 23:25:19] [ info]      azure.0
[2020/11/16 23:25:19] [ info] ___________
[2020/11/16 23:25:19] [ info]  collectors:
[2020/11/16 23:25:19] [ info] [engine] started (pid=1)
[2020/11/16 23:25:19] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2020/11/16 23:25:19] [debug] [storage] [cio stream] new stream registered: tail.0
[2020/11/16 23:25:19] [ info] [storage] version=1.0.6, initializing...
[2020/11/16 23:25:19] [ info] [storage] in-memory
[2020/11/16 23:25:19] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/11/16 23:25:19] [debug] [input:tail:tail.0] inotify watch fd=24
[2020/11/16 23:25:19] [debug] [input:tail:tail.0] scanning path /var/log/containers/osm-controller-*_arc-osm-system_osm-controller-*.log
[2020/11/16 23:25:19] [debug] [input:tail:tail.0] inode=3102680 with offset=5323 appended as /var/log/containers/osm-controller-894445495-gl8rt_arc-osm-system_osm-controller-75b0e9546dba1a7c9dbd9318d8f90e5f23547189355ff682166554de09b51c09.log
[2020/11/16 23:25:19] [debug] [input:tail:tail.0] scan_glob add(): /var/log/containers/osm-controller-894445495-gl8rt_arc-osm-system_osm-controller-75b0e9546dba1a7c9dbd9318d8f90e5f23547189355ff682166554de09b51c09.log, inode 3102680
[2020/11/16 23:25:19] [debug] [input:tail:tail.0] 1 new files found on path '/var/log/containers/osm-controller-*_arc-osm-system_osm-controller-*.log'
[2020/11/16 23:25:19] [debug] [upstream] config->http_proxy: http://10.240.0.8:3128
[2020/11/16 23:25:19] [ info] [output:azure:azure.0] customer_id='redacted' host='redacted.ods.opinsights.azure.com:443'
[2020/11/16 23:25:19] [debug] [router] match rule tail.0:azure.0
[2020/11/16 23:25:19] [ info] [sp] stream processor started
[2020/11/16 23:25:19] [debug] [input:tail:tail.0] inode=3102680 file=/var/log/containers/osm-controller-894445495-gl8rt_arc-osm-system_osm-controller-75b0e9546dba1a7c9dbd9318d8f90e5f23547189355ff682166554de09b51c09.log promote to TAIL_EVENT
[2020/11/16 23:25:19] [ info] [input:tail:tail.0] inotify_fs_add(): inode=3102680 watch_fd=1 name=/var/log/containers/osm-controller-894445495-gl8rt_arc-osm-system_osm-controller-75b0e9546dba1a7c9dbd9318d8f90e5f23547189355ff682166554de09b51c09.log
[2020/11/16 23:25:21] [debug] [input:tail:tail.0] inode=3102680 events: IN_MODIFY 
[2020/11/16 23:25:21] [debug] [input:tail:tail.0] inode=3102680 events: IN_MODIFY 
[2020/11/16 23:25:21] [debug] [input:tail:tail.0] inode=3102680 events: IN_MODIFY
```

**Expected behavior**

Logs should be sent to Log Analytics workspace. Running `kubectl logs` on the fluent bit container should return status 200 for each message sent. On inspection, proxy server logs should show requests being made. I am not sure whether this is a bug or an issue with my configuration.

**Your Environment**

* Version used: 1.6.4-debug
* Configuration/Input/Filter/Parser/Output: 
```    
    [SERVICE]
      Flush             5
      Daemon            off
      Log_Level         debug
      Parsers_File      parser.conf
    [INPUT]
      Name    tail
      Tag     kube.*
      Path    /var/log/containers/osm-controller-*_{{.Values.OpenServiceMesh.namespace}}_osm-controller-*.log
      Parser  cri
    [FILTER]
      name       grep
      match      *
      regex      message /"level":"trace"/
    [OUTPUT]
      Name        azure
      Match       *
      Customer_ID <Log Analytics workspace ID>
      Shared_Key  <Log Analytics primary key>
```
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes
* Server type and version: Squid proxy server
* Operating System and version: WSL2

**Additional context**

I am trying to make this service capable of supporting outbound proxy. I have tested this successfully without a proxy server and can see logs being sent to Azure, however once I deploy the pod in a cluster that has a proxy, messages are no longer sent. The container logs outputs `stream processor started` but does not show logs being sent thereafter.

**Comment by SanyaKochhar** [comment] 2020-11-17 02:41
cc/ @erain have you seen anything like this while testing http proxy envm vars?

**Comment by edsiper** [comment] 2020-11-17 03:07
@SanyaKochhar is this a kind of known Proxy service that can be used for local testing ?

**Comment by SanyaKochhar** [comment] 2020-11-17 17:38
@edsiper I'm using Squid proxy on an Azure VM and deploying the container on an AKS cluster with the same vnet and subnet as the VM

**Comment by edsiper** [comment] 2020-11-17 22:26
@erain do you know if the feature is compatible with Squid ?

**Comment by SanyaKochhar** [comment] 2020-11-17 22:47
On looking into this further, it seems to work when I comment out the grep filter that I am using to filter on log level. Not sure why but I'm still looking for a fix

**Comment by erain** [comment] 2020-11-18 14:37
@edsiper I _THINK_ the feature is compatible with Squid, and that is a common setup in our use case. 

@SanyaKochhar it is strange that grep filter would impact http proxy. Could you attach some Squid logs when it is working / not working?

**Comment by SanyaKochhar** [comment] 2020-11-18 17:16
@erain yeah I am not sure why. I tried changing the grep regex and that didn't help trying to find a wildcard regex just to make sure. I've also tried it with the stdout and modify filters and it works with those. 

Here are logs of when grep filter is used and messages aren't sent:
```
[2020/11/18 00:07:19] [ info] Configuration:
[2020/11/18 00:07:19] [ info]  flush time     | 5.000000 seconds
[2020/11/18 00:07:19] [ info]  grace          | 5 seconds
[2020/11/18 00:07:19] [ info]  daemon         | 0
[2020/11/18 00:07:19] [ info] ___________
[2020/11/18 00:07:19] [ info]  inputs:
[2020/11/18 00:07:19] [ info]      tail
[2020/11/18 00:07:19] [ info] ___________
[2020/11/18 00:07:19] [ info]  filters:
[2020/11/18 00:07:19] [ info]      grep.0
[2020/11/18 00:07:19] [ info] ___________
[2020/11/18 00:07:19] [ info]  outputs:
[2020/11/18 00:07:19] [ info]      azure.0
[2020/11/18 00:07:19] [ info] ___________
[2020/11/18 00:07:19] [ info]  collectors:
[2020/11/18 00:07:19] [ info] [engine] started (pid=1)
[2020/11/18 00:07:19] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2020/11/18 00:07:19] [debug] [storage] [cio stream] new stream registered: tail.0
[2020/11/18 00:07:19] [ info] [storage] version=1.0.6, initializing...
[2020/11/18 00:07:19] [ info] [storage] in-memory
[2020/11/18 00:07:19] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/11/18 00:07:19] [debug] [input:tail:tail.0] inotify watch fd=24
[2020/11/18 00:07:19] [debug] [input:tail:tail.0] scanning path /var/log/containers/osm-controller-*_arc-osm-system_osm-controller-*.log
[2020/11/18 00:07:19] [debug] [input:tail:tail.0] inode=3358595 with offset=5005 appended as /var/log/containers/osm-controller-894445495-795pb_arc-osm-system_osm-controller-b2771be46f00b491486390b8aa2b2b55a3bc01e05a90366aa1563277c8fafd5a.log
[2020/11/18 00:07:19] [debug] [input:tail:tail.0] scan_glob add(): /var/log/containers/osm-controller-894445495-795pb_arc-osm-system_osm-controller-b2771be46f00b491486390b8aa2b2b55a3bc01e05a90366aa1563277c8fafd5a.log, inode 3358595
[2020/11/18 00:07:19] [debug] [input:tail:tail.0] 1 new files found on path '/var/log/containers/osm-controller-*_arc-osm-system_osm-controller-*.log'
[2020/11/18 00:07:19] [debug] [upstream] config->http_proxy: http://10.240.0.8:3128
[2020/11/18 00:07:19] [ info] [output:azure:azure.0] customer_id='<redacted>' host='<redacted>.ods.opinsights.azure.com:443'
[2020/11/18 00:07:19] [debug] [router] match rule tail.0:azure.0
[2020/11/18 00:07:19] [ info] [sp] stream processor started
[2020/11/18 00:07:19] [debug] [input:tail:tail.0] inode=3358595 file=/var/log/containers/osm-controller-894445495-795pb_arc-osm-system_osm-controller-b2771be46f00b491486390b8aa2b2b55a3bc01e05a90366aa1563277c8fafd5a.log promote to TAIL_EVENT
[2020/11/18 00:07:19] [ info] [input:tail:tail.0] inotify_fs_add(): inode=3358595 watch_fd=1 name=/var/log/containers/osm-controller-894445495-795pb_arc-osm-system_osm-controller-b2771be46f00b491486390b8aa2b2b55a3bc01e05a90366aa1563277c8fafd5a.log
[2020/11/18 00:07:19] [debug] [input:tail:tail.0] inode=3358595 events: IN_MODIFY
[2020/11/18 00:07:19] [debug] [input:tail:tail.0] inode=3358595 events: IN_MODIFY
[2020/11/18 00:07:19] [debug] [input:tail:tail.0] inode=3358595 events: IN_MODIFY
[2020/11/18 00:07:19] [debug] [input:tail:tail.0] inode=3358595 events: IN_MODIFY
[2020/11/18 00:07:19] [debug] [input:tail:tail.0] inode=3358595 events: IN_MODIFY
[2020/11/18 00:07:19] [debug] [input:tail:tail.0] inode=3358595 events: IN_MODIFY
[2020/11/18 00:07:19] [debug] [input:tail:tail.0] inode=3358595 events: IN_MODIFY
[2020/11/18 00:07:19] [debug] [input:tail:tail.0] inode=3358595 events: IN_MODIFY
[2020/11/18 00:07:19] [debug] [input:tail:tail.0] inode=3358595 events: IN_MODIFY
[2020/11/18 00:07:19] [debug] [input:tail:tail.0] inode=3358595 events: IN_MODIFY
[2020/11/18 00:07:19] [debug] [input:tail:tail.0] inode=3358595 events: IN_MODIFY
[2020/11/18 00:07:19] [debug] [input:tail:tail.0] inode=3358595 events: IN_MODIFY
[...]
```

Here are logs of when it is not used and messages are successfully sent:
```
[2020/11/18 16:51:57] [ info] Configuration:
[2020/11/18 16:51:57] [ info]  flush time     | 5.000000 seconds
[2020/11/18 16:51:57] [ info]  grace          | 5 seconds
[2020/11/18 16:51:57] [ info]  daemon         | 0
[2020/11/18 16:51:57] [ info] ___________
[2020/11/18 16:51:57] [ info]  inputs:
[2020/11/18 16:51:57] [ info]      tail
[2020/11/18 16:51:57] [ info] ___________
[2020/11/18 16:51:57] [ info]  filters:
[2020/11/18 16:51:57] [ info] ___________
[2020/11/18 16:51:57] [ info]  outputs:
[2020/11/18 16:51:57] [ info]      azure.0
[2020/11/18 16:51:57] [ info] ___________
[2020/11/18 16:51:57] [ info]  collectors:
[2020/11/18 16:51:57] [ info] [engine] started (pid=1)
[2020/11/18 16:51:57] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2020/11/18 16:51:57] [debug] [storage] [cio stream] new stream registered: tail.0
[2020/11/18 16:51:57] [ info] [storage] version=1.0.6, initializing...
[2020/11/18 16:51:57] [ info] [storage] in-memory
[2020/11/18 16:51:57] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/11/18 16:51:57] [debug] [input:tail:tail.0] inotify watch fd=24
[2020/11/18 16:51:57] [debug] [input:tail:tail.0] scanning path /var/log/containers/osm-controller-*_arc-osm-system_osm-controller-*.log
[2020/11/18 16:51:57] [debug] [input:tail:tail.0] inode=3103915 with offset=5321 appended as /var/log/containers/osm-controller-894445495-cc6d2_arc-osm-system_osm-controller-9035067f4ac64c61f3333f4c32f53542a1d04403d6c3b90c68104ee5bc09b7a5.log
[2020/11/18 16:51:57] [debug] [input:tail:tail.0] scan_glob add(): /var/log/containers/osm-controller-894445495-cc6d2_arc-osm-system_osm-controller-9035067f4ac64c61f3333f4c32f53542a1d04403d6c3b90c68104ee5bc09b7a5.log, inode 3103915
[2020/11/18 16:51:57] [debug] [input:tail:tail.0] 1 new files found on path '/var/log/containers/osm-controller-*_arc-osm-system_osm-controller-*.log'
[2020/11/18 16:51:57] [debug] [upstream] config->http_proxy: http://10.240.0.8:3128
[2020/11/18 16:51:57] [ info] [output:azure:azure.0] customer_id='<redacted>' host='<redacted>.ods.opinsights.azure.com:443'
[2020/11/18 16:51:57] [debug] [router] match rule tail.0:azure.0
[2020/11/18 16:51:57] [ info] [sp] stream processor started
[2020/11/18 16:51:57] [debug] [input:tail:tail.0] inode=3103915 file=/var/log/containers/osm-controller-894445495-cc6d2_arc-osm-system_osm-controller-9035067f4ac64c61f3333f4c32f53542a1d04403d6c3b90c68104ee5bc09b7a5.log promote to TAIL_EVENT
[2020/11/18 16:51:57] [ info] [input:tail:tail.0] inotify_fs_add(): inode=3103915 watch_fd=1 name=/var/log/containers/osm-controller-894445495-cc6d2_arc-osm-system_osm-controller-9035067f4ac64c61f3333f4c32f53542a1d04403d6c3b90c68104ee5bc09b7a5.log
[2020/11/18 16:51:58] [debug] [input:tail:tail.0] inode=3103915 events: IN_MODIFY
[2020/11/18 16:51:58] [debug] [input:tail:tail.0] inode=3103915 events: IN_MODIFY
[2020/11/18 16:51:58] [debug] [input:tail:tail.0] inode=3103915 events: IN_MODIFY
[2020/11/18 16:51:58] [debug] [input:tail:tail.0] inode=3103915 events: IN_MODIFY
[2020/11/18 16:52:00] [debug] [input:tail:tail.0] inode=3103915 events: IN_MODIFY
[2020/11/18 16:52:00] [debug] [input:tail:tail.0] inode=3103915 events: IN_MODIFY
[2020/11/18 16:52:00] [debug] [input:tail:tail.0] inode=3103915 events: IN_MODIFY
[2020/11/18 16:52:02] [debug] [task] created task=0x7f3542a525a0 id=0 OK
[2020/11/18 16:52:02] [debug] [upstream] establishing http tunneling to proxy: host 10.240.0.8 port 3128
[2020/11/18 16:52:02] [debug] [http_client] using HTTP CONNECT for proxy: proxy host <redacted>.ods.opinsights.azure.com, proxy port 443
[2020/11/18 16:52:02] [debug] [http_client] header=CONNECT <redacted>.ods.opinsights.azure.com:443 HTTP/1.1
Proxy-Connection: KeepAlive
Host: <redacted>.ods.opinsights.azure.com
Content-Length: 0
User-Agent: Fluent-Bit


[2020/11/18 16:52:02] [debug] [upstream] proxy returned 200
[2020/11/18 16:52:02] [debug] [http_client] flb_http_client_proxy_connect connection #33 connected to 10.240.0.8:3128.
[2020/11/18 16:52:02] [debug] [http_client] not using http_proxy for header
[2020/11/18 16:52:02] [debug] [http_client] header=POST /api/logs?api-version=2016-04-01 HTTP/1.1
Host: <redacted>.ods.opinsights.azure.com
Content-Length: 12456
User-Agent: Fluent-Bit
Log-Type: fluentbit
Content-Type: application/json
x-ms-date: Wed, 18 Nov 2020 16:52:02 GMT
Authorization: SharedKey <redacted>


[2020/11/18 16:52:02] [ info] [output:azure:azure.0] customer_id=<redacted>, HTTP status=200
[2020/11/18 16:52:02] [debug] [upstream] KA connection #33 to 10.240.0.8:3128 is now available
[2020/11/18 16:52:02] [debug] [task] destroy task=0x7f3542a525a0 (task_id=0)
[2020/11/18 16:52:03] [debug] [input:tail:tail.0] inode=3103915 events: IN_MODIFY
[2020/11/18 16:52:04] [debug] [input:tail:tail.0] inode=3103915 events: IN_MODIFY
[2020/11/18 16:52:04] [debug] [input:tail:tail.0] inode=3103915 events: IN_MODIFY
[2020/11/18 16:52:07] [debug] [task] created task=0x7f3542a52640 id=0 OK
[2020/11/18 16:52:07] [debug] [upstream] KA connection #33 is in a failed state to: 10.240.0.8:3128, cleaning up
[2020/11/18 16:52:07] [debug] [upstream] establishing http tunneling to proxy: host 10.240.0.8 port 3128
[2020/11/18 16:52:07] [debug] [http_client] using HTTP CONNECT for proxy: proxy host <redacted>.ods.opinsights.azure.com, proxy port 443
[2020/11/18 16:52:07] [debug] [http_client] header=CONNECT <redacted>.ods.opinsights.azure.com:443 HTTP/1.1
Proxy-Connection: KeepAlive
Host: <redacted>.ods.opinsights.azure.com
Content-Length: 0
User-Agent: Fluent-Bit

[... repeats for each message sent]
```

**Comment by SanyaKochhar** [comment] 2020-11-18 23:40
I have been able to get it working for now. The proxy was run on an AKS cluster which outputs its logs in a slightly different format than the no proxy environment (kind cluster) that I had originally tested this regex on. I'm not sure why this did not generate an error message like some of the other faulty regexes I tried did, but it seems to work by changing the regex to `$log['log']['level'] trace`. 

Is there a way to set up parser and filter regexes to be able to handle differing log formats on different k8s distros?

**Comment by erain** [comment] 2020-11-19 13:51
So it looks like the problem is not with the proxy, it was with the regex you used which filter out ALL of your logs. 

I don't think there is a "fit-all" regex for your purpose (and TBH everyone's needs are different for regex), so the best approach is to test and check in your own environment.

But I think we can close this issue.

**Comment by edsiper** [comment] 2020-11-24 23:19
@SanyaKochhar you can set up as many filters you want in the pipeline, same as many inputs and outputs. For custom inquiries about your use case let's open a different ticket.

thanks @erain for your assistance!, closing this ticket.

**Closed by edsiper** 2020-11-24 23:19 UTC
