### ISSUE TITLE
fluent-bit crashes with SIGSEGV in template_execute()

### ISSUE THREAD

**Issue by beckjim** [fluent/fluent-bit#1734] opened 2019-11-13 12:52 UTC
## Bug Report

**Describe the bug**
fluent-bit 1.3.2 crashes with SIGSEV, when forward target host becomes unresponsive.
This happens only with storage.type=filesystem and Retry_Limit=False.

Please note the number of bytes to flash before the crash: 140TB 

Stacktrace
```
[engine] caught signal (SIGSEGV)  
[2019/11/13 11:30:53] [debug] [out_forward] request 140736115963728 bytes to flush
#0  0x55650f1b61c6      in  template_execute() at lib/msgpack-3.2.0/include/msgpack
unpack_template.h:172  
#1  0x55650f1b7cb8      in  msgpack_unpack_next() at lib/msgpack-3.2.0/src/unpack.c:677  
#2  0x55650eeb195c      in  data_compose() at plugins/out_forward/forward.c:890  
#3  0x55650eeb1c33      in  cb_forward_flush() at plugins/out_forward/forward.c:990  
#4  0x55650ee62f2d      in  output_pre_cb_flush() at include/fluent-bit/flb_output.h:315   
#5  0x55650f1d1c86      in  co_init() at lib/monkey/deps/flb_libco/amd64.c:117   
#6  0xffffffffffffffff  in  ???() at ???:0    
```

**To Reproduce**
- use configuration below with an unreachable forward host (mine returns connection refused)
- Steps to reproduce the problem:
-- create a namespace containing a single test container (fluent-bit is running in different namesapce). In my case the namespace is called 'kai2-0poc'
-- start the test container producing fast test output with `while true; do date; sleep 0.05; done`
-- start fluent-bit
-- wait a few minutes (2-3 minutes in my environment)
-- fluent-bit crashes as described

**Expected behavior**
No crash. 
With Retry_Limit=False I would have expected that with 
`storage.backlog.mem_limit=1MB` and `storage.type=filesystem` events get buffered on disk until the (disk usage) limit of 1MB is reached.
In Production of course I'd like to buffer some GBs (not just 1MB) of logs in case they can't be shipped.
In fact, the storage path already contains ~14MB of data just before the crash.

**Screenshots**
n/a

**Your Environment**

* Version used: 
official docker image fluent/fluent-bit:1.3.2-debug (but also crashes with edsiper/fluent-bit-1.3.3-next:3)

* Configuration:
```
@SET DBPATH=/fb
@SET STORAGE_PATH=/fb/spool
@SET STORAGE_BACKLOG_MEM_LIMIT=1M
@SET MEM_BUF_LIMIT=1M

[SERVICE]
    Parsers_File   parsers.conf
    Flush          5
    Grace          5
    Daemon         Off
    Log_Level      debug
    storage.path   ${STORAGE_PATH}
    storage.backlog.mem_limit  ${STORAGE_BACKLOG_MEM_LIMIT}

[INPUT]
    Name              tail
    Alias             input.kai2-0poc
    Buffer_Max_Size   128KB
    Buffer_Chunk_Size 32KB
    storage.type      filesystem
    Tag               kube.<namespace_name>.<pod_name>.<container_name>
    Tag_Regex         (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
    Path              /var/log/containers/*_kai2-0poc_*-*.log
    Refresh_Interval  10
    Skip_Long_Lines   On
    Mem_Buf_Limit     ${MEM_BUF_LIMIT}
    DB                ${DBPATH}/kai2-0poc.db
    Docker_Mode       On

[OUTPUT]
    Name           forward
    Alias          output.kai2-0poc
    Match          kube.kai2-0poc.**
    Host           1.2.3.4
    Port           24225
    tls            On
    tls.ca_path    /fluent-bit/certs/
    Retry_Limit    False
```

parsers.conf
```
[PARSER]
    Name        docker
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
    Time_Keep   On
```

* Environment name and version (e.g. Kubernetes? What version?): 
-- Openshift 3.9, i.e. Kubernetes 1.9
-- Fluent-Bit running as daemonset, configured for forwarding container logs
--- /var/log & /var/lib/docker/containers are mounted from host
--- pod has 250MB of memory
* Server type and version: n/a
* Operating System and version: 
`Linux fluent-bit-nc497 3.10.0-1062.4.1.el7.x86_64 #1 SMP Wed Sep 25 09:42:57 EDT 2019 x86_64 GNU/Linux`
* Filters and plugins: n/a

**Additional context**
For reproducing the issue, I removed all filters, e.g. kubernetes.
I tested the same setup with Elasticsearch output (instead of Forward), but couldn't reproduce the crash.
With `storage.type=memory` everything works as expected.

Thank you!

**Comment by edsiper** [comment] 2019-11-13 21:50
thanks for reporting this issue.

I was able to reproduce it outside of Kubernetes. The problem is located when retrying chunks that cannot be up in memory due to memory restrictions.

Working in a fix.

**Comment by beckjim** [comment] 2019-11-14 06:28
Thanks for your quick and comprehensive feedback!
Looking forward to test a fix once it is available ...

**Comment by edsiper** [comment] 2019-11-20 07:25
Fixed by:

- 0c32b9f8
- 7f771e98

**Closed** 2019-11-20 07:25 UTC
Labels: bug, fixed

**Comment by epsteina16** [comment] 2024-04-01 14:27
A relatively recent change https://github.com/fluent/fluent-bit/commit/d73ff32a3c6e499a15168abc62e0d26c826bdc86 undid https://github.com/fluent/fluent-bit/commit/0c32b9f8dd976aa501618f0a542b555cbda1a45b which fixed this issue. As such, there is a regression in recent releases of Fluent Bit. I ran into this issue in Fluent Bit 2.2.1.

**Comment by hjampala** [comment] 2025-06-02 07:56
Issue is still seen in the Fluent Bit 2.2.1, may I know if this is being tracked by any other issue ?
