### ISSUE TITLE
Espaced newlines in JSON formatted logs are being escaped twice

### ISSUE THREAD

**Issue by ThorstenKunz** [fluent/fluent-bit#530] opened 2018-03-08 08:53 UTC
We are logging JSON to our container consoles. If we have multiline log entries the newlines are properly escaped by our application logger: { "stacktrace": "line1\nline2\line3\n" }

Looking at what is being set to our ElasticSearch cluster by fluentbit it seems the backslashes are being escaped once more: { "stacktrace": "line1\\\nline2\\\line3\\\n" }
This means in Kibana it doesn't format the stacktracke properly but displays "line1\nline2\line3\n" instead for the field.

**Comment by sestrel** [comment] 2018-03-12 19:41
I described more or less the same issue here #523 

I closed my issue hence I'm not sure if the function I identified is the real root cause and because I found this new fluent-bit feature for 0.13 http://fluentbit.io/documentation/0.13/parser/decoder.html 
Unfortunately I had to open a new issue #534 because the new functionality doesn't fit the idea it has been introduced for, or at least doesn't fit the use case for merging escaped json within json logs written by the docker containers.

**Comment by ThorstenKunz** [comment] 2018-03-16 21:58
@sestrel your issue documented in #523 is slightly difference. What happend in our case is that if the output of a console logger is a properly escaped JSON string then some part of fluentbit is escaping the backslashes use to escape the newline again and thus effectively turning them into a regular '\' as opposed to an escape sequence '\n'.

**Comment by edsiper** [comment] 2018-03-23 21:10
This problem have a workaround with the new Parser Decoder feature and improved Kubernetes Filter, please refer to the latest updates on this repository:

https://github.com/fluent/fluent-bit-kubernetes-logging/tree/0.13-dev

**Comment by edsiper** [comment] 2018-03-23 21:11
Closing this issue, if you still face a similar problem we can re-open this one.

**Closed by edsiper** 2018-03-23 21:11 UTC
Labels: bug, fixed
