### ISSUE TITLE
Fluentbit service start error Windows Error 1067

### ISSUE THREAD

**Issue by dauchande** [fluent/fluent-bit#5615] opened 2022-06-22 18:35 UTC
From a clean install of fluentbit v1.9.4 on Windows 10, I was getting an error 1067 - Service terminated unexpectedly.

It turned out to be that the ImagePath set for the config file was C:\program files\fluent-bit\bin\fluent-bit.exe -c C:\program files\fluent-bit\conf\fluent-bit.conf.

Debugged it and the config file passed to main was "C:\program".

Adding quotes around the config file fixed the issue for me.

Additional: This is with Windows installer version 1.9.4 and the default installation to Windows 10 Pro (19044.1706)

**Comment by patrick-stephens** [comment] 2022-06-23 09:54
Related: https://docs.fluentbit.io/manual/installation/windows#faq-fluent-bit-fails-to-start-up-when-installed-under-c-program-files

Ideally it should be resolved though if possible.

**Comment by patrick-stephens** [comment] 2022-06-23 12:50
Tracking as a duplicate of #5519 as it was first plus has some other info.

**Closed by patrick-stephens** 2022-06-23 12:50 UTC
Labels: packaging
