### ISSUE TITLE
Don't use `$<` to set `__FILENAME__` in `CMakeFiles.txt`.

### ISSUE THREAD

**Issue by igorpeshansky** [fluent/fluent-bit#5492] opened 2022-05-24 21:38 UTC
## Bug Report

**Describe the bug**
Due to a [change in CMake 3.20](https://discourse.cmake.org/t/base-filename-gets-set-to-compiler-depend-ts-after-update-to-cmake-3-20/3075/3), using `$<` to set `__FILENAME__` ends up with `__FILENAME__` being set to `compiler_depends.ts`, resulting in log messages that mention that file instead of the correct source file, for example:
```
[2022/05/04 06:09:59] [error] [build/plugins/in_tail/CMakeFiles/flb-plugin-in_tail.dir/compiler_depend.ts:139 errno=2] No such file or directory
```

**To Reproduce**
- Steps to reproduce the problem:
  - Build fluent-bit with CMake 3.20 or later.
  - Set up `in_tail` to watch a log file, and force (or wait for) log rotation.

**Expected behavior**
The log message contains the correct filename (in this case, `tail_fs_inotify.c`).

**Your Environment**
* Version used: 1.8.12 (but the bug is present in HEAD as well)
* Operating System and version: Debian 10 Linux
* Filters and plugins: `in_tail`

**Additional context**
Suggested fix:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a07b235aa..6e51244fe 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -46,11 +46,7 @@ else()
   set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall")
 endif()
 
-if(NOT ${CMAKE_SYSTEM_NAME} MATCHES "Windows")
-  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D__FILENAME__='\"$(subst ${CMAKE_SOURCE_DIR}/,,$(abspath $<))\"'")
-else()
-  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D__FILENAME__=__FILE__")
-endif()
+set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D__FILENAME__=__FILE__")
 
 if(${CMAKE_SYSTEM_PROCESSOR} MATCHES "armv7l")
   set(CMAKE_C_LINK_FLAGS "${CMAKE_C_LINK_FLAGS} -latomic")
```

**Comment by patrick-stephens** [comment] 2022-05-25 08:58
@igorpeshansky is this change backwards compatible as well? Can you submit a PR and I'll get it merged if so?

We just need to make sure some of the older targets (and their older cmakes - looking at you CentOS 7!) carry on building ok.

**Comment by patrick-stephens** [comment] 2022-05-25 09:00
And thanks for noticing this, I've been building some OpenSuse targets with CMake 3.23 and not noticed!

**Comment by niedbalski** [comment] 2022-05-25 10:31
@patrick-stephens I cannot reproduce this issue with in_tail on MacOS (at least). @igorpeshansky Do you have a configuration file or command line arguments list to reproduce the same failure.

In any case to make it backwards compatible and if only affects > 3.20, the patch has to look as:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a07b235aa..d9e4ff226 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -46,7 +46,7 @@ else()
   set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall")
 endif()

-if(NOT ${CMAKE_SYSTEM_NAME} MATCHES "Windows")
+if(NOT ${CMAKE_SYSTEM_NAME} MATCHES "Windows" AND (${CMAKE_VERSION} VERSION_LESS "3.20") )
   set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D__FILENAME__='\"$(subst ${CMAKE_SOURCE_DIR}/,,$(abspath $<))\"'")
 else()
   set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D__FILENAME__=__FILE__")

```

**Comment by patrick-stephens** [comment] 2022-05-25 10:40
On an Opensuse/leap system I get this with CMake 3.23:
```
[2022/05/25 10:37:43] [debug] [input:tail:tail.0] flb_tail_fs_inotify_init() initializing inotify tail input
[2022/05/25 10:37:43] [debug] [input:tail:tail.0] inotify watch fd=27
[2022/05/25 10:37:43] [debug] [input:tail:tail.0] scanning path /var/log/test/*.log
[2022/05/25 10:37:43] [debug] [input:tail:tail.0] inode=86507648 with offset=24 appended as /var/log/test/test1.log
[2022/05/25 10:37:43] [debug] [input:tail:tail.0] scan_glob add(): /var/log/test/test1.log, inode 86507648
[2022/05/25 10:37:43] [debug] [input:tail:tail.0] 1 new files found on path '/var/log/test/*.log'
[2022/05/25 10:37:43] [debug] [stdout:stdout.0] created event channels: read=29 write=30
[2022/05/25 10:37:43] [debug] [router] match rule tail.0:stdout.0
[2022/05/25 10:37:43] [ info] [sp] stream processor started
[2022/05/25 10:37:43] [debug] [input:tail:tail.0] inode=86507648 file=/var/log/test/test1.log promote to TAIL_EVENT
[2022/05/25 10:37:43] [ info] [input:tail:tail.0] inotify_fs_add(): inode=86507648 watch_fd=1 name=/var/log/test/test1.log
[2022/05/25 10:37:43] [debug] [input:tail:tail.0] [static files] processed 0b, done
[2022/05/25 10:37:43] [ info] [output:stdout:stdout.0] worker #0 started
[2022/05/25 10:37:46] [debug] [input:tail:tail.0] inode=86507648 events: IN_MODIFY 
[2022/05/25 10:37:46] [debug] [input chunk] update output instances with new chunk size diff=22
[2022/05/25 10:37:47] [debug] [task] created task=0x7f9660242460 id=0 OK
[2022/05/25 10:37:47] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[0] fail: [1653475066.377255610, {"log"=>"hello"}]
[2022/05/25 10:37:47] [debug] [out flush] cb_destroy coro_id=0
[2022/05/25 10:37:47] [debug] [task] destroy task=0x7f9660242460 (task_id=0)
[2022/05/25 10:37:58] [debug] [input:tail:tail.0] inode=86507648 events: IN_ATTRIB 
[2022/05/25 10:37:58] [debug] [input:tail:tail.0] inode=86507648 file has been deleted: /var/log/test/test1.log
[2022/05/25 10:37:58] [debug] [input:tail:tail.0] inode=86507648 removing file name /var/log/test/test1.log
[2022/05/25 10:37:58] [ info] [input:tail:tail.0] inotify_fs_remove(): inode=86507648 watch_fd=1
```
This is using a simple config:
```
[SERVICE]
   log_level debug
[INPUT]
    name tail
    tag fail
    Path /var/log/test/*.log

[OUTPUT]
    name  stdout
    match *
```

**Comment by patrick-stephens** [comment] 2022-06-06 10:38
@igorpeshansky have you got a simple example that reproduces it? Neither I nor @niedbalski can reproduce it.

**Comment by ptsneves** [comment] 2022-07-28 09:15
@patrick-stephens while building working on the bitbake recipe for #4204 I am able to reproduce the issue. The issue is visible at compile time. Just running `strings td-agent-bit | grep compiler_depend.ts` will give you the matches. At a deeper level you can also see that a lot of object files have this issue. I am reproducing this on linux. Let me know if you require more information.

**Comment by ptsneves** [comment] 2022-07-28 09:34
As an addition if using gcc we should have a look at [-ffile-prefix-map](https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html) and friends so that the compiler sanitises paths for us.

**Comment by patrick-stephens** [comment] 2022-07-28 13:40
Could someone propose a PR to resolve it? Ideally with a unit test.

**Comment by ptsneves** [comment] 2022-08-02 09:08
@patrick-stephens See #5819

**Comment by patrick-stephens** [comment] 2022-08-04 08:47
No worries.

**Comment by leonardo-albertovich** [comment] 2022-08-04 09:13
I experienced the issue, let me know if there's anything I can do to help get this merged since it'd be really nice to have it.

**Comment by ptsneves** [comment] 2022-08-04 13:36
@leonardo-albertovich Regression testing ongoing on #5819.

**Closed** 2022-08-11 14:00 UTC
