### ISSUE TITLE
[DOC] Standard output plugin doc page appears listed in doc's Filters section, too.

### ISSUE THREAD

**Issue by q2dg** [fluent/fluent-bit#4057] opened 2021-09-04 10:53 UTC
See https://docs.fluentbit.io/manual/pipeline/filters/standard-output and https://docs.fluentbit.io/manual/pipeline/outputs/standard-output  It seems the former should be deleted. Thanks

**Comment by nokute78** [comment] 2021-09-04 22:50
Thank you for reporting.

The issue is already reported on doc repo https://github.com/fluent/fluent-bit-docs/issues/358 .
A patch is already sent https://github.com/fluent/fluent-bit-docs/pull/528 .

So, I close this issue.
Thank you.

**Closed by nokute78** 2021-09-04 22:50 UTC
