### ISSUE TITLE
Parser not found even defined.

### ISSUE THREAD

**Issue by epcim** [fluent/fluent-bit#382] opened 2017-09-25 14:09 UTC
Parser definiton (I have tried also multiple Parsers_file entries in [SERVICE], the behavior is the same).

```root@ctl01:/etc/td-agent-bit# head -n 18 parsers.conf                                                                                                                                                      
[PARSER]
    Name   haproxy-what-I-want-to-use
    Format regex
    Regex ^(?<time>[^ ][-:+0-9TZ]+|[[:upper:]][[:lower:]]{2}[ -:+0-9TZ]*)\s+(?<messages>.*)$
    Time_Format %b %d %H:%M:%S
    Time_Format %Y-%m-%dT%H:%M:%S+00:00
    Time_Format %Y-%m-%dT%H:%M:%S+%z
    Time_Format %Y-%m-%dT%H:%M:%S
    Time_Keep True
    Time_Key time

# this is just renamed originally "apache" parser
[PARSER]
    Name   haproxy
    Format regex
    Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
    Time_Key time
    Time_Format %d/%b/%Y:%H:%M:%S %z

root@ctl01:/etc/td-agent-bit# cat /etc//td-agent-bit/td-agent-bit.conf
@INCLUDE output_elastic.conf
[INPUT]
    Name tail
    DB /tmp/haproxy.flb.db
    Buffer_Max_Size 64k
    Chunk_Size 32k
    Exclude_Path *.gz,*.xz
    Multiline False
    Multiline_Flush 4
    Parser haproxy
    Path /var/log/haproxy.log*
    Path_Key path
    Tag haproxy

[SERVICE]
    Daemon off
    Flush 10
    Log_Level debug
    Parsers_File parsers.conf

root@ctl01:/etc/td-agent-bit# service td-agent-bit restart                                                                                                                                                           
root@ctl01:/etc/td-agent-bit# journalctl -n 50 -u td-agent-bit |tail -n 20       

Sep 25 14:05:13 ctl01 systemd[1]: Stopped TD Agent Bit.
Sep 25 14:05:13 ctl01 systemd[1]: Started TD Agent Bit.
Sep 25 14:05:13 ctl01 td-agent-bit[15521]: [2017/09/25 14:05:13] [ info] [engine] started
Sep 25 14:05:13 ctl01 td-agent-bit[15521]: [2017/09/25 14:05:13] [error] [in_tail] parser 'haproxy' is not registered
Sep 25 14:05:13 ctl01 td-agent-bit[15521]: [2017/09/25 14:05:13] [debug] [in_tail] inotify watch fd=20
Sep 25 14:05:13 ctl01 td-agent-bit[15521]: [2017/09/25 14:05:13] [debug] [in_tail] scanning path /var/log/haproxy.log*
Sep 25 14:05:13 ctl01 td-agent-bit[15521]: [2017/09/25 14:05:13] [debug] [in_tail] add to scan queue /var/log/haproxy.log, offset=0
Sep 25 14:05:13 ctl01 td-agent-bit[15521]: [2017/09/25 14:05:13] [debug] [in_tail] add to scan queue /var/log/haproxy.log.1, offset=0
Sep 25 14:05:13 ctl01 td-agent-bit[15521]: [2017/09/25 14:05:13] [debug] [in_tail] excluded=/var/log/haproxy.log.10.gz
Sep 25 14:05:13 ctl01 td-agent-bit[15521]: [2017/09/25 14:05:13] [debug] [in_tail] excluded=/var/log/haproxy.log.11.gz
Sep 25 14:05:13 ctl01 td-agent-bit[15521]: [2017/09/25 14:05:13] [debug] [in_tail] excluded=/var/log/haproxy.log.12.gz
```

I will get                  `[error] [in_tail] parser 'haproxy' is not registered`

**Comment by epcim** [comment] 2017-09-25 14:10
v0.12.3

**Comment by edsiper** [comment] 2017-09-25 15:11
The parsers configuration only allow ONE Time_Format definition, having more than one is generating the unexpected behavior. 
.
The right fix from Fluent Bit side is to give details about the proper error. Working on a fix to improve that

**Comment by edsiper** [comment] 2017-09-25 16:20
The real cause of the problem was that Time_Keep only accepted on/off values (not True).

I pushed a fix to extend support for on/off/true/false, this will be part of 0.12.4 release.

note: if an error exists in a parsers file, the while file is skipped. Now you should be able to get more detailed errors in the output.

**Comment by edsiper** [comment] 2017-09-26 22:43
Fixed by https://github.com/fluent/fluent-bit/commit/e859b635b1781cc881fb5f8e107faff1d2c7bcd8

**Closed by edsiper** 2017-09-26 22:43 UTC
Labels: bug, fixed
