### ISSUE TITLE
epoll_ctl errno 17 when combine tail and systemd

### ISSUE THREAD

**Issue by jolestar** [fluent/fluent-bit#373] opened 2017-09-11 04:13 UTC
version: fluent-bit 0.12

fluent-bit.conf
```
[SERVICE]
    Flush          1
    Daemon         Off
    Log_Level      debug
    Parsers_File   parsers.conf

[INPUT]
    Name           tail
    Tag            kube.*
    Path           /var/log/containers/*.log
    Parser         docker

[INPUT]
    Name            systemd
    Tag             host.*

[OUTPUT]
    Name  stdout
    Match *
```
parsers.conf
```
[PARSER]
    Name   json-test
    Format json
    Time_Key time
    Time_Format %d/%b/%Y:%H:%M:%S %z

[PARSER]
    Name        docker
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
    Time_Keep   On
```

put the above two config  to  /fluentbit/etc/

```console
docker run --network host -v /var/log:/var/log -v /fluentbit/etc/:/fluent-bit/etc fluent/fluent-bit:0.12 /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
```

error message:

```console
[2017/09/11 04:05:32] [  Error] epoll_ctl: File exists, errno=17 at /tmp/fluent-bit-0.12.0/lib/monkey/mk_core/mk_event_epoll.c:133
```

**Comment by edsiper** [comment] 2017-09-11 04:37
I tried to reproduce without success. 

When you see the error, does it affects tail or systemd plugin ?

**Comment by jolestar** [comment] 2017-09-11 06:11
I can reproduce the error every time.

```console
docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

``` console
docker run -v /fluentbit/etc/:/fluent-bit/etc fluent/fluent-bit:0.12 /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
Unable to find image 'fluent/fluent-bit:0.12' locally
0.12: Pulling from fluent/fluent-bit
f7ef834aadcd: Pull complete
ffe324699c1d: Pull complete
730512578b0b: Pull complete
5a487e3172af: Pull complete
c095fb9ff8f6: Pull complete
434afeb392cd: Pull complete
Digest: sha256:afeef3212814489865f84d426394b2f9c4f1354bd4559797adca1bbc4d7fa06c
Status: Downloaded newer image for fluent/fluent-bit:0.12
Fluent-Bit v0.12.1
Copyright (C) Treasure Data

[2017/09/11 06:05:42] [  Error] epoll_ctl: File exists, errno=17 at /tmp/fluent-bit-0.12.1/lib/monkey/mk_core/mk_event_epoll.c:133
[2017/09/11 06:05:42] [ info] [engine] started
[2017/09/11 06:05:42] [debug] [in_tail] inotify watch fd=19
[2017/09/11 06:05:42] [debug] [in_tail] scanning path /var/log/containers/*.log
[2017/09/11 06:05:42] [error] [in_tail] read error, check permissions: /var/log/containers/*.log
[2017/09/11 06:05:42] [debug] [router] input=tail.0 'DYNAMIC TAG'
[2017/09/11 06:05:42] [debug] [router] input=systemd.0 'DYNAMIC TAG'
```

It seems no affects tails or systemd, but I want know why. Monkey seams to be used only for http server, but my config not enable http server.

**Comment by edsiper** [comment] 2017-09-12 01:27
Looking at the output I see the following:

- There is a epoll_ctl before the service starts, so it's related to a problem when in_tail or in_systemd are initializing.
- in_tail cannot read /var/log/containers, could be related to permissions ?

Fluent Bit uses the Monkey core-runtime engine for memory, networking and other operations, the HTTP interface is not built-in.

please check the permission stuff above

**Comment by jolestar** [comment] 2017-09-12 01:46
The reason for permissions error is that the /var/log/containers dir is not exist in fluent docker image. Even if I use -v to mapping host /var/log dir to container and fix  permissions error, epoll_ctl error still exist.

**Comment by jolestar** [comment] 2017-09-13 10:47
I found it seam affect tails input, tail is easily interrupted。

**Comment by Constantin07** [comment] 2017-09-13 13:58
We are getting the same error while running fluent-bit in container.

fluent-bit.out.log:
```
Starting Fluent Bit using /etc/fluent-bit/nonlocal.conf
Fluent-Bit v0.12.1
Copyright (C) Treasure Data

[2017/09/12 12:17:18] [  Error] epoll_ctl: File exists, errno=17 at /tmp/fluent-bit-0.12.1/lib/monkey/mk_core/mk_event_epoll.c:133
[2017/09/12 12:17:31] [  Error] epoll_ctl: File exists, errno=17 at /tmp/fluent-bit-0.12.1/lib/monkey/mk_core/mk_event_epoll.c:133
[2017/09/12 14:31:50] [  Error] epoll_ctl: File exists, errno=17 at /tmp/fluent-bit-0.12.1/lib/monkey/mk_core/mk_event_epoll.c:133
[2017/09/12 14:32:00] [  Error] epoll_ctl: File exists, errno=17 at /tmp/fluent-bit-0.12.1/lib/monkey/mk_core/mk_event_epoll.c:133
[2017/09/12 15:17:24] [  Error] epoll_ctl: File exists, errno=17 at /tmp/fluent-bit-0.12.1/lib/monkey/mk_core/mk_event_epoll.c:133
[2017/09/12 15:17:25] [  Error] epoll_ctl: File exists, errno=17 at /tmp/fluent-bit-0.12.1/lib/monkey/mk_core/mk_event_epoll.c:133
```

**Comment by edsiper** [comment] 2017-09-13 20:45
@Constantin07 

thanks for the feedback. I am digging into the epoll_ctl problem now, for now can you share your configuration ? I want to find similarities between your use case and @jolestar to find the root cause.

About the "error writing content body" means the other end-point (TCP service) closed the connection. Sometimes it can be related to Fluent-bit 0.12 flushing records to a Fluentd 0.12 where the forward protocol message is different. Please add the option "Time_as_Integer On" in your Fluent Bit out_forward section.

**Comment by edsiper** [comment] 2017-09-13 22:11
@jolestar @Constantin07 

In order to find the root the cause of the problem I need your help trying to reproduce the issue with a new Fluent Bit that I have put in place for download:

- Sources: https://github.com/fluent/fluent-bit/archive/issue-373.zip
- Docker Image: fluent/fluent-bit:0.12-issue-373

> Docker image should be available in about 10 mins.

please try to reproduce, if you need a specific package (deb, rpm) let me know so I can build it

**Comment by baldeynz** [comment] 2017-09-13 22:24
Hi. We have the same epoll_ctl errno 17  issue in our setup, we are trying to use tail and systemd inputs with fluentbit whilst running in a container as a daemonset in kubernetes. Might not be related but is it possible to run the fluentbit systemd plugin in a container and if so is it dependant on the docker journald logging driver being enabled in docker?

**Comment by baldeynz** [comment] 2017-09-13 23:12
I have tried the docker image above and it runs for a little while (showing journald logs for kubelet.service) before failing with the following errors:

[2017/09/13 23:04:51] [  Error] epoll_ctl: File exists, errno=17 at /tmp/fluent-bit-issue-373/lib/monkey/mk_core/mk_event_epoll.c:133
[2017/09/13 23:04:51] [error] [input collector] COLLECT_EVENT registration failed

our config is:
fluent-bit.conf: |-
    [SERVICE]
      Flush          1
      Daemon         Off
      Log_Level      info
      Parsers_File   parsers.conf
 
    [INPUT]
      Name           tail
      Tag            kube.*
      Path           /var/log/containers/*.log
      Parser         docker
      Mem_Buf_Limit  256KB
 
    [INPUT]
      Name           systemd
      Tag            host.*
      Systemd_Filter _SYSTEMD_UNIT=kubelet.service
 
    [FILTER]
      Name           kubernetes
      Match          kube.*
      Kube_URL       https://kubernetes.default.svc:443
      Merge_JSON_Log On
 
    [OUTPUT]
      Name  forward
      Match kube.*
      Host 123.123.123.123
    [OUTPUT]
      Name  stdout
      Match *

parsers.conf: |-
    [PARSER]
      Name        docker
      Format      json
      Time_Key    time
      Time_Format %Y-%m-%dT%H:%M:%S.%L
      Time_Keep   On

And Daemonset is set to use your image fluent/fluent-bit:0.12-issue-373

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: kube-system
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: fluent-bit
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:0.12-issue-373
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: journald
          mountPath: /run/log/journal
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - mountPath: /fluent-bit/etc
          name: fluentbit-config
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
 path: /var/log
      - name: journald
        hostPath:
          path: /run/log/journal
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - configMap:
          name: fluentbit-config
        name: fluentbit-config

**Comment by edsiper** [comment] 2017-09-13 23:22
I was able to reproduce the problem (systemd plugin), I am troubleshooting, I will provide an update shortly

**Comment by Constantin07** [comment] 2017-09-14 14:07
@edsiper here is the config:

```
[SERVICE]
    Flush          1
    Daemon         Off
    Log_Level      info
    Parsers_File   /etc/fluent-bit/parsers.conf

[INPUT]
    Name           tail
    Tag            nginx.access.general.${ENV}.gateway
    Path           /var/log/nginx/access.log
    Parser         nginx_gateway_access
    DB             /var/log/nginx/flb_tail.db
    Mem_Buf_Limit  5MB

[INPUT]
    Name           tail
    Tag            nginx.access.general.${ENV}.service
    Path           /var/log/nginx/access-service.log
    Parser         nginx_gateway_access
    DB             /var/log/nginx/flb_tail.db
    Mem_Buf_Limit  5MB

[INPUT]
    Name           tail
    Tag            nginx.error.general.${ENV}.gateway
    Path           /var/log/nginx/error.log
    Parser         nginx_error
    DB             /var/log/nginx/flb_tail.db
    Mem_Buf_Limit  5MB
    Buffer_Chunk_Size 32k
    Buffer_Max_Size 512k

[INPUT]
    Name           tail
    Tag            nginx.error.general.${ENV}.service
    Path           /var/log/nginx/error-service.log
    Parser         nginx_error
    DB             /var/log/nginx/flb_tail.db
    Mem_Buf_Limit  5MB
    Buffer_Chunk_Size 32k
    Buffer_Max_Size 512k

[FILTER]
    Name record_modifier
    Match *
    Record application nginx
    Record dockerHost ${DOCKER_HOST}
    Record Env ${ENV}
    Record AZ ${AZ}

[OUTPUT]
    Name          forward
    Match         *
    Host          ${FLUENTD_HOST}
    Port          ${FLUENTD_PORT}
    Self_Hostname ${HOSTNAME}
```

**Comment by edsiper** [comment] 2017-09-14 18:48
I've found the root cause of the problem and pushed a fix into 0.12 branch (fix will be part of 0.12.2 release) 

If you can do some tests with the new Docker image (av in the next 15 min), will help to speed up the release of this version:

https://hub.docker.com/r/fluent/fluent-bit/builds/bdmup4vukrspvgwn7quyau9/

## Docker hub image

```
fluent/fluent-bit:0.12-issue-373
```

### Fixes

- Input Engine: do not start a running collector
- Systemd: fix usage of multiple filters

**Comment by baldeynz** [comment] 2017-09-14 20:22
Hi 

Using the same config as before we seem to be getting the same error as we had before:

[2017/09/14 20:07:53] [ info] [engine] started
[2017/09/14 20:07:53] [ info] [filter_kube] https=1 host=kubernetes.default.svc port=443
[2017/09/14 20:07:53] [ info] [filter_kube] local POD info OK
[2017/09/14 20:07:53] [ info] [filter_kube] testing connectivity with API server...
[2017/09/14 20:07:53] [ info] [filter_kube] API server connectivity OK
[2017/09/14 20:07:54] [error] [out_fw] error writing content body
[2017/09/14 20:07:55] [error] [out_fw] error writing content body

Fluent-Bit v0.12.2
Copyright (C) Treasure Data
 
[2017/09/14 20:07:59] [  Error] epoll_ctl: File exists, errno=17 at /tmp/fluent-bit-issue-373/lib/monkey/mk_core/mk_event_epoll.c:133

We deleted our local image of fluent/fluent-bit:0.12-issue-373 and pulled again, not %100 sure that we are getting the new image though.
The image shown on a docker inspect on the container was:

 "Image": "sha256:99e59f495ffaa222bfeb67580213e8c28c1e885f1d245ab2bbe3b1b1ec3bd0b2"

Any chance you can change the tag slightly so we can be sure its a different image? or can you confirm that the sha256 above is correct?

**Comment by edsiper** [comment] 2017-09-15 01:22
new sha256 is __414437c9563367744cbc77d1a94c643b42f33686e7d3bac7ede4552196554ba8__

**Comment by jolestar** [comment] 2017-09-15 03:05
We've confirmed that this bug has been fixed

**Comment by edsiper** [comment] 2017-09-15 05:56
thanks for the feedback.

Image fluent/fluent-bit:0.12.2 is already available.

**Closed by edsiper** 2017-09-15 05:56 UTC
Labels: bug, fixed

**Comment by ouyangluwei** [comment] 2020-03-13 11:41
command: ["sh", "-c", "sysctl fs.inotify.max_user_instances=1024; /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf"]
