### ISSUE TITLE
Reload feature in fluentd-bit or Dynamic reload

### ISSUE THREAD

**Issue by Allesgluck** [fluent/fluent-bit#1379] opened 2019-06-12 09:22 UTC
Hi Team,

I donot see any reload feature or re-loading the dynamic config changes in fluentd w/o taking down the process. Can u please provide any insight or guide me ?

**Comment by edsiper** [comment] 2019-06-13 22:45
There is no dynamic config reload support, that feature is delayed due to other priorities. 

Closing this question.

**Closed by edsiper** 2019-06-13 22:45 UTC
Labels: fixed, question

**Comment by RiccardoManfrin** [comment] 2021-02-25 18:16
Is this still the case?

**Comment by FeynmanZhou** [comment] 2021-08-09 13:01
Hope [Fluentbit-operator](https://github.com/fluent/fluentbit-operator) is helpful for you to address it.

**Comment by nickbroon** [comment] 2021-08-18 18:18
This is probably a duplicate of #365
