### ISSUE TITLE
Lack of logging when configuration is invalid

### ISSUE THREAD

**Issue by jbhilton11** [fluent/fluent-bit#378] opened 2017-09-18 18:56 UTC
I'm trying to add in TLS for the HTTP output plugin and have the following:

```
[INPUT]
    Name tail
    Path /var/log/audit/audit.log
    Parser auditd

[OUTPUT]
    Name http
    Match *
    Host <hostname>
    Port <port>
    URI <dynamic URI>
    Format json
    tls On
    tls.verify Off
```
However, when I start up the fluent-bit service in the foreground, it looks as though it starts to run and then it just stops. I can only assume that this is an issue with the configuration I have, however, I'm not sure because there is no additional logging other than what appears to be the service starting up, but just not doing anything.

Any help debugging/adding additional logging to fluent-bit-0.12.1 would be awesome!

**Comment by edsiper** [comment] 2017-09-18 21:46
@jbhilton11 in order to troubleshoot and try to reproduce the issue, please provide the output of the following command:

```
fluent-bit -c yourconffile.conf --sosreport
```

**Comment by jbhilton11** [comment] 2017-09-19 12:38
```
[Fluent Bit]
    Edition Community Edition
    Version 0.12.1
    Built Flags JSMN_PARENT_LINKS JSMN_STRICT FLB_HAVE_TLS FLB_HAVE_SQLDB FLB_HAVE_FLUSH_LIBCO FLB_HAVE_VALGRIND FLB_HAVE_FORK FLB_HAVE_PROXY_GO FLB_HAVE_JEMALLOC JEMALLOC_MANGLE FLB_HAVE_REGEX FLB_HAVE_C_TLS FLB_HAVE_SETJMP FLB_HAVE_ACCEPT4 FLB_HAVE_INOTIFY

[Operating System]
    Name Linux
    Release ...
    Version ...

[Hardware]
...

[Built Plugins]
    Inputs cpu mem kmsg tail proc disk netif dummy head health serial stdin tcp mqtt lib forward random syslog
    Filters grep stdout kubernetes parser record_modifier
    Outputs counter es exit file forward http influxdb kafka-rest nats null plot stdout td lib flowcounter

[SERVER] Runtime configuration
    Flush 5
    Daemon Off
    Log_Level Debug

[INPUT] Instance
    Name tail.0 (tail, id=0)
    Flags DYN_TAG
    Threaded No
    Tag tail.0
    Path /var/log/audit/audit.log
    Parser auditd

[FILTER] Instance
    Name record_modifie (record_modifier, id=0)
    Match *
    Record ...
    Record ...
    Record ...
    Record ...

[OUTPUT] Instance
    Name http.0 (http, mask_id=1)
    Match *
    TLS Active Yes
    TLS.Verify Off
    TLS.Ca_File (not set)
    TLS.Crt_File (not set)
    TLS.Key_File (not set)
    TLS.Key_Passwd (not set)
    Retry Limit 1
    Host.TCP_Port ...
    Host.Name ...
    URI ...
    Format json

**Comment by jbhilton11** [comment] 2017-09-19 12:48
I just noticed that this might be an SELinux issue preventing this from connecting. If you have any ideas what this tries to do that might be causing SELinux to have an issue, that would be helpful to know.

**Comment by jbhilton11** [comment] 2017-09-19 13:39
Well, it seems like providing some more TLS values (ie. ca_file, crt_file, etc.) actually don't cause this SELinux issue anymore. It might be worthwhile to require a couple more properties before actually making it to where TLS can be utilized. All examples show just "tls" and "tls.verify".

**Comment by edsiper** [comment] 2017-09-20 01:33
Since I don't have Selinux here, how can I reproduce the problem ? I would like to learn what's the anomaly from a code perspective to detect cases like this. I did a check on TLS routines and there are verification for every piece (need to find if I am missing something)

**Comment by jbhilton11** [comment] 2017-09-20 17:43
So, from what I can tell, I had a truststore that didn't trust the CA that signed the certificate that I was using for the fluent-bit forwarder. This appeared to cause issues enough to shut down the fluent-bit forwarder process right after starting. My guess is that the initial connection with the server to check if the certificate is trusted is being interpreted in some way that causes the forwarder to shut down abruptly. That's really all I can tell that's going on, but can't see anything in the forwarder's log file from a Log_level Debug standpoint.

**Comment by jbhilton11** [comment] 2017-09-21 17:25
So it turns out the true problem was all certs/key/key password-related. However, it was really hard to debug this issue without the help of any logging. Part of my issue was the portion mentioned in the above comment about the server CA not trusting the client certificate CA (remedy was adding the client CA to the server truststore). The other issue I found out is that I needed to specify the key file password for it to work. Once I did this, the logging showed up (tls and non-tls-related logging). I was able to see when strictly running the fluent-bit forwarder as the root user that it was throwing a segmentation fault when I was having cert/key/key password issues.

If possible, it would be great to have some type of logging added in the case where issues like these are occurring. I'm not sure what shows up when fluent-bit runs into issues trying to use those certs/keys, but nothing shows up if there's an issue.

I appreciate all the help you've offered and I hope this "enhancement" will help others! :)

**Comment by edsiper** [comment] 2017-09-25 16:39
so if your key file required a password, you did not see any error ?

**Comment by jbhilton11** [comment] 2017-09-25 17:58
That's correct. I did not see any additional logging until I figured out I had to provide the password to my key file. Once I did that, the logging kicked in (trace from fluent-bit and TLS from the tls.debug variable).

**Comment by edsiper** [comment] 2017-09-26 22:49
In 0.12 branch, there some changes where TLS errors adds more messages (the ones coming from libmbedtls).

All this comes out on 0.12.4 release (this Friday)

**Comment by edsiper** [comment] 2017-10-03 15:46
Closing this issue since more errors has been included.

**Closed by edsiper** 2017-10-03 15:46 UTC
Labels: enhancement, fixed
