### ISSUE TITLE
High load / 100% CPU usage on Raspberry Pi

### ISSUE THREAD

**Issue by marktheunissen** [fluent/fluent-bit#90] opened 2016-07-27 08:41 UTC
Problem: `fluent-bit` process maxes out a CPU core (100% usage). My build environment is the Raspberry Pi 1 (ARM). Followed the compile instructions in the README.

This is the command:

`head events.json | ~/src/fluent-bit/build/bin/fluent-bit -i stdin -o stdout -f 1 > outtest`

This only sends 10 events through fluent-bit. It should be idle after flushing those. The actual result is the high CPU usage.

Run `strace` on the pid and I see the following lines being repeated while the process maxes out the CPU:

```
read(5, "", 32766)                      = 0
epoll_wait(3, {{EPOLLHUP, {u32=3363536, u64=4298330832}}}, 256, -1) = 1
read(5, "", 32766)                      = 0
epoll_wait(3, {{EPOLLHUP, {u32=3363536, u64=4298330832}}}, 256, -1) = 1
read(5, "", 32766)                      = 0
epoll_wait(3, {{EPOLLHUP, {u32=3363536, u64=4298330832}}}, 256, -1) = 1
...
```

**Comment by edsiper** [comment] 2016-07-27 13:52
I will dig into that, I suspect it could be related to when the stdin file descriptor is closed.

note: if you use 'head' command it will only print a few lines of the beginning of the target file, use cat instead.

**Comment by marktheunissen** [comment] 2016-07-27 14:14
@edsiper Ok thanks - yup, I am using head because the file is massive and I want to show that the bug is triggered by only 10 lines.

**Comment by edsiper** [comment] 2016-07-27 14:16
got it. Indeed I was able to reproduce the problem and the guilty is the missing handling of the closed STDIN interface. Working in a fix.

**Comment by edsiper** [comment] 2016-07-27 15:14
I pushed an enhancement at branch [0.8](https://github.com/fluent/fluent-bit/tree/0.8), would you please give it a try ?

**Comment by marktheunissen** [comment] 2016-07-27 16:05
Will have to have a look tomorrow. How will it work now? Let's say I have a process that generates events occasionally, called `event_creator`:

`./bin/event_creator | /bin/fluent-bit -i stdin -o stdout -f 1 > outtest`

If it outputs a line of JSON every minute, will fluent-bit be able to cope with that?

**Comment by edsiper** [comment] 2016-07-27 18:15
that should be ok, the only thing I am thinking how to handle it is that if stdin gets closed, should Fluent Bit stop working ?, at the moment it continue working which is expected because it runs as a service.

maybe in_stdin may request to shutdown once it finish ?

**Comment by edsiper** [comment] 2016-08-03 17:54
@marktheunissen any update is appreciated.

**Comment by marktheunissen** [comment] 2016-08-03 18:44
Hey @edsiper, I've actually switched to using Fluent Hydra now which is written in Go. https://github.com/fujiwara/fluent-agent-hydra

**Comment by marktheunissen** [comment] 2016-08-03 18:47
Sorry, I just couldn't wait for a stable version.

**Comment by edsiper** [comment] 2016-08-03 18:48
not a problem, understandable. Thanks for the report.

Closing this issue as cannot reproduce it again after latest fixes in 0.8 branch.

**Closed by edsiper** 2016-08-03 18:48 UTC

**Comment by rolandjitsu** [comment] 2019-05-22 07:41
I'm actually also, consistently, seeing 100% CPU usage. I'm using the process, memory, cpu and tail inputs.

Using only tail peaks at 100% only while flushing.

**Comment by edsiper** [comment] 2019-05-22 07:51
@rolandjitsu please open a new issue with configuration, rpi version and so on, we can follow up there.

**Comment by rolandjitsu** [comment] 2019-05-22 08:06
@edsiper see https://github.com/fluent/fluent-bit/issues/1341.
