### ISSUE TITLE
It would be nice to allow multiple [SERVICE] sections

### ISSUE THREAD

**Issue by stronny** [fluent/fluent-bit#1030] opened 2019-01-15 16:00 UTC
**Is your feature request related to a problem? Please describe.**
It would be convenient to have a `@INCLUDE service/*.conf` directive to make the config more modular just as I do with inputs, outputs and filters. The problem is that I have to merge all parameters into a single file inside my config manager, which also prevents manual overrides.

**Describe the solution you'd like**
I don't know how you store the values internally, but it would make sense to allow modifying them as the config stream is read.

**Additional context**
Right now the daemons just crashes with SIGSEGV for me if I try to include a file with [SERVICE] section:
```
# /opt/td-agent-bit/bin/td-agent-bit -c //etc//td-agent-bit/td-agent-bit.conf
Fluent Bit v1.0.2
Copyright (C) Treasure Data

[engine] caught signal (SIGSEGV)
ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)Aborted
```

As a side note the double slashes come straight from the systemd unit which is really minimalistic, I would argue to the detriment of the service.

**Comment by edsiper** [comment] 2019-06-03 17:26
please share your configuration file, I cannot reproduce the crash as you mention.

(please upgrade to v1.1.2)

**Comment by edsiper** [comment] 2020-05-05 17:44
Only one [SECTION] is allowed, otherwise, it can lead to confusion from an operational perspective.

Closing the enhancement request.

**Closed by edsiper** 2020-05-05 17:44 UTC
Labels: waiting-for-user
