### ISSUE TITLE
Parser time of unstructured input unexpected

### ISSUE THREAD

**Issue by nakato** [fluent/fluent-bit#469] opened 2017-12-18 01:57 UTC
I was attempting to get fluent-bit to add a time to unstructured standard input content, and found that I could either get the time set to `0.000000000` or a very unexpected value about a year ago, `1483142400.000000000` (2016-12-31).

Fluent-bit version: 0.12.10
Installation: Docker `fluent/fluent-bit:0.12.10`

Starting with a basic config to parse `blobs of text` to `{"message": "text"}`, I get a time of `0.000000000`

parser.conf:
```ini
[PARSER]
    Name    pt
    Format  regex
    Regex   ^(?<message>.*)$
```

```shell
echo "Hello, World!" | fluent-bit -i stdin -p Parser=pt --parser=par.conf -o stdout
```

I would expect the output to be similar to:
```
[0] stdin.0: [1513560363.000000000, {"message"=>"Hello, World!"}]
```
But instead I get
```
[0] stdin.0: [0.000000000, {"message"=>"Hello, World!"}]
```

Changing the config to skip the time lookup in [flb_parse_regex.c](https://github.com/fluent/fluent-bit/blob/3ad1a098437e1bbb55473ec22e4994ed8ce9b207/src/flb_parser_regex.c#L52), fluentbit then adds a timestamp to the output, however the time that is returned is quite unexpected.   The timestamp ends up always being `1483142400.000000000` (2016, Dec, 31) in my testing.

Parser.conf
```
[PARSER]
    Name    pt
    Format  regex
    Regex   ^(?<time>)(?<message>.*)$
    Time_Key time
    Time_Format 
```

Then:
```
echo "Hello, World!" | fluent-bit -i stdin -p Parser=pt --parser=par.conf -o stdout
```
outputs
```
[0] stdin.0: [1483142400.000000000, {"message"=>"Hello, World!"}]
```

---

If I provide structured input without a date, the date gets set appropriately.  I would expect that to be the case with unstructured input that's parsed as well.
```
echo '{"message": "Hello, World!"}' | fluent-bit -i stdin -o stdout
```
```
[0] stdin.0: [1513561838.719509364, {"message"=>"Hello, World!"}]
```

**Comment by edsiper** [comment] 2017-12-20 22:11
@nakato thanks for the bug report.

I've found the following root causes:

- in_stdin plugin is not populating default time after the regex call. Fixed by https://github.com/fluent/fluent-bit/commit/b8f296682d237d94ae74dd41052866a1ebc98317
- config reader: after trim a value, it don't check if the value is empty (which is not allowed). Fixed by https://github.com/fluent/fluent-bit/commit/99738a7940771fe6ebc2d2036fb563d43dcb8dd6

In the meanwhile you can try 0.12 branch which have the changes in place, I will be releasing v0.12.11 shortly.

**Comment by edsiper** [comment] 2017-12-22 04:30
Fluent Bit v0.12.11 has been released: http://fluentbit.io/announcements/v0.12.11/

**Closed by edsiper** 2017-12-22 04:30 UTC
Labels: bug, fixed

**Comment by nakato** [comment] 2017-12-23 12:12
I can confirm v0.12.11 sets the timestamp correctly, and the empty value errors out.


Thanks for your work @edsiper !
