### ISSUE TITLE
mem buf overlimit - Potential deadlock

### ISSUE THREAD

**Issue by wiardvanrij** [fluent/fluent-bit#9133] opened 2024-07-25 19:51 UTC
## Bug Report

**Describe the bug**

First of all, I wasn't entirely able to reproduce it, and I have limited tools around it to exactly say: this happened. However, I figured to report it nonetheless. 

- Multiple `tail` inputs with `Mem_Buf_Limit`
Using:
```
        Buffer_Chunk_Size 256K
        Buffer_Max_Size 2MB
```
- One `forward` output
- A large node on K8s with 100++ pods
- Effectively around 250+ tail inputs
- Potentially a lot more tail because of some lag

What happened was the following:
- Pod got restarted
- It hit `mem buf overlimit` on both our main tails
- Then resumed again fairly quickly and ping/pong between those states
- At some point, the tails both got paused again due to the same `mem buf overlimit`, but now they they did not resume
- Memory usage was constant and quite high (800MB)
- CPU usage was `1m` (so, nothing). 
- Didn't seem to do anything anymore.

My opinion is the following, but I don't know if it's true as I'm not familiar with the code, yet if I have to make a guess:
- There is some init logic that starts all the tails
- Meanwhile the buffers get filled
- It does not start the output until the whole 'init' process is done
- It hit the buffer limits before it even could start outputting
- effectively creating a deadlock somehow?

Simply after restarting the pod again, fluentbit started to run fine with about 1 cpu and ~150MB of memory.

**Your Environment**

* Version used: 2.2.2
* Environment name and version (e.g. Kubernetes? What version?): K8s

---

Again, I'm sorry for the limited information, but even so, I figured to just mention it.

**Comment by jvassev** [comment] 2024-08-05 19:18
We are experiencing the same: after the buffer is full (our is 1G), the plugin just hangs. I changed the output plugin to just discarding the logs but we still hit the same problem.

I tried both with version 2.1.6 and 3.1.0 - same behaviour.

**Comment by leonardo-albertovich** [comment] 2024-08-06 10:46
Could you please share your configuration file @jvassev ? I'm not asking @wiardvanrij because it seems like his setup is quite large and hard to minimize but even then any insight or ideas would be more than welcome.

The one thing that caught my mind was that you mentioned the interaction between the actual tail instances and cold chunks being loaded which could make sense, however, I'm not entirely sure about the output part but I'll analyze the code and try to get closer to a reproduction.

Thanks for taking the time to report this issue.

**Comment by leonardo-albertovich** [comment] 2024-08-06 11:21
From what I see in the code I'm under the impression that : 

1. Cold chunks loaded while starting the system are only bound to the `storage_backlog` input plugin which means they do not directly affect other input plugins
2. Input plugins that go over their memory allowance are paused immediately after ingesting the "offending" chunk [here](https://github.com/fluent/fluent-bit/blob/master/src/flb_input_chunk.c#L1753)
3. Input plugin memory limits are checked each time an associated task is destroyed [here](https://github.com/fluent/fluent-bit/blob/master/src/flb_task.c#L498)

There is one scenario I'm thinking of where :

1. There are multiple input plugins routed to an output plugin that has a storage limit 
2. Some of the input plugins ingest enough data to go over their memory allowance and be paused yet none of their chunks are scheduled to be flushed
3. Another plugin needs to ingest data and causes those chunks to be dumped

I could be wrong but I think this could be a scenario where an input plugin is "left hanging" so I'll try to come up with a fix and if you folks could test it that would be great.

**Comment by jvassev** [comment] 2024-08-06 11:24
Here is my config, stripped of irrelevant items:
```
[SERVICE]
    Flush           5
    Daemon          off
    Log_Level       info
    Parsers_File    /fluent-bit/etc/parsers.conf
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_PORT    2020

[INPUT]
    Name              tail
    Tag               kube.*
    Path              /var/log/containers/*.log
    Parser            ${PARSER} # just cri parser
    DB                ${WORK_DIR}/flb_kube.db
    Mem_Buf_Limit     ${MEM_BUFFER} # set to 1G
    rotate_wait       60
    Skip_Long_Lines   On
    Refresh_Interval  5

[FILTER]
    Name                kubernetes
    Match               kube.*
    Kube_URL            https://kubernetes.default.svc:443
    Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
    K8S-Logging.Parser  Off
    Annotations         Off
    Buffer_Size         256k
    Cache_Use_Docker_Id On


[OUTPUT]
# omitted

```

**Comment by leonardo-albertovich** [comment] 2024-08-06 11:28
Does your output plugin have a storage limit? Do you have just one input or did you omit others?

**Comment by wiardvanrij** [comment] 2024-08-06 15:36
redacted but our full config

```
   [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        Parsers_File  custom_parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2022
        Health_Check  On
        storage.metrics On
        storage.path              /var/log/flb-storage/
        storage.sync              normal
        storage.checksum          off
        storage.backlog.mem_limit 10M

    [INPUT]
        name   fluentbit_metrics
        tag    internal_metrics
    [INPUT]
        Name tail
        Tag  xxxx_all.*
        Path /var/log/containers/*.log
        Exclude_Path /var/log/containers/*_istio-proxy*, /var/log/containers/*_loki_*
        multiline.parser docker, cri
        Parser docker_no_time
        Buffer_Chunk_Size 256K
        Buffer_Max_Size 2MB
        Skip_Long_Lines On
        Rotate_Wait     5
        Refresh_Interval 10
        DB  /var/log/flb_kube_alllog.db
        DB.Sync         Normal
        Ignore_Older  1h
        Mem_Buf_Limit 120MB
    [INPUT]
        Name tail
        Tag  xxxx_proxy.*
        Path /var/log/containers/*istio-proxy*
        Exclude_Path /var/log/containers/*_loki_*
        multiline.parser docker, cri
        Parser docker_no_time
        Buffer_Chunk_Size 256K
        Buffer_Max_Size 2MB
        Skip_Long_Lines On
        Rotate_Wait     5
        Refresh_Interval 10
        DB  /var/log/flb_istoproxy_alllog.db
        DB.Sync         Normal
        Ignore_Older  1h
        Mem_Buf_Limit 120MB
    [INPUT]
        Name  tail
        Tag  xxxx.*
        Path  /var/log/containers/xxxx*istio-proxy*.log
        Parser  docker
        DB  /var/log/xxxx.db
        DB.Sync         Normal
        Skip_Long_Lines  Off
        Refresh_Interval  10
        Mem_Buf_Limit 5MB
    [INPUT]
        Name  tail
        Tag  xxxx.*
        Path  /var/log/containers/xxxx*istio-proxy*.log
        Parser  docker
        DB  /var/log/flb_kube_pinot.db
        DB.Sync         Normal
        Skip_Long_Lines  Off
        Refresh_Interval  10
        Mem_Buf_Limit 5MB
    [INPUT]
        Name  tail
        Tag  xxxx_xxxx.*
        Path  /var/log/containers/xxxx*istio-proxy*.log
        Parser  docker
        DB  /var/log/xxxx.db
        DB.Sync         Normal
        Skip_Long_Lines  Off
        Refresh_Interval  10
        Mem_Buf_Limit 5MB
    [INPUT]
        Name  tail
        Tag  xxxx_.*
        Path  /var/log/containers/xxxx*istio-proxy*.log
        Parser  docker
        DB  /var/log/xxxx-primary.db
        DB.Sync         Normal
        Skip_Long_Lines  Off
        Refresh_Interval  10
        Mem_Buf_Limit 5MB
    [INPUT]
        Name systemd
        Tag systemd.*
        Read_From_Tail On
        Strip_Underscores On
        Mem_Buf_Limit 10MB
    [INPUT]
        Name tail
        Tag  xxxx_cni.*
        Path /var/log/aws-routed-eni/*.log
        Parser docker_no_time
        Buffer_Chunk_Size 256K
        Buffer_Max_Size 2MB
        Skip_Long_Lines On
        Rotate_Wait     5
        Refresh_Interval 10
        DB  /var/log/flb_cni_alllog.db
        DB.Sync         Normal
        Ignore_Older  1h
        Mem_Buf_Limit 10MB

    [FILTER]
        Name record_modifier
        Match *
        Record xxxx_account xxxx
        Record xxxx_cluster_name xxxx-2
        Record xxxx_env prod
        Record xxxx_region us-east-1
    [FILTER]
        Name record_modifier
        Match systemd.*
        Record xxxx_app nodes_systemd
    [FILTER]
        Name modify
        Match systemd.*
        Rename HOSTNAME xxxx_host
    [FILTER]
        Name   kubernetes
        Match  xxxx_all.*
        Merge_Log On
        Keep_Log   Off
        Kube_Tag_Prefix xxxx_all.var.log.containers.
        Buffer_Size 0
    [FILTER]
        Name   kubernetes
        Merge_Log On
        Match  xxxx_proxy.*
        Merge_Log_Key envoy
        Keep_Log   Off
        Kube_Tag_Prefix xxxx_proxy.var.log.containers.
        Buffer_Size 0
    [FILTER]
        Name   kubernetes
        Match  xxxx_beehive.*
        Merge_Log  On
        Merge_Log_Key envoy
        Keep_Log   Off
        Kube_Tag_Prefix xxxx_beehive.var.log.containers.
        Buffer_Size 0
    [FILTER]
        Name   kubernetes
        Match  xxxx_pinot.*
        Merge_Log  On
        Merge_Log_Key envoy
        Keep_Log   Off
        Kube_Tag_Prefix xxxx_pinot.var.log.containers.
        Buffer_Size 0
    [FILTER]
        Name   kubernetes
        Match  xxx.*
        Merge_Log  On
        Merge_Log_Key envoy
        Keep_Log   Off
        Kube_Tag_Prefix xxxx.var.log.containers.
        Buffer_Size 0
    [FILTER]
        Name   kubernetes
        Match  xxx-xxx.*
        Merge_Log  On
        Merge_Log_Key envoy
        Keep_Log   Off
        Kube_Tag_Prefix xxx-xxx.var.log.containers.
        Buffer_Size 0
    [FILTER]
        Name record_modifier
        Match xxxx_cni.*
        Record xxxx_host ${HOSTNAME}
        Record xxxx_app nodes_cni
    [FILTER]
        Name nest
        Match xxxx_*
        Operation lift
        Add_prefix xxxx_
        Nested_under kubernetes
    [FILTER]
        Name nest
        Match xxxx_*
        Operation lift
        Add_prefix envoy_
        Nested_under envoy
    [FILTER]
        Name nest
        Match xxxx_*
        Operation lift
        Add_prefix xxxx_labels_
        Nested_under xxxx_labels
    [FILTER]
        Name nest
        Match xxxx_*
        Operation lift
        Add_prefix xxxx_annotations_
        Nested_under xxxx_annotations
    [FILTER]
        Name modify
        Match xxxx_*
        Rename xxxx_labels_app xxxx_app
    [FILTER]
        Name modify
        Match xxxx_*
        Condition Key_Value_Equals xxxx_container_name event-exporter
        Hard_copy event_pod_name xxxx_pod_name
        Hard_copy event_namespace_name xxxx_namespace_name
        Hard_copy event_app xxxx_app
    [FILTER]
        Name record_modifier
        Match *
        Remove_key xxxx_docker_id
        Remove_key xxxx_container_hash
        Remove_key xxxx-template-hash
        Remove_key _p
    [FILTER]
        Name modify
        Match *
        Remove_wildcard xxx
        Remove_wildcard xxx
        Remove_wildcard xxx.istio.io
        Remove_wildcard xxx
        Remove_wildcard xxx.istio.io
        Remove_wildcard xxx
    [FILTER]
        Name   lua
        Match  xxxx_all.*
        script /fluent-bit/scripts/rate_limit.lua
        call   rate_limit
    [OUTPUT]
        Name s3
        Match   xxxx.*
        bucket xxxx
        region us-east-1
        use_put_object On
        s3_key_format /$TAG[1]/%Y/%m/%d/%H/%M/%S/$UUID
        s3_key_format_tag_delimiters ._-
        total_file_size  1M
        upload_timeout 1m
    [OUTPUT]
        Name s3
        Match   xxx.*
        bucket xxxx
        region us-east-1
        use_put_object On
        s3_key_format /$TAG[1]/%Y/%m/%d/%H/%M/%S/$UUID
        s3_key_format_tag_delimiters ._-
        total_file_size  1M
        upload_timeout 1m
    [OUTPUT]
        Name s3
        Match   xxx.*
        bucket xxxx
        region us-east-1
        use_put_object On
        s3_key_format /$TAG[1]/%Y/%m/%d/%H/%M/%S/$UUID
        s3_key_format_tag_delimiters ._-
        total_file_size  1M
        upload_timeout 1m
    [OUTPUT]
        Name s3
        Match   xxxx.*
        bucket xxxx
        region us-east-1
        use_put_object On
        s3_key_format /$TAG[1]/%Y/%m/%d/%H/%M/%S/$UUID
        s3_key_format_tag_delimiters ._-
        total_file_size  1M
        upload_timeout 1m
    [OUTPUT]
        Name  forward
        Match_Regex ^(xxxx.*|xxxx.*|systemd.*|xxx.*)$
        Host  xxxxx
        Port  8007
        TLS   On
    [OUTPUT]
        name   prometheus_exporter
        match  internal_metrics
        host   0.0.0.0
        port   2023
```

**Comment by wiardvanrij** [comment] 2024-08-06 15:40
I also would like to mention that this basically never happens and I wouldn't have a way to reproduce it :D

**Comment by jvassev** [comment] 2024-08-08 14:19
> Does your output plugin have a storage limit? Do you have just one input or did you omit others?

No - single output plugin written using the go sdk to write to an external source. For my test I basically discard the event in `FLBPluginFlushCtx`.

**Comment by edsiper** [comment] 2024-08-10 13:54
comments:

- this is Fluent Bit v2.2.2 (very old)
- we need a reproducible case

Let's have a reproducible case with Fluent Bit v3, so we can troubleshoot, for now I think is better to close this one. Let's open a new one if the problem persists with v3.

**Closed by edsiper** 2024-08-10 13:54 UTC
Labels: status: waiting-for-triage
