### ISSUE TITLE
memory corruption with tail in multiline mode and defined types

### ISSUE THREAD

**Issue by tbe** [fluent/fluent-bit#1368] opened 2019-06-03 13:09 UTC
## Bug Report

**Describe the bug**
If a regex parser has defined types for the fields, the output is crippled or the whole process crashes with SEGFAULT. The output may contain sensitive content from the memory 

**To Reproduce**
- Parser definition
```
[PARSER]
  Name pglog
  Format regex
  Regex ^(?<time>(?<timeshort>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \w+) \[(?<pid>\d+)\]: \[(?<session_logline>[^\]]+)\] user=(?<user>.*?),db=(?<db>.*?),xid=(?<xid>.*?),vxid=(?<vxid>.*?) (?<type>\w+):\s*(?<message>.*)$
  Types pid:integer
  Time_Format %Y-%m-%d %H:%M:%S
  Time_Offset +0200
  Time_Key timeshort
  Time_Keep Off
```
- Test Input
```
2019-05-20 12:32:09 CEST [31192]: [11321-1] user=someuser,db=somedb,xid=0,vxid=54/84479012 LOG:  execute <unnamed>: CREATE TEMP TABLE IF NOT EXISTS "temp_login_ids" (namespace_id INT, login_id VARCHAR(255)) ON COMMIT DELETE ROWS
```
- Result
```
[0] pg.ngr: [1558348329.000000000, {"time"=>"2019-05-20 12:32:09 CEST", "pid"=>"pid�yدsession_logline�11321-1�user�someuser�db�somedb�xid�0�vxid�54/84479012�type�LOG�messageكexecute <unnamed>: CREATE TEMP TABLE IF NOT EXISTS "temp_login_ids" (namespace_id INT, login_id VARCHAR(255)) ON COMMIT DELETE ROWS_SOCKET�FLB_IS_TD_AGENT�FLB_HAVE_PROXY_GO�FLB_HAVE_SYSTEM_STRPTIME�FLB_HAVE_JEMALLOC�FLB_HAVE_LIBBACKTRACE�FLB_HAVE_REGEX�FLB_HAVE_LUAJIT�FLB_HAVE_C_TLS�FLB_HAVE_ACCEPT4�FLB_HAVE_INOTIFY��\��)��time�2019-05-20 12:32:09 CEST�pid�y�les_closed�files_rotated�filter��record_modifier.0��drop_records�add_records�output��stdout.0��proc_records�proc_bytes�errors�retries�retries_failed��proc_records�proc_bytes�errors�retries�retries_failed", "session_logline"=>"11321-1", "user"=>"someuser", "db"=>"somedb", "xid"=>"0", "vxid"=>"54/84479012", "type"=>"LOG", "message"=>"execute <unnamed>: CREATE TEMP TABLE IF NOT EXISTS "temp_login_ids" (namespace_id INT, login_id VARCHAR(255)) ON COMMIT DELETE ROWS", "hostname"=>"549dd5eb9fc3"}]
```

- Steps to reproduce the problem:
Parse the above line with the above parser with `tail` in multiline mode to any output.

**Expected behavior**
The line gets parsed

**Screenshots**
![image](https://user-images.githubusercontent.com/102155/58804081-44e5fd00-8611-11e9-8327-db4f02a5ec66.png)

**Your Environment**

* Version used: 1.1.2
* Operating System and version: Centos 7.5.1804

**Comment by edsiper** [comment] 2019-06-03 17:43
I could not reproduce the issue:

```
$ ../build/bin/fluent-bit -R parser.conf -i tail -p path=test.log -p parser=pglog -o stdout -f 1
Fluent Bit v1.2.0
Copyright (C) Treasure Data

[2019/06/03 11:39:48] [ info] [storage] initializing...
[2019/06/03 11:39:48] [ info] [storage] in-memory
[2019/06/03 11:39:48] [ info] [storage] normal synchronization mode, checksum disabled
[2019/06/03 11:39:48] [ info] [engine] started (pid=22555)
[2019/06/03 11:39:48] [ info] [sp] stream processor started
[0] tail.0: [1558348329.000000000, {"time"=>"2019-05-20 12:32:09 CEST", "pid"=>31192, "session_logline"=>"11321-1", "user"=>"someuser", "db"=>"somedb", "xid"=>"0", "vxid"=>"54/84479012", "type"=>"LOG", "message"=>"execute <unnamed>: CREATE TEMP TABLE IF NOT EXISTS "temp_login_ids" (namespace_id INT, login_id VARCHAR(255)) ON COMMIT DELETE ROWS"}]
```
> tested with v1.1.2 and GIT master

can you reproduce the problem in a different distro ?

**Comment by tbe** [comment] 2019-06-03 23:20
Also happens with a debian 9 docker image. I attached my testfile. Also tried a fresh build of 1.1.2, but that made it even worse:
![image](https://user-images.githubusercontent.com/102155/58840671-de8bc980-8666-11e9-8c97-1ea95e2432a5.png)



[test.log](https://github.com/fluent/fluent-bit/files/3249805/test.log)

**Comment by edsiper** [comment] 2019-06-04 03:06
please attach your full td-agent-bit.conf file

**Comment by edsiper** [comment] 2019-06-04 04:08
testing in debian:9 image, 

```
root@12f0feba6995:/fluent-bit-1.1.2/build# cat /etc/issue
Debian GNU/Linux 9 \n \l

root@12f0feba6995:/fluent-bit-1.1.2/build# bin/fluent-bit -R parsers.conf -i tail -p path=test.log -p parser=pglog -o stdout -f 1
Fluent Bit v1.1.2
Copyright (C) Treasure Data

[2019/06/04 04:00:40] [ info] [storage] initializing...
[2019/06/04 04:00:40] [ info] [storage] in-memory
[2019/06/04 04:00:40] [ info] [storage] normal synchronization mode, checksum disabled
[2019/06/04 04:00:40] [ info] [engine] started (pid=13831)
[2019/06/04 04:00:40] [ info] [sp] stream processor started
[0] tail.0: [1558348329.000000000, {"time"=>"2019-05-20 12:32:09 CEST", "pid"=>31192, "session_logline"=>"11321-1", "user"=>"someuser", "db"=>"somedb", "xid"=>"0", "vxid"=>"54/84479012", "type"=>"LOG", "message"=>"execute <unnamed>: CREATE TEMP TABLE IF NOT EXISTS "temp_login_ids" (namespace_id INT, login_id VARCHAR(255)) ON COMMIT DELETE ROWS"}]
```

**Comment by tbe** [comment] 2019-06-04 07:02
[config.zip](https://github.com/fluent/fluent-bit/files/3250931/config.zip)

**Comment by tbe** [comment] 2019-06-04 10:32
I found the source if the issue in in_tail. `flb_mult_flush` ignores the type of the given msgpack object, and always treats it as string

https://github.com/fluent/fluent-bit/blob/master/plugins/in_tail/tail_multiline.c#L405

But if the type is an integer, the value of the int is used as buffer size.

![image](https://user-images.githubusercontent.com/102155/58872633-c21e7a00-86c4-11e9-87f6-8ae01c98f778.png)

**Comment by edsiper** [comment] 2019-06-04 22:10
thanks for providing such details. I've pushed fix 826c84f9 in GIT master. It will be part of 1.1.3 release next week.

**Comment by tbe** [comment] 2019-06-04 22:46
Thanks for the quick response.

I had a look on the commit. With the new code, the multiline parser will break if the last value is an int, even if there are successive parser for the following lines. There will never be a multiline flush for this kind of parsers, resulting in lines with just the `log` key.

I will propose a fix later

**Comment by edsiper** [comment] 2020-05-05 18:02
#1373 has been merged.

**Closed by edsiper** 2020-05-05 18:02 UTC
Labels: bug, troubleshooting
