### ISSUE TITLE
Trace down random test failures on input plugin tests (Travis CI)

### ISSUE THREAD

**Issue by fujimotos** [fluent/fluent-bit#1231] opened 2019-03-28 04:13 UTC
### Bug

I see the tests `flb-rt-in_*` failing randomly on Travis (1 in 5-6 runs).

    [ FAILED ]
      in_random.c:123: Check ret == 0... failed
      in_random.c:128: Check ret > start + 900 && ret < start + 4000... failed
    FAILED: 1 of 1 unit tests have failed.

The oldest failure case I know is jobs/459115779 (Nov 2018), so it must not
be something  introduced recently. But still, these failures are irritating since they
are breaking builds for innocent feature branches (e.g. #1153, #1155 and #1208).

Let's add some fix for it.

### Links

Here is several failing test runs:

* https://travis-ci.org/fluent/fluent-bit/jobs/459115779
* https://travis-ci.org/fluent/fluent-bit/jobs/468288568
* https://travis-ci.org/fluent/fluent-bit/jobs/511732351
* https://travis-ci.org/fluent/fluent-bit/jobs/498933831
* https://travis-ci.org/fluent/fluent-bit/jobs/495195149

**Comment by fujimotos** [comment] 2019-03-28 09:46
I spent part of today poking at this issue. As far as I can tell,
it's a pure timing problem.

Right now we run TEST_CHECK three times in each test following the
schedule below:

    0    1    2    3    4    5
    |----*----F1-2-*----F3---|

    F ... Flush (scheduled)
    1 ... Test if data has been flushed
    2 ... Test if data has NOT been flushed
    3 ... Test if data has been flushed

The crucial point is that the first check (1) is designed to wait
up to 4 seconds in order to absorb random delays on slow servers.
This fix, however, is causing another class of errors, since now we
CAN have another flush between (1) and (2), which is the root cause
of the current test failures.

I tested several tweaks this evening, including adjusting timeout
or modifying flags we pass to timerfd_settime() in epoll backend,
but it seems like there is no clear magic solution that works reliably.

**Comment by donbowman** [comment] 2019-03-29 12:26
maybe we can add a test hook in fluent-bit core so that flush becomes explicit rather than timer driven?

e.g. disable the flush-on-interval, and have the test code call flush explicitly.

**Comment by edsiper** [comment] 2019-03-29 16:10
- I see the main problem is that CI system might respond slower than our tests in some specific cases. 

- In the case of in_random, the problem is that it can take a long time if there is not enough entropy in the system, so having a direct callback as soon the data is available can let the program on hold/stuck. 

Since we don't really care about system random capabilities and it entropy level for what Fluent Bit does, we could simply disable in_random test. I know this is a kind of 'antipattern'.

I am looking at PR #1232 now...

**Comment by edsiper** [comment] 2019-04-03 23:03
Fixed by #1232, thanks.

**Closed by edsiper** 2019-04-03 23:03 UTC
