### ISSUE TITLE
[parser] Invalid time format on Alpine Linux

### ISSUE THREAD

**Issue by StevenACoffman** [fluent/fluent-bit#231] opened 2017-04-10 18:58 UTC
It appears that the parser is not working correctly for some date formats, using the existing parsers.conf. 
When I do this:

```bash
echo '127.0.0.1 - - [03/Apr/2017:15:36:41 +0000] "GET /server-s
tatus?auto HTTP/1.1" 200 499 "-" "collectd/5.4.0.git"' | ./bin/fluent-bit -v -i
stdin -p Parser=apache2 --parser=../conf/parsers.conf -o stdout
```

I get:

```bash 
[parser] Invalid time format %d/%b/%Y:%H:%M:%S %z
```

However, it parses fine if I do this in ruby:
```ruby
require 'date'
DateTime.strptime("03/Apr/2017:15:35:10 +0000", "%d/%b/%Y:%H:%M:%S %z")
```

**Comment by StevenACoffman** [comment] 2017-04-10 18:59
This is the relevant portion from the parser.conf for reference:
```python
[PARSER]
    Name   apache2
    Format regex
    Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
    Time_Key time
    Time_Format %d/%b/%Y:%H:%M:%S %z
```

**Comment by edsiper** [comment] 2017-04-12 16:48
@StevenACoffman 

I cannot reproduce the problem here locally, here it works as expected:

```
$ echo '127.0.0.1 - - [03/Apr/2017:15:36:41 +0000] "GET /server-status?auto HTTP/1.1" 200 499 "-" "collectd/5.4.0.git"' | bin/fluent-bit -i stdin -R ../conf/parsers.conf -p parser=apache2 -o stdout -f 2
Fluent-Bit v0.12.0
Copyright (C) Treasure Data

[2017/04/12 10:46:54] [ info] [engine] started
[2017/04/12 10:46:54] [ warn] [in_stdin] end of file (stdin closed by remote end)
[2017/04/12 10:46:54] [ info] [input] pausing stdin.0
[0] stdin.0: [1491255401.000000000, {"host"=>"127.0.0.1", "user"=>"-", "method"=>"GET", "path"=>"/server-status?auto", "code"=>"200", "size"=>"499", "referer"=>"-", "agent"=>"collectd/5.4.0.git"}]
```

are you using the latest version from GIT Master ? (note that stdin + parse support is only available for the next 0.12 major release)

**Comment by StevenACoffman** [comment] 2017-04-13 02:04
Hrm... I attempted it again, and I am seeing different results, so I may be doing something wrong. Here's how I was able to reproduce the problem:
```bash
git clone git@github.com:fluent/fluent-bit.git
cp apache_error.log ./fluent-bit
cp apache_access.log ./fluent-bit
docker run -v /Users/scoffman/Documents/git/fluent-bit:/fluenty --name myfluent --rm -it alpine sh
 
apk add --update alpine-sdk
apk add --update build-base gcc abuild binutils binutils-doc gcc-doc
apk add --update cmake cmake-doc
 
cd /fluenty/build
cmake ..
make

 echo '127.0.0.1 - - [03/Apr/2017:15:36:41 +0000] "GET /server-status?auto HTTP/1.1" 200 499 "-" "collectd/5.4.0.git"' | bin/fluent-bit -i stdin -R ../conf/parsers.conf -p parser=apache2 -o stdout -f 2
```

I received this output:
```
[2017/04/12 21:34:39] [ info] [engine] started
[0] stdin.0: [0.000000000, {"host"=>"127.0.0.1", "user"=>"-", "method"=>"GET", "path"=>"/server-status?auto", "code"=>"200", "size"=>"499", "referer"=>"-", "agent"=>"collectd/5.4.0.git"}]
[2017/04/12 21:34:39] [error] [parser] Invalid time format %d/%b/%Y:%H:%M:%S %z
[2017/04/12 21:34:39] [ warn] [in_stdin] end of file (stdin closed by remote end)
[2017/04/12 21:34:39] [ info] [input] pausing stdin.0
[2017/04/12 21:34:39] [ warn] [engine] service will stop in 5 seconds
[2017/04/12 21:34:44] [ info] [engine] service stopped
```

During the build, I did get several warnings:
```
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
```

**Comment by StevenACoffman** [comment] 2017-04-13 11:35
I can delete the cloned fluent-bit repo, restart my machine, repeat the process and reliably get this result.

**Comment by StevenACoffman** [comment] 2017-04-13 13:06
This may be an issue in alpine linux.
> I believe that strftime in Alpine Linux does not respect the tzinfo of the datetime object, either. I had to make sure I had a datetime in local time and then .replace(tzinfo=None) to get the time to show up correctly, too.
There are more details here: https://github.com/iron-io/dockers/issues/42

**Comment by StevenACoffman** [comment] 2017-04-13 13:43
When I change the timeformat in the parsers.conf to be `%d/%b/%Y:%H:%M:%S %Z` I get the same error.

When I change the timeformat to `%d/%b/%Y:%H:%M:%S +0000` it works fine. Since we always use UTC, this works around the problem for us, but will affect any Alpine linux (docker) users that don't.

With a little more investigation, it appears that alpine linux uses musl instead of glibc. Looking through the musl source code to [strptime.c](http://git.musl-libc.org/cgit/musl/tree/src/time/strptime.c) and [strftime.c](https://github.com/BlankOn/musl/blob/master/src/time/strftime.c) I see that while strftime.c has a `z` case, strptime.c does not. My C is _weak_ so that's about all I can suss out. Not sure if that's at all helpful. 

Thanks again for your awesome work on fluent, and I really appreciate how responsive you've been, to me and to everyone else. I can see why everyone loves working with Treasure Data, if you're at all representative of the culture.

**Comment by edsiper** [comment] 2017-04-13 17:07
hi @StevenACoffman 

thanks for research the issue. Definitely Fluent Bit and Musl based environments are not compatible, before this issue we also had:

- Jemalloc (memory allocator) on Musl cannot be integrated properly
- Musl functions bootstrap have a compatibility issue when loading Golang shared libraries

Few weeks ago I gave up trying to workaround Alpine Linux problems because of Musl. If you are using Docker I suggest you check our images at Docker Hub [fluent/fluent-bit](https://hub.docker.com/r/fluent/fluent-bit/), next week I will push some images based on GIT master (0.12).

For now let's take it as "Alpine Linux + Musl" is __not__ supported by Fluent Bit.

Thanks for your kind words, Treasure Data is an awesome place to work :)

For now I am closing this issue.

**Closed by edsiper** 2017-04-13 17:07 UTC
