### ISSUE TITLE
in_systemd memory leak when dynamic tag and filter are enabled

### ISSUE THREAD

**Issue by kabakaev** [fluent/fluent-bit#693] opened 2018-07-25 13:12 UTC
## Bug Report
`fluent-bit` is consuming RAM till it gets killed by kernel OOM killer at 400MB.

I tried to find which part is using so much memory. Valgrind suggests that it is some part of `in_systemd_collect()` in `systemd.c`.

The issue occurs only when a bunch of filters are enabled between input and oputput.

**Steps to reproduce**

```
$ git log -1
commit adec302571268125aca5f2edd986a3ca715f18d1 (HEAD -> master, origin/master, origin/HEAD)
$ cd /tmp/src/build/
$ sudo apt-get install valgrind
$ cmake   -DFLB_DEBUG=On \
          -DFLB_TRACE=On \
          -DFLB_MTRACE=On \
          -DFLB_VALGRIND=On \
          -DFLB_JEMALLOC=On \
          -DFLB_BUFFERING=On \
          -DFLB_TLS=On \
          -DFLB_WITHOUT_SHARED_LIB=On \
          -DFLB_WITHOUT_EXAMPLES=On \
          -DFLB_HTTP_SERVER=On \
          -DFLB_OUT_KAFKA=Off ..
$ make -j 8
# create docker container, put custom config into `/fluent-bit/etc/fluent-bit.conf`, as given below
$ /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit --sosreport
Fluent-Bit v0.14.0
Copyright (C) Treasure Data

[2018/07/25 10:31:12] [error] [parser:crio] Invalid format Regex
[2018/07/25 10:31:12] [ info] [engine] started (pid=186)
[2018/07/25 10:31:12] [debug] [in_systemd] add filter: _SYSTEMD_UNIT=docker.service (or)
[2018/07/25 10:31:12] [debug] [in_systemd] add filter: _SYSTEMD_UNIT=docker.service (or)
[2018/07/25 10:31:12] [debug] [in_tail] inotify watch fd=64
[2018/07/25 10:31:12] [debug] [in_tail] scanning path /var/log/k8s/kube-apiserver/audit.log
[2018/07/25 10:31:12] [debug] [in_tail] Cannot read info from: /var/log/k8s/kube-apiserver/audit.log
[2018/07/25 10:31:12] [debug] [filter_modify] Initialized modify filter with 0 conditions and 16 rules
[2018/07/25 10:31:12] [ warn] [filter_kube] merge_json_log is deprecated, enabling 'merge_log' option instead
[2018/07/25 10:31:12] [ info] [filter_kube] https=1 host=kubernetes.default.svc port=443
[2018/07/25 10:31:12] [ info] [filter_kube] local POD info OK
[2018/07/25 10:31:12] [ info] [filter_kube] testing connectivity with API server...
[2018/07/25 10:31:12] [debug] [filter_kube] API Server (ns=kube-system, pod=fluent-bit-hwrqx) http_do=0, HTTP Status: 200
[2018/07/25 10:31:12] [ info] [filter_kube] API server connectivity OK
[2018/07/25 10:31:12] [debug] [router] input=systemd.0 'DYNAMIC TAG'
[2018/07/25 10:31:12] [debug] [router] input=systemd.1 'DYNAMIC TAG'
[2018/07/25 10:31:12] [debug] [router] input=systemd.2 'DYNAMIC TAG'
[2018/07/25 10:31:12] [debug] [router] input=tail.0 'DYNAMIC TAG'

Fluent Bit Enterprise - SOS Report
==================================
The following report aims to be used by Fluent Bit and Fluentd Enterprise
Customers of Treasure Data. For more details visit:

    https://fluentd.treasuredata.com

[Fluent Bit]
    Edition             Community Edition
    Version             0.14.0
    Built Flags          JSMN_PARENT_LINKS JSMN_STRICT FLB_HAVE_TLS FLB_HAVE_SQLDB FLB_HAVE_BUFFERING FLB_HAVE_TRACE FLB_HAVE_METRICS FLB_HAVE_HTTP_SERVER FLB_HAVE_FLUSH_LIBCO FLB_HAVE_SYSTEMD FLB_HAVE_VALGRIND FLB_HAVE_FORK FLB_HAVE_MTRACE FLB_HAVE_TIMESPEC_GET FLB_HAVE_PROXY_GO FLB
_HAVE_JEMALLOC JEMALLOC_MANGLE FLB_HAVE_LIBBACKTRACE FLB_HAVE_REGEX FLB_HAVE_LUAJIT FLB_HAVE_C_TLS FLB_HAVE_ACCEPT4 FLB_HAVE_INOTIFY

[Operating System]
    Name                Linux
    Release             3.10.0-693.21.1.el7.x86_64
    Version             #1 SMP Wed Mar 7 19:03:37 UTC 2018

[Hardware]
    Architecture        x86_64
    Processors          2

[Built Plugins]
    Inputs              cpu mem kmsg tail proc disk systemd netif dummy head exec health serial stdin tcp mqtt lib forward random syslog
    Filters             grep stdout throttle kubernetes parser lua record_modifier nest modify
    Outputs             azure counter es exit file forward http influxdb kafka-rest nats null plot splunk stackdriver stdout td lib flowcounter

[SERVER] Runtime configuration
    Flush               1
    Daemon              Off
    Log_Level           Debug

[INPUT] Instance
    Name                systemd.0 (systemd, id=0)
    Flags               DYN_TAG
    Threaded            No
    Tag                 sys_systemd_.*
    Mem_Buf_Limit       976.6K
    Path                /var/log/journal
    Max_Entries         5000
    Read_From_Tail      true

[INPUT] Instance
    Name                systemd.1 (systemd, id=1)
    Flags               DYN_TAG
    Threaded            No
    Tag                 sys_k8s_.*
    Mem_Buf_Limit       976.6K
    Path                /var/log/journal
    Max_Entries         5000
    Systemd_Filter      _SYSTEMD_UNIT=docker.service
    Read_From_Tail      true

[INPUT] Instance
    Name                systemd.2 (systemd, id=2)
    Flags               DYN_TAG
    Threaded            No
    Tag                 user_k8s_.*
    Mem_Buf_Limit       976.6K
    Path                /var/log/journal
    Max_Entries         5000
    Systemd_Filter      _SYSTEMD_UNIT=docker.service
    Read_From_Tail      true

[INPUT] Instance
    Name                tail.0 (tail, id=0)
    Flags               DYN_TAG
    Threaded            No
    Tag                 sys_k8saudit
    Mem_Buf_Limit       976.6K
    Path                /var/log/k8s/kube-apiserver/audit.log
    Parser              k8saudit_parser
    Refresh_Interval    61
    Skip_Long_Lines     Off
    Read_From_Tail      true

[FILTER] Instance
    Name                grep.0 (grep, id=0)
    Match               *_k8s_*
    Regex               CONTAINER_NAME k8s_
    Exclude             CONTAINER_NAME k8s_fluent-bit
[FILTER] Instance
    Name                record_modifie (record_modifier, id=0)
    Match               *_k8s_*
    Remove_key          _EXE
    Remove_key          EXE
    Remove_key          _CAP_EFFECTIVE
    Remove_key          CAP_EFFECTIVE
    Remove_key          _CMDLINE
    Remove_key          CMDLINE
    Remove_key          _COMM
    Remove_key          COMM
    Remove_key          _GID
    Remove_key          GID
    Remove_key          _PID
    Remove_key          PID
    Remove_key          _SOURCE_REALTIME_TIMESTAMP
    Remove_key          SOURCE_REALTIME_TIMESTAMP
    Remove_key          _SYSTEMD_CGROUP
    Remove_key          SYSTEMD_CGROUP
    Remove_key          _SYSTEMD_SLICE
    Remove_key          SYSTEMD_SLICE
    Remove_key          _SYSTEMD_UNIT
    Remove_key          SYSTEMD_UNIT
    Remove_key          _TRANSPORT
    Remove_key          TRANSPORT
    Remove_key          _UID
    Remove_key          UID
    Remove_key          PRIORITY
    Remove_key          SYSLOG_IDENTIFIER
[FILTER] Instance
    Name                modify.0 (modify, id=0)
    Match               *
    Rename              _BOOT_ID BOOT_ID
    Rename              _CAP_EFFECTIVE CAP_EFFECTIVE
    Rename              _CMDLINE CMDLINE
    Rename              _COMM COMM
    Rename              _EXE EXE
    Rename              _GID GID
    Rename              _HOSTNAME HOSTNAME
    Rename              _MACHINE_ID MACHINE_ID
    Rename              _PID PID
    Rename              _SOURCE_REALTIME_TIMESTAMP SOURCE_REALTIME_TIMESTAMP
    Rename              _SYSTEMD_CGROUP SYSTEMD_CGROUP
    Rename              _SYSTEMD_SLICE SYSTEMD_SLICE
    Rename              _SYSTEMD_UNIT SYSTEMD_UNIT
    Rename              _TRANSPORT TRANSPORT
    Rename              _UID UID
    Rename              MESSAGE log
[FILTER] Instance
    Name                grep.1 (grep, id=1)
    Match               user_k8s_*
    Exclude             CONTAINER_NAME k8s_.*_kube-system_
[FILTER] Instance
    Name                grep.2 (grep, id=2)
    Match               sys_k8s_*
    Regex               CONTAINER_NAME k8s_.*_kube-system_
    Regex               CONTAINER_NAME k8s_.*_kube-public_
    Regex               CONTAINER_NAME k8s_.*_tc-system_
[FILTER] Instance
    Name                grep.3 (grep, id=3)
    Match               sys_systemd_.*
    Exclude             CONTAINER_NAME k8s_
[FILTER] Instance
    Name                kubernetes.0 (kubernetes, id=0)
    Match               *_k8s_*
    Use_Journal         true
    Tag_Key             flb-tag
    Kube_URL            https://kubernetes.default.svc:443
    Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
    Merge_JSON_Log      On
    K8S-Logging.Parser  On
    K8S-Logging.Exclude On

[OUTPUT] Instance
    Name                file.0 (file, mask_id=1)
    Match               *
    TLS Active          No
    Retry Limit         1
    Path                /dev/null

$ while true ; do logger asdf ; echo ok ; done &
# collect memory usage of a running fluent-bit
$ /usr/bin/valgrind.bin --leak-check=yes /fluent-bit/bin/fluent-bit -c /tmp/v2/fluent-bit.conf &>/tmp/flb.out &
$ sleep 1800
$ gdb
(gdb) set non-stop off
(gdb) target remote | vgdb
(gdb) monitor xtmemory
==162== xtree memory report: /tmp/v2/xtmemory.kcg.162.2
(gdb) quit
```

[xtmemory.kcg.162.2.gz](https://github.com/fluent/fluent-bit/files/2227976/xtmemory.kcg.162.2.gz)

Use `kcachegrind` to render the /tmp/v2/xtmemory.kcg.162.2:
![flb-with-filters](https://user-images.githubusercontent.com/6826176/43202527-0d45f3e6-901c-11e8-8453-7cebc5b111d7.png)

Now, remove all `[FILTER]` sections from the config and retry.

```
$ /usr/bin/valgrind.bin --leak-check=yes /fluent-bit/bin/fluent-bit -c /tmp/v2/fluent-bit.conf-512kb-no-filter &> flb-nofilter.out &
$ sleep 1800
$ gdb
(gdb) set non-stop off
(gdb) target remote | vgdb
(gdb) monitor xtmemory
==241== xtree memory report: /tmp/v2/xtmemory.kcg.241.4
(gdb) quit
```
[xtmemory.kcg.241.4.gz](https://github.com/fluent/fluent-bit/files/2227979/xtmemory.kcg.241.4.gz)

Memory profile without filters looks different:
![flb-no-filters](https://user-images.githubusercontent.com/6826176/43202579-2d41852a-901c-11e8-8f20-3ca19caf9859.png)

The `fluent-bit` RAM usage without filters does not increase too much over time.

**Expected behavior**
`in_systemd` with `[FILTER]`s should not consume too much RAM.

**Environment**
* Version used: master rev. adec3025.
* Configuration, filters and plugins: see "SOSreport" above.
* Environment name and version: Kubernetes-v1.9.9
* Server type and version: standard docker image from fluent-bit-v0.13.2. Profiling is done on the image built with `cmake` parameters given above.
* Operating System and version: CentOS-7, vanilla docker-v18.03.

**Additional context**
I aim to collect docker logs from systemd, enrich them with pod info from kubernetes api, and send separately to various stores:
* all logs from user containers should be sent to a user-managed `fluent-bit` instance using `out_forward`;
* all other systemd logs should go into an `elasticsearch` instance.

**Comment by kabakaev** [comment] 2018-07-26 19:48
Looking at [the corresponding code](https://github.com/fluent/fluent-bit/blob/v0.13.5/plugins/in_systemd/systemd.c#L158), one may see that if the `tag` is changing, then a new piece of memory [is allocated for buffer](https://github.com/fluent/fluent-bit/blob/v0.13.5/plugins/in_systemd/systemd.c#L164).

As long as my config was written with dynamic tags (a star at the end of INPUT.Tag), it is guaranteed that [tag name will change very often](https://github.com/fluent/fluent-bit/blob/v0.13.5/plugins/in_systemd/systemd.c#L115), just because systemd receives logs from various `_SYSTEMD_UNIT`s, which is the tag suffix.
So, removing the dynamic tag generation from config file does solve the memory leak issue.

I don't really need the dynamic tag functionality, so my problem is kind of solved.

Still, i guess fixing this bug should optimise overall memory usage.

**Comment by Misterhex** [comment] 2018-08-09 12:14
Hi I am getting this even with input.tag without *.    Could you share your configuration that is the workaround for this?

**Comment by edsiper** [comment] 2018-08-10 23:38
FYI: I am troubleshooting this issue.

**Comment by edsiper** [comment] 2018-08-11 03:25
I have not been able to reproduce the problem locally. Do you think you can minimize the test case reducing the number of  filters and inputs ?

**Comment by edsiper** [comment] 2018-08-21 11:31
@kabakaev ping

**Comment by kabakaev** [comment] 2018-09-04 23:32
I was unable to reproduce the issue outside of my kubernetes cluster. 
I would need some more time to try reproducing it at labs.play-with-k8s.com.

**Comment by edsiper** [comment] 2018-10-29 04:14
Found the root cause of the problem:

If a filter remove __all__ the content of a dyntag buffer, it final size is zero and the engine skip the reference since there is nothing to process, but the context remain.

Issue fixed on 9fc067a1.

**Comment by bluebike** [comment] 2018-10-29 19:38
Looked  filter_modify: 
 https://github.com/fluent/fluent-bit/blob/9fc067a17ebad30a1c623e75c6dc8ad63aee4d0e/plugins/filter_modify/modify.c#L1409-L1412

There seems to be memory leak, because  returned buffer is freed unless  ```ret == FLB_FILTER_MODIFIED```

https://github.com/fluent/fluent-bit/blob/9fc067a17ebad30a1c623e75c6dc8ad63aee4d0e/src/flb_filter.c#L95-L106

Made pull request: #870

**Comment by edsiper** [comment] 2018-10-31 03:13
changes merged, issue fixed.

**Closed by edsiper** 2018-10-31 03:13 UTC
Labels: bug, fixed
