### ISSUE TITLE
Linux packages not working for centos (aarch64 / arm64v8)

### ISSUE THREAD

**Issue by noly** [fluent/fluent-bit#4270] opened 2021-11-02 18:43 UTC
Cloned from #4007

## Bug Report

**Describe the bug**
I'm getting an error while running FB in Centos 8 in arm.

**To Reproduce**
* Start a Centos 7/8 or RedHat linux instance for arm64 (AWS, GCP, etc..): I tested in aws CentOS Stream 8 aarch64 20210603 community AMI
* Follow the installation process https://docs.fluentbit.io/manual/installation/linux/redhat-centos:
`sudo yum install td-agent-bit`

**Expected behavior**
Fluent-bit works.

**Screenshots**
_Execution error_:
```
/opt/td-agent-bit/bin/td-agent-bit -i cpu -t my_cpu -o stdout -m '*'
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
FATAL: error reading `/proc/sys/crypto/fips_enabled' in libgcrypt: Cannot allocate memory
<jemalloc>: Unsupported system page size
Aborted (core dumped)
```

<img width="1082" alt="Screen Shot 2021-11-02 at 19 37 50" src="https://user-images.githubusercontent.com/4612272/139924995-7228e80f-31e9-416c-a050-5d63cdf582c1.png">

_Service start up error_:
```
$ service td-agent-bit status

td-agent-bit.service - TD Agent Bit
   Loaded: loaded (/usr/lib/systemd/system/td-agent-bit.service; disabled; vendor preset: disabled)
   Active: failed (Result: core-dump) since Tue 2021-11-02 18:21:44 UTC; 3s ago
  Process: 10989 ExecStart=/opt/td-agent-bit/bin/td-agent-bit -c /etc/td-agent-bit/td-agent-bit.conf (code=dumped, signal=ABRT)
 Main PID: 10989 (code=dumped, signal=ABRT)

Nov 02 18:21:44: td-agent-bit.service: Service RestartSec=100ms expired, scheduling restart.
Nov 02 18:21:44: td-agent-bit.service: Scheduled restart job, restart counter is at 5.
Nov 02 18:21:44: Stopped TD Agent Bit.
Nov 02 18:21:44: td-agent-bit.service: Start request repeated too quickly.
Nov 02 18:21:44: td-agent-bit.service: Failed with result 'core-dump'.
Nov 02 18:21:44: Failed to start TD Agent Bit.
```

**Your Environment**
Version used: fluent-bit 1.8.9
Configuration: default/standard
Environment: AWS Linux Centos 8

**Comment by edsiper** [comment] 2021-11-02 21:40
are you able to reproduce the issue with Centos 7 ? (we don't ship packages for Centos 8)

**Comment by noly** [comment] 2021-11-03 09:43
Hi @edsiper. Yes, I was able to reproduce the issue in AWS AMi **CentOS 7.9.2009 aarch64**

<img width="1642" alt="Screen Shot 2021-11-03 at 10 39 13" src="https://user-images.githubusercontent.com/4612272/140037924-49a05657-c9c6-49a7-af50-2ffea0d9d166.png">


Even thou you don't ship packages for CentOs8 it's a [supported platforms](https://docs.fluentbit.io/manual/installation/supported-platforms).

**Comment by noly** [comment] 2021-12-07 10:54
Commenting to avoid stale

**Comment by patrick-stephens** [comment] 2021-12-20 15:08
I'll pick up to try to include in the staging test updates.

**Comment by patrick-stephens** [comment] 2021-12-24 11:47
@noly to keep you in the loop, the staging test workflow is in place now so I'll start extending tests to see if I can replicate although probably after the holidays now.

**Comment by ANBUZHIDAO** [comment] 2022-01-11 11:20
I also found the problem when I use the arm64 image in k8s
please see https://github.com/jemalloc/jemalloc/issues/467

I think this is because jmemalloc compiled-in page size 4k, if your arm64 machine pagesize is 64k, it will not work.
`getconf PAGESIZE`  can get the pagesize.

I change the dockerfile not use jemalloc and build a new image myself, then it can work on my arm64 machine. my arm64 machine pagesize is 65536.

**Comment by patrick-stephens** [comment] 2022-01-11 11:32
I'll admit I'm not an expert but looking at that issue it appears there is no general solution to it - you have to compile for your page size. Do you have a suggestion on what to do @ANBUZHIDAO for Fluent Bit containers or was this just for info on people who have the issue? We can/should document it as well.

**Comment by patrick-stephens** [comment] 2022-01-31 20:40
I've not forgotten... @noly did you see the page size comment above, is it relevant to your set up?

**Comment by noly** [comment] 2022-02-01 18:21
Hi @patrick-stephens, it is relevant indeed. Fedoras distro use 64k as page size:

<img width="868" alt="Screen Shot 2022-02-01 at 15 18 22" src="https://user-images.githubusercontent.com/4612272/152027228-5206536a-50b7-4675-8ca4-b5fd1fb80922.png">

Are you planing to release a fixed version of arm64 bin with correct page_size?

**Comment by patrick-stephens** [comment] 2022-02-02 09:26
If that is the default for Fedora we probably should - do you know if it is always the default and also for the downstream Red Hat distros as well? I'd rather not have to make another distro-specific artefact so be good if we can share them.

The packages are all compiled via containerised builds currently: https://github.com/fluent/fluent-bit/blob/master/packaging/distros/centos/Dockerfile 

My concern as well is testing, verifying this is tricky in CI I think but I do need to ramp up the ARM tests specifically in this area. 

A PR would really help if you get a chance so ping me if you do and I'll push for it.

**Comment by icereed** [comment] 2022-03-07 06:42
@ANBUZHIDAO, I would also be very interested in your ARM build.

I'm facing the same error using the Docker image in a Oracle Linux VM with Oracle Kubernetes Engine using ARM instances.
Inside any container the page size is reported to be 65536:

```shell
bash-5.1$ getconf PAGESIZE
65536
```

I would be fine to have a binary without jemalloc for the time being.

**Comment by cosmo0920** [comment] 2022-03-07 10:37
We should use the configure option to specify 65535 page size on CentOS as: --with-lg-page=16

**Comment by patrick-stephens** [comment] 2022-03-07 10:43
Seems a good shout so if anyone can submit a PR just ping me if it needs approval.

**Comment by ANBUZHIDAO** [comment] 2022-03-07 10:56
> 

I just change `-DFLB_JEMALLOC=On` to `-DFLB_JEMALLOC=Off` in the dockerfiles/Dockerfile
Maybe this have worse performance, but it worked and it's enough for me.

**Comment by patrick-stephens** [comment] 2022-03-08 08:21
So it does sound like for CentOS 7 arm derivatives the default page size determined during the build is incorrect. This may be down to using QEMU on Ubuntu hosts as it is run with Github Actions.

https://github.com/pypa/manylinux/issues/735

We need to ensure therefore it is built with the right settings on the CentOS containers.

**Comment by patrick-stephens** [comment] 2022-03-08 10:31
@noly just to keep you in the loop, we've identified a fix for this but I also want to add some verification to prevent it happening again so may take a bit of effort to sort.

**Comment by noly** [comment] 2022-03-09 09:53
@patrick-stephens sounds great!! Thanks for taking care of this issue.

**Comment by patrick-stephens** [comment] 2022-03-09 10:05
@noly Any chance you can just test the change to confirm on master? CI testing is still WIP so if you have an actual target you can run on that would be ace to confirm.

I'm just pushing a change to allow me to build a specific target for `master` as that will mean you can just download the package then as built by the official CI, i.e. on an Ubuntu AMD64 host. 

Otherwise if you have a similar host and can set up QEMU on it then we can build the same target manually:
```
./packaging/build.sh -v master -b master -d centos/.arm64v8
```

**Comment by patrick-stephens** [comment] 2022-03-09 11:12
@noly (and anyone else) can you test the packages from here (once completed) on your target to confirm?
https://github.com/fluent/fluent-bit/actions/runs/1956875452

You can now control jemalloc configuration via the `FLB_JEMALLOC_OPTIONS` CMake variable, it defaults to `--with-lg-quantum=3` so make sure to add that in any override.

**Comment by patrick-stephens** [comment] 2022-03-09 12:52
Looks like it is not splitting the arguments so I'll fix that:

```CONFIG             : '--with-lg-page=16 --with-lg-quantum=3'```

Apologies for that.

**Comment by patrick-stephens** [comment] 2022-03-09 15:42
One good aspect this picked up was that the default `fluent-bit` package was being built without jemalloc so fixed two bugs for the price of 1 @noly !

**Closed** 2022-03-09 21:48 UTC

**Comment by patrick-stephens** [comment] 2022-03-10 09:28
@noly try this one https://github.com/fluent/fluent-bit/actions/runs/1961696121

There should be a package to download based on master for the ARM 64 target

**Comment by noly** [comment] 2022-03-10 10:20
On my way!!

**Comment by noly** [comment] 2022-03-10 10:56
Did a fast test and worked!! 👯 

<img width="1636" alt="Screen Shot 2022-03-10 at 11 54 02" src="https://user-images.githubusercontent.com/4612272/157647402-0e4df32f-0c00-4006-bc73-999b8703df28.png">

Amazing work everyone!! and Kudos to you @patrick-stephens!!!

**Comment by noly** [comment] 2022-03-11 15:03
@patrick-stephens do you know when this change will be available? is with v1.9.0?

**Comment by patrick-stephens** [comment] 2022-03-11 15:06
yes, the staging builds from 1.9 should also have it if you want to test the latest RC: https://github.com/fluent/fluent-bit/actions/runs/1961119944

**Comment by patrick-stephens** [comment] 2022-03-11 15:09
I've updated the discussion on RCs as well with the details: https://github.com/fluent/fluent-bit/discussions/4954

**Comment by patrick-stephens** [comment] 2022-03-11 15:10
The next 1.8 release should also have it, basically the next release of either.

**Comment by loxiaopohaiol** [comment] 2022-08-24 08:39
@patrick-stephens I use the lates images on the arm64 machine, have the same problem:
![image](https://user-images.githubusercontent.com/48348273/186371941-55827672-394d-4914-9846-99ecd2885b3b.png)

**Comment by patrick-stephens** [comment] 2022-08-24 08:42
Container images? They're debian based.

**Comment by loxiaopohaiol** [comment] 2022-08-24 08:53
> Container images? They're debian based.

I use the fluent/fluent-bit:latest  docker images to running the fluentbit , but it has the same error log. My machine is arm64 and the OS is YHKYLIN-OS（base on linux）

**Comment by patrick-stephens** [comment] 2022-08-24 08:54
The container images are a Debian distro so sounds like your distro uses a different page size is my guess. Can you confirm the page size your distro uses (I've never heard of it)?

**Comment by loxiaopohaiol** [comment] 2022-08-24 08:59
> DFLB_JEMALLOC

The system page size looks like is 65535:
![image](https://user-images.githubusercontent.com/48348273/186376685-8603520c-aa8d-42f3-9f51-859b2a7e6a6e.png)

**Comment by lusson-luo** [comment] 2022-09-06 12:38
> The container images are a Debian distro so sounds like your distro uses a different page size is my guess. Can you confirm the page size your distro uses (I've never heard of it)?

+1
